/* Operation Turtle Property Intelligence configuration and pure helpers.
   The six-category score is read-only until the app explicitly persists it. */
(function(){
  'use strict';
  const DETAILED_SCORECARD_CATEGORIES=[
    {id:'privacy',label:'Privacy',weight:10,strength:'Excellent privacy'},
    {id:'mountainViews',label:'Mountain Views',weight:6,strength:'Strong mountain views'},
    {id:'buildability',label:'Buildability',weight:10,strength:'Strong build site'},
    {id:'recreation',label:'Recreation',weight:7,strength:'Great recreation potential'},
    {id:'hunting',label:'Hunting',weight:5,strength:'Strong hunting potential'},
    {id:'waterFeatures',label:'Water Features',weight:6,strength:'Notable water features'},
    {id:'roadAccess',label:'Road Access',weight:7,strength:'Strong road access'},
    {id:'utilities',label:'Utilities',weight:9,strength:'Utilities are well positioned'},
    {id:'airportAccess',label:'Airport Access',weight:5,strength:'Convenient airport access'},
    {id:'costcoAccess',label:'Costco Access',weight:4,strength:'Convenient Costco access'},
    {id:'homeDepotAccess',label:'Home Depot Access',weight:4,strength:'Convenient Home Depot access'},
    {id:'lowesAccess',label:"Lowe's Access",weight:4,strength:"Convenient Lowe's access"},
    {id:'groceryAccess',label:'Grocery Access',weight:5,strength:'Convenient grocery access'},
    {id:'hospitalAccess',label:'Hospital Access',weight:5,strength:'Convenient hospital access'},
    {id:'internetAvailability',label:'Internet Availability',weight:7,strength:'Internet availability is promising'},
    {id:'overallFeeling',label:'Overall Feeling',weight:6,strength:'Strong overall fit'}
  ];
  const SIMPLIFIED_SCORECARD_CATEGORIES=[
    {id:'landBuildability',label:'Land & Buildability',weight:25},
    {id:'privacySetting',label:'Privacy & Setting',weight:20},
    {id:'recreationUsability',label:'Recreation & Usability',weight:15},
    {id:'locationConvenience',label:'Location & Convenience',weight:15},
    {id:'developmentCostRisk',label:'Development Cost & Risk',weight:15},
    {id:'overallPersonalFit',label:'Overall Personal Fit',weight:10}
  ];
  const STATUS_OPTIONS=['Researching','Interested','Visit Planned','Visited','Offer Submitted','Under Contract','Purchased','Rejected','Archived'];
  const LEGACY_STATUS_MAP={Saved:'Researching',Shortlisted:'Interested',Rejected:'Rejected'};
  const clampScore=value=>{if(value===''||value===null||value===undefined)return null;const number=Number(value);return Number.isFinite(number)?Math.max(0,Math.min(10,number)):null;};
  const unique=values=>[...new Set(values.filter(Boolean))];
  const confidenceFor=(facts,unknowns=0)=>facts>=4?'High':facts>=2?'Medium':facts>=1?'Low':unknowns?'Not enough information':'Not enough information';
  const scorecardEntry=value=>({score:clampScore(value?.score),notes:typeof value?.notes==='string'?value.notes:'',updatedAt:typeof value?.updatedAt==='string'?value.updatedAt:''});
  function normalizeScorecard(value){const source=value&&typeof value==='object'?value:{},ratings={};DETAILED_SCORECARD_CATEGORIES.forEach(category=>{ratings[category.id]=scorecardEntry(source.ratings?.[category.id]??source[category.id]);});return {version:1,ratings};}
  function scorecardHasValues(value){const card=normalizeScorecard(value);return DETAILED_SCORECARD_CATEGORIES.some(category=>card.ratings[category.id].score!==null||card.ratings[category.id].notes||card.ratings[category.id].updatedAt);}
  function detailedTurtleScore(record={}){const scorecard=normalizeScorecard(record.propertyIntelligence?.scorecard||record.scorecard);let total=0,ratedWeight=0,ratedCount=0;const categories=DETAILED_SCORECARD_CATEGORIES.map(category=>{const rating=scorecard.ratings[category.id],contribution=rating.score===null?0:(rating.score/10)*category.weight;if(rating.score!==null){ratedWeight+=category.weight;ratedCount+=1;}total+=contribution;return {...category,score:rating.score,notes:rating.notes,updatedAt:rating.updatedAt,contribution:Number(contribution.toFixed(2))};});return {total:Number(Math.max(0,Math.min(100,total)).toFixed(2)),percentage:Number(Math.max(0,Math.min(100,total)).toFixed(2)),ratedCount,ratedWeight,categories,scorecard};}
  const textFacts=record=>[record.notes,...(Array.isArray(record.pros)?record.pros:[]),...(Array.isArray(record.cons)?record.cons:[]),record.parcel?.notes,record.locationVerification?.source,record.propertyType,...Object.values(record.investment||{}),...Object.values(record.site||{})].filter(value=>typeof value==='string').join(' ').toLowerCase();
  const includesAny=(text,terms)=>terms.some(term=>text.includes(term));
  const developmentValue=(record,key)=>{const siteKeys={driveway:['Driveway'],homesite:['Homesite','Home Site','Pad'],utilities:['Electric','Utilities','Water','Well','Septic']};const values=[record.development?.[key],record.infrastructure?.[key],...(siteKeys[key]||[]).map(siteKey=>record.site?.[siteKey]),key==='utilities'?record.investment?.utilities:null].filter(value=>value!==undefined&&value!==null&&value!=='');return values.length?values.map(value=>String(value)).join(' ').toLowerCase():'unknown'};
  const existingStructureRecorded=record=>Boolean(Number(record.beds)||Number(record.sqft)||/existing-(livable|home|cabin|structure)|cabin|dwelling|residence|home needing renovation|barn|shop/.test(`${record.propertyType||''} ${textFacts(record)}`));
  const practicalHomesiteRecorded=(value,text)=>/home|pad|identified|prepared|build site/.test(value)||includesAny(text,['prepared pad','building pad','build site','homesite']);
  const utilityAccessRecorded=value=>/onsite|roadside|existing|fully-onsite|available/.test(value);
  const AUTO_SCORE_FACT_MAPPING={landBuildability:['acreage','saved buildability rating','driveway and building-pad facts','utilities','parcel geometry','terrain, flood, soil, septic, or perc notes'],privacySetting:['acreage','saved privacy rating','privacy, wooded, view, road, and neighbor notes'],recreationUsability:['acreage','saved recreation rating','trails, hunting, woods, water, and usability notes'],locationConvenience:['verified routed destination minutes','explicitly saved airport or shopping access ratings'],developmentCostRisk:['driveway, pad, utility, well, septic, and development estimates','terrain and access risks'],overallPersonalFit:['detailed Overall Feeling rating','visit observations and personal pros or concerns']};
  const explicitAccessRatings=record=>{const values=[];for(const [label,key] of [['Airport','Airport'],['Shopping','Shopping']]){const raw=Number(record.scores?.[key]);if(Number.isFinite(raw)&&raw>=0&&raw<=100)values.push({label,score:raw/10});}return values};
  const acreageBase=acres=>{if(!Number.isFinite(acres)||acres<=0)return null;if(acres<10)return 2.5;if(acres<20)return 5;if(acres<30)return 6.7;if(acres<=50)return 8;return 8.3;};
  const routeMinutes=(record,matcher)=>{const destinations=Array.isArray(record.destinations)?record.destinations:[];const item=destinations.find(candidate=>matcher.test(String(candidate?.name||candidate?.label||candidate?.type||'')));if(!item)return null;const value=Number(item.routeMinutes??item.durationMinutes??item.drivingMinutes??item.minutes??item.travelMinutes);return Number.isFinite(value)&&value>=0?value:null;};
  const timeScore=(minutes,type)=>{if(!Number.isFinite(minutes))return null;if(type==='airport'){if(minutes<=45)return 10;if(minutes<=60)return 8.5;if(minutes<=75)return 7;if(minutes<=90)return 4.5;return 2.5;}if(minutes<=20)return 10;if(minutes<=35)return 8;if(minutes<=50)return 6;if(minutes<=70)return 4;return 2.5;};
  function ruleLandBuildability(record){const acres=Number(record.acres),text=textFacts(record),reasons=[],warnings=[];let score=acreageBase(acres),facts=score===null?0:1;if(score===null)return {autoScore:null,confidence:'Not enough information',reasons,warnings:['Acreage and practical build-site information are not yet recorded.']};if(acres<10)warnings.push('Under the 10-acre minimum target.');else if(acres>=30&&acres<=50)reasons.push('Acreage is in the preferred 30–50 acre range.');else if(acres>50)reasons.push('Acreage exceeds the preferred range, pending usable-land verification.');const driveway=developmentValue(record,'driveway'),homesite=developmentValue(record,'homesite'),utilities=developmentValue(record,'utilities'),hasHomesite=practicalHomesiteRecorded(homesite,text);if(/existing|usable/.test(driveway)){score+=.8;facts++;reasons.push('Existing driveway is recorded.');}else if(/rough|none|washout|\$/.test(driveway)){score-=.7;facts++;warnings.push('Driveway work remains a concern.');}if(hasHomesite){score+=1;facts++;reasons.push(/pad|prepared/.test(`${homesite} ${text}`)?'Prepared building pad is recorded.':'A practical build site is recorded.');}else if(/steep/.test(homesite)){score-=1;facts++;warnings.push('No clear practical build site is recorded.');}if(utilityAccessRecorded(utilities)){score+=.7;facts++;reasons.push('Utility availability is recorded.');}else if(/extension|offgrid|tbd/.test(utilities)){score-=.7;facts++;warnings.push('Utility extension or off-grid service may be needed.');}if(existingStructureRecorded(record)){score+=.5;facts++;reasons.push('Existing structure supports immediate site use.');}if(includesAny(text,['rock','drainage','flood','steep slope','septic concern','access concern'])){score-=1;facts++;warnings.push('Known terrain, drainage, septic, or access concern needs review.');}if(!hasHomesite)warnings.push('Build-site, well, and septic details remain incomplete.');return {autoScore:clampScore(score),confidence:confidenceFor(facts,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  function rulePrivacySetting(record){const acres=Number(record.acres),text=textFacts(record),reasons=[],warnings=[];let score=acreageBase(acres),facts=score===null?0:1;if(score===null&&!includesAny(text,['privacy','rural','wood','tree','view','mountain','secluded']))return {autoScore:null,confidence:'Not enough information',reasons,warnings:['No acreage or setting observations are recorded.']};if(score===null)score=5;const positives=['privacy','secluded','rural','wood','timber','tree cover','mountain view','view'];const negatives=['neighbor','nearby homes','road noise','traffic','visible from road'];if(includesAny(text,positives)){score+=1.2;facts++;reasons.push('Property notes describe privacy, wooded cover, rural setting, or views.');}if(includesAny(text,negatives)){score-=1.3;facts++;warnings.push('Notes identify a visibility, neighbor, or road-noise concern.');}if(acres>=30)reasons.push('Acreage supports separation from nearby uses.');if(!includesAny(text,[...positives,...negatives]))warnings.push('Road visibility, nearby homes, and tree cover still need field verification.');return {autoScore:clampScore(score),confidence:confidenceFor(facts,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  function ruleRecreationUsability(record){const acres=Number(record.acres),text=textFacts(record),reasons=[],warnings=[];let score=null,facts=0;if(Number.isFinite(acres)&&acres>0){score=acres<10?3.5:acres<20?5:acres<30?6:7;facts++;reasons.push('Acreage provides a starting point for on-site recreation.');}const recreationTerms=['trail','atv','sxs','hunting','hike','shoot','woods','timber','creek','pond','water','open ground'];if(includesAny(text,recreationTerms)){score=(score??5)+1.5;facts++;reasons.push('Property notes identify recreation, trails, woods, or water potential.');}if(String(record.waterFeature||'').toLowerCase()!=='unknown'&&record.waterFeature){score=(score??5)+.7;facts++;reasons.push('A water feature is recorded.');}if(includesAny(text,['unusable','impassable','wet','flood'])){score=(score??5)-1;facts++;warnings.push('Some land may have limited recreational usability.');}if(score===null)return {autoScore:null,confidence:'Not enough information',reasons,warnings:['No acreage, recreation, or water information is recorded.']};if(facts<2)warnings.push('Trail, hunting, and usable-ground conditions need field verification.');return {autoScore:clampScore(score),confidence:confidenceFor(facts,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  function ruleLocationConvenience(record){const entries=[['Airport',/airport/i,'airport'],["Lowe's",/lowe'?s/i,'service'],['Home Depot',/home depot/i,'service'],['Costco',/costco/i,'service'],['Grocery',/grocery|walmart|supermarket/i,'service'],['Hospital',/hospital/i,'service']],known=[];entries.forEach(([label,matcher,type])=>{const minutes=routeMinutes(record,matcher);if(minutes!==null)known.push({label,minutes,score:timeScore(minutes,type),type});});const savedRatings=explicitAccessRatings(record);if(!known.length&&!savedRatings.length)return {autoScore:null,confidence:'Not enough information',reasons:[],warnings:['No verified routed travel times or explicitly saved access ratings are recorded. Straight-line distances are not used for this score.']};const scored=[...known,...savedRatings],score=scored.reduce((total,item)=>total+item.score,0)/scored.length,reasons=[],warnings=[];const airport=known.find(item=>item.type==='airport');if(airport){if(airport.minutes<=45)reasons.push(`Airport routed time is ${airport.minutes} minutes.`);else if(airport.minutes<=75)reasons.push(`Airport routed time is ${airport.minutes} minutes and remains competitive.`);else warnings.push(`Airport routed time is ${airport.minutes} minutes.`);}if(known.some(item=>item.label==="Lowe's"))reasons.push("Lowe's has a property-specific routed time.");if(savedRatings.length)reasons.push(`Uses ${savedRatings.map(item=>item.label.toLowerCase()).join(' and ')} access rating${savedRatings.length===1?'':'s'} already saved with this property.`);const missing=entries.filter(([label,matcher])=>routeMinutes(record,matcher)===null).map(([label])=>label);if(missing.length)warnings.push(`Missing routed data: ${missing.join(', ')}.`);return {autoScore:clampScore(score),confidence:confidenceFor(known.length+savedRatings.length,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  function ruleDevelopmentCostRisk(record){const text=textFacts(record),reasons=[],warnings=[];let score=null,facts=0;const driveway=developmentValue(record,'driveway'),homesite=developmentValue(record,'homesite'),utilities=developmentValue(record,'utilities'),hasHomesite=practicalHomesiteRecorded(homesite,text);if(/existing|usable/.test(driveway)){score=(score??5)+1;facts++;reasons.push('Existing driveway reduces initial access work.');}if(hasHomesite){score=(score??5)+1;facts++;reasons.push('Existing home, pad, or identified site reduces development uncertainty.');}if(utilityAccessRecorded(utilities)){score=(score??5)+.8;facts++;reasons.push('Known utility access reduces extension uncertainty.');}if(existingStructureRecorded(record)){score=(score??5)+.7;facts++;reasons.push('Existing structure may reduce immediate development needs.');}const costs=record.developmentCost&&typeof record.developmentCost==='object'?record.developmentCost:{},siteCosts=record.site&&typeof record.site==='object'?record.site:{};const knownCost=[...Object.entries(costs),...Object.entries(siteCosts)].some(([key,value])=>/total|estimate|expected|low|high|driveway|electric|well|septic/i.test(key)&&/\$|\d/.test(String(value)));if(knownCost){score=(score??5);facts++;reasons.push('Development-cost inputs are recorded.');}if(includesAny(text,['rock','drainage','flood','bridge','retaining','soil','septic concern','permit'])){score=(score??5)-1.4;facts++;warnings.push('Known site-cost or permitting risk needs review.');}if(/rough|none|extension|offgrid|steep|tbd|washout/.test(`${driveway} ${homesite} ${utilities}`)){score=(score??5)-.7;facts++;warnings.push('Access, site, or utility work may be material.');}if(score===null)return {autoScore:null,confidence:'Not enough information',reasons,warnings:['Driveway, site, utility, and development-cost information is not yet recorded.']};if(!knownCost)warnings.push('Unknown development items are not treated as zero cost.');return {autoScore:clampScore(score),confidence:confidenceFor(facts,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  function ruleOverallPersonalFit(record){const text=textFacts(record),reasons=[],warnings=[];let score=null,facts=0;const overallFeeling=clampScore(record.propertyIntelligence?.scorecard?.ratings?.overallFeeling?.score??record.scorecard?.ratings?.overallFeeling?.score);if(overallFeeling!==null){score=overallFeeling;facts++;reasons.push('Saved Overall Feeling rating is used as the personal-fit baseline.');}const visitStatus=String(record.visitStatus||'').trim(),visited=(Boolean(visitStatus)&&!/^not visited$/i.test(visitStatus))||displayStatus(record.status)==='Visited'||/drive-?by|walked|visited|site visit/.test(`${visitStatus} ${record.status||''} ${text}`);if(visited){score=score??6;facts++;reasons.push('The property has been visited or personally evaluated.');}const positives=Array.isArray(record.pros)?record.pros.filter(Boolean).length:0,negatives=Array.isArray(record.cons)?record.cons.filter(Boolean).length:0;if(positives){score=(score??5)+Math.min(1.5,positives*.4);facts++;reasons.push('Personal strengths are recorded.');}if(negatives){score=(score??5)-Math.min(1.5,negatives*.4);facts++;warnings.push('Personal concerns are recorded.');}if(includesAny(text,['love','favorite','excellent fit','great fit'])){score=(score??5)+.7;facts++;reasons.push('Notes express a positive personal fit.');}if(score===null)return {autoScore:null,confidence:'Not enough information',reasons,warnings:['Personal impression or visit notes have not been recorded.']};if(!visited)warnings.push('A site visit may materially change this personal-fit recommendation.');return {autoScore:clampScore(score),confidence:confidenceFor(facts,warnings.length),reasons:unique(reasons),warnings:unique(warnings)};}
  const RULES={landBuildability:ruleLandBuildability,privacySetting:rulePrivacySetting,recreationUsability:ruleRecreationUsability,locationConvenience:ruleLocationConvenience,developmentCostRisk:ruleDevelopmentCostRisk,overallPersonalFit:ruleOverallPersonalFit};
  const simplifiedEntry=value=>({autoScore:clampScore(value?.autoScore),manualScore:clampScore(value?.manualScore),effectiveScore:clampScore(value?.effectiveScore),confidence:['High','Medium','Low','Not enough information'].includes(value?.confidence)?value.confidence:'Not enough information',reasons:Array.isArray(value?.reasons)?value.reasons.filter(item=>typeof item==='string').slice(0,6):[],warnings:Array.isArray(value?.warnings)?value.warnings.filter(item=>typeof item==='string').slice(0,6):[],factsUsed:Array.isArray(value?.factsUsed)?value.factsUsed.filter(item=>typeof item==='string').slice(0,6):[],missingFacts:Array.isArray(value?.missingFacts)?value.missingFacts.filter(item=>typeof item==='string').slice(0,6):[],recalculatedAt:typeof value?.recalculatedAt==='string'?value.recalculatedAt:'',notes:typeof value?.notes==='string'?value.notes:'',updatedAt:typeof value?.updatedAt==='string'?value.updatedAt:'',source:value?.source==='manual'?'manual':'automatic'});
  function normalizeSimplifiedScorecard(value){const source=value&&typeof value==='object'?value:{},categories={};SIMPLIFIED_SCORECARD_CATEGORIES.forEach(category=>{categories[category.id]=simplifiedEntry(source.categories?.[category.id]??source[category.id]);});return {version:1,categories};}
  function calculateSimplifiedScorecard(record={},existing){const saved=normalizeSimplifiedScorecard(existing||record.propertyIntelligence?.simplifiedScorecard||record.simplifiedScorecard),categories={};SIMPLIFIED_SCORECARD_CATEGORIES.forEach(category=>{const automatic=RULES[category.id](JSON.parse(JSON.stringify(record||{}))),prior=saved.categories[category.id],manualScore=prior.manualScore,effectiveScore=manualScore===null?automatic.autoScore:manualScore;categories[category.id]={...prior,autoScore:automatic.autoScore,manualScore,effectiveScore,confidence:manualScore===null?automatic.confidence:'High',reasons:automatic.reasons,warnings:automatic.warnings,factsUsed:automatic.reasons,missingFacts:automatic.warnings,recalculatedAt:prior.recalculatedAt||'',source:manualScore===null?'automatic':'manual'};});return {version:1,categories};}
  function simplifiedTurtleScore(record={}){const scorecard=calculateSimplifiedScorecard(record),categories=SIMPLIFIED_SCORECARD_CATEGORIES.map(category=>{const value=scorecard.categories[category.id];return {...category,...value,score:value.effectiveScore,contribution:0};});const rated=categories.filter(category=>category.score!==null),ratedWeight=rated.reduce((sum,category)=>sum+category.weight,0),total=ratedWeight?rated.reduce((sum,category)=>sum+(category.score/10)*(category.weight/ratedWeight)*100,0):0;categories.forEach(category=>{category.contribution=category.score===null?0:Number(((category.score/10)*(ratedWeight?category.weight/ratedWeight:0)*100).toFixed(2));});const confidences=categories.map(category=>category.confidence),overallConfidence=!rated.length?'Not enough information':confidences.includes('Low')||confidences.includes('Not enough information')?'Low':confidences.includes('Medium')?'Medium':'High';return {total:Number(Math.max(0,Math.min(100,total)).toFixed(2)),percentage:Number(Math.max(0,Math.min(100,total)).toFixed(2)),ratedCount:rated.length,ratedWeight,categories,scorecard,overallConfidence,incomplete:rated.length<SIMPLIFIED_SCORECARD_CATEGORIES.length};}
  function getTurtleScore(record={}){const simplified=simplifiedTurtleScore(record),detailed=detailedTurtleScore(record);return {...simplified,detailedScorecard:detailed.scorecard,detailedScore:detailed};}
  function displayStatus(status){const value=String(status||'').trim();return STATUS_OPTIONS.includes(value)?value:(LEGACY_STATUS_MAP[value]||'Researching');}
  function statusMatches(record,status){return !status||displayStatus(record?.status)===status;}
  function airportDistance(record={}){const destinations=Array.isArray(record.destinations)?record.destinations:[],airport=destinations.find(item=>/airport/i.test(String(item?.name||item?.label||item?.type||''))),value=Number(airport?.miles??airport?.distanceMiles??airport?.distance);return Number.isFinite(value)&&value>=0?value:null;}
  function pricePerAcre(record={}){const acres=Number(record.acres),price=Number(record.price);return acres>0&&price>=0?price/acres:null;}
  function numericAscending(a,b){const aValid=Number.isFinite(a),bValid=Number.isFinite(b);if(!aValid&&!bValid)return 0;if(!aValid)return 1;if(!bValid)return -1;return a-b;}
  function sortProperties(records=[],sort='turtleScore',{favoritesFirst=false}={}){const statusIndex=value=>Math.max(0,STATUS_OPTIONS.indexOf(displayStatus(value))),valueFor=record=>{if(sort==='price')return Number(record.price)||null;if(sort==='pricePerAcre')return pricePerAcre(record);if(sort==='acreage')return Number(record.acres)||null;if(sort==='airportDistance')return airportDistance(record);if(sort==='favorite')return record.favorite?1:0;if(sort==='status')return statusIndex(record.status);return getTurtleScore(record).total;};return records.slice().sort((a,b)=>{if(favoritesFirst&&Boolean(a.favorite)!==Boolean(b.favorite))return a.favorite?-1:1;const aValue=valueFor(a),bValue=valueFor(b);if(sort==='price'||sort==='pricePerAcre'||sort==='airportDistance'||sort==='status')return numericAscending(aValue,bValue)||String(a.name||'').localeCompare(String(b.name||''));return numericAscending(bValue,aValue)||String(a.name||'').localeCompare(String(b.name||''));});}
  function filterProperties(records=[],filters={}){const minimum=value=>{const number=Number(value);return Number.isFinite(number)&&number>0?number:null;},minAcres=minimum(filters.minAcres),minTurtle=minimum(filters.minTurtleScore),minPrice=minimum(filters.minPrice),maxPrice=minimum(filters.maxPrice),maxPricePerAcre=minimum(filters.maxPricePerAcre),county=String(filters.county||'').trim().toLowerCase();return records.filter(record=>{const turtle=getTurtleScore(record).total,price=Number(record.price)||0,acres=Number(record.acres)||0,ppa=pricePerAcre(record);return (!minAcres||acres>=minAcres)&&(!minTurtle||turtle>=minTurtle)&&statusMatches(record,filters.status)&&(!filters.favorite||Boolean(record.favorite))&&(!county||String(record.parcel?.county||'').toLowerCase().includes(county))&&(!minPrice||price>=minPrice)&&(!maxPrice||price<=maxPrice)&&(!maxPricePerAcre||(ppa!==null&&ppa<=maxPricePerAcre));});}
  function strengthsAndWeaknesses(record={}){const turtle=getTurtleScore(record),strengths=[],weaknesses=[];turtle.categories.filter(category=>category.score!==null&&category.score>=7.5).sort((a,b)=>b.score-a.score).forEach(category=>strengths.push(category.label));turtle.categories.forEach(category=>{if(category.score!==null&&category.score<=4)weaknesses.push(`${category.label} needs attention`);weaknesses.push(...category.warnings.slice(0,1));});if(!turtle.ratedCount)weaknesses.push('Not enough information to calculate a Turtle Score');return {strengths:unique(strengths).slice(0,4),weaknesses:unique(weaknesses).slice(0,4)};}
  function dashboard(records=[]){const totals=records.length?records:[],rated=totals.map(getTurtleScore).filter(result=>result.ratedCount>0),average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null,propertyScores=rated.map(result=>result.total),acres=totals.map(record=>Number(record.acres)||0).filter(value=>value>0),prices=totals.map(record=>Number(record.price)||0).filter(value=>value>0),ppas=totals.map(pricePerAcre).filter(value=>value!==null),statusCounts=Object.fromEntries(STATUS_OPTIONS.map(status=>[status,0]));totals.forEach(record=>{statusCounts[displayStatus(record.status)]+=1;});return {totalProperties:totals.length,favorites:totals.filter(record=>record.favorite).length,visited:totals.filter(record=>{const status=String(record.visitStatus||'').trim();return status&&!/^not visited$/i.test(status);}).length,averageTurtleScore:average(propertyScores),highestScore:propertyScores.length?Math.max(...propertyScores):null,lowestScore:propertyScores.length?Math.min(...propertyScores):null,statusCounts,averageAcreage:average(acres),averagePrice:average(prices),averagePricePerAcre:average(ppas)};}
  function runRegressionChecks(){const base={id:'OT-001',name:'Fixture',address:'1 Test Rd',lat:35.4,lng:-84.3,acres:30,development:{driveway:'existing',homesite:'pad',utilities:'onsite'},pros:['Wooded privacy and ATV trail'],cons:[],visitStatus:'Walked',destinations:[{name:'Airport',routeMinutes:60},{name:"Lowe's",routeMinutes:30},{name:'Hospital',routeMinutes:35}],propertyIntelligence:{scorecard:{ratings:{privacy:{score:9,notes:'legacy',updatedAt:'2026-07-26'}}}}};const acreScores=[0,10,20,30,50,60].map(acres=>ruleLandBuildability({...base,acres}).autoScore),complete=getTurtleScore(base),partial=getTurtleScore({id:'OT-002',name:'Partial',address:'2 Test Rd',lat:35.4,lng:-84.3,acres:20}),manual=calculateSimplifiedScorecard(base,{categories:{landBuildability:{manualScore:9,notes:'manual'}}}),cleared=calculateSimplifiedScorecard(base,{categories:{landBuildability:{manualScore:null,notes:'keep'}}}),noData=getTurtleScore({}),unknownAirport=ruleLocationConvenience({...base,destinations:[]}),knownRisk=ruleDevelopmentCostRisk({...base,notes:'Rock and drainage concern'}),storedRoundTrip=JSON.parse(JSON.stringify({version:1,records:{'OT-001':{propertyIntelligence:base.propertyIntelligence}}})),sorted=sortProperties([base,{...base,name:'Lower',acres:5,pros:[],destinations:[]}],'turtleScore'),filtered=filterProperties([base],{minAcres:20,minTurtleScore:1});const checks={simplifiedWeightsTotal100:SIMPLIFIED_SCORECARD_CATEGORIES.reduce((sum,category)=>sum+category.weight,0)===100,underTenAcreageIsMateriallyLower:acreScores[0]<acreScores[1],acreageThresholdsIncrease:acreScores[1]<acreScores[2]&&acreScores[2]<acreScores[3]&&acreScores[3]<=acreScores[4]&&acreScores[4]<=acreScores[5],knownAirportTimeScores:ruleLocationConvenience(base).autoScore!==null,unknownAirportStaysUnknown:unknownAirport.autoScore===null&&unknownAirport.confidence==='Not enough information',knownRiskProducesWarning:knownRisk.warnings.length>0,manualOverrideWins:manual.categories.landBuildability.effectiveScore===9&&manual.categories.landBuildability.source==='manual',clearingOverrideReturnsAutomatic:cleared.categories.landBuildability.effectiveScore===cleared.categories.landBuildability.autoScore&&cleared.categories.landBuildability.notes==='keep',partialDataRenormalizes:partial.ratedCount>0&&partial.ratedWeight<100&&partial.total>0&&partial.total<=100,noScoreableDataStaysEmpty:noData.ratedCount===0&&noData.total===0,overallScoreBounded:complete.total>=0&&complete.total<=100,legacyDetailedScorecardSurvives:storedRoundTrip.records['OT-001'].propertyIntelligence.scorecard.ratings.privacy.score===9,sortingAndFilteringUseSimplified:sorted[0]===base&&filtered.length===1,lowConfidenceIdentified:getTurtleScore({...base,destinations:[]}).overallConfidence==='Low'};return {passed:Object.values(checks).every(Boolean),checks};}
  window.OTIntelligence={config:{scorecardCategories:DETAILED_SCORECARD_CATEGORIES,detailedScorecardCategories:DETAILED_SCORECARD_CATEGORIES,simplifiedScorecardCategories:SIMPLIFIED_SCORECARD_CATEGORIES,statusOptions:STATUS_OPTIONS,autoScoreFactMapping:AUTO_SCORE_FACT_MAPPING},normalizeScorecard,scorecardHasValues,normalizeSimplifiedScorecard,calculateSimplifiedScorecard,getDetailedTurtleScore:detailedTurtleScore,getTurtleScore,displayStatus,statusMatches,airportDistance,pricePerAcre,sortProperties,filterProperties,strengthsAndWeaknesses,dashboard,runRegressionChecks};
  window.OTPropertyIntelligenceRegressionChecks={run:runRegressionChecks};
})();
