/* Meaningful, evidence-gated listing change tracking. No polling or startup writes. */
(()=>{
'use strict';
const VERSION='1.0.0',DEFAULT_CADENCE_HOURS=24;
const clone=value=>value==null?value:structuredClone(value);
const now=()=>new Date().toISOString();
const finite=value=>Number.isFinite(Number(value));
const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
const unique=values=>[...new Set(values.filter(Boolean).map(clean))];
const meaningfulClaims=record=>unique([record.propertyIntelligence?.zillowLand?.sellerFinancing==='yes'&&'Seller financing',record.propertyIntelligence?.zillowLand?.nationalParkAdjacency==='yes'&&'National Park adjacency',record.propertyIntelligence?.zillowLand?.glampingPlatforms&&`${record.propertyIntelligence.zillowLand.glampingPlatforms} glamping platforms`,record.propertyIntelligence?.zillowLand?.establishedTrails==='yes'&&'Established trails',record.propertyIntelligence?.zillowLand?.priorBusinessUse==='yes'&&'Prior business use']);
function snapshotFromRecord(record={},options={}){
  const verified=options.verified||{},source=options.source||record.zillowFacts?.current?.sourceType||record.listingTextEvidence?.current?.sourceType||record.source||'Saved property';
  return {price:finite(record.price)&&Number(record.price)>0?Number(record.price):null,status:clean(record.listingStatus||record.status||''),acreage:finite(record.acres)&&Number(record.acres)>0?Number(record.acres):null,importantFacts:unique([record.beds&&`${record.beds} beds`,record.baths&&`${record.baths} baths`,record.sqft&&`${record.sqft} sq ft`,...meaningfulClaims(record)]),descriptionClaims:meaningfulClaims(record),source,sourceUrl:options.sourceUrl||record.listing||'',checkedAt:options.checkedAt||now(),verification:{price:verified.price??Boolean(record.price),status:verified.status??Boolean(record.listingStatus),acreage:verified.acreage??Boolean(record.acres),importantFacts:verified.importantFacts??true,descriptionClaims:verified.descriptionClaims??true}};
}
function observationFromResearch(result={},record={}){
  const items=result?.findings?.sources||result?.items||[],matching=items.filter(item=>window.OTPropertyResearch?.resultMatchesAddress?.(item,record.address)),text=matching.map(item=>`${item.title||''} ${item.description||''}`).join(' '),price=text.match(/\$\s*([\d,]{4,})\b/)?.[1],acres=text.match(/\b([\d.]+)\s*(?:acres?|ac)\b/i)?.[1],status=text.match(/\b(active|pending|contingent|sold|withdrawn|removed|back on market)\b/i)?.[1];
  if(!matching.length)return {success:false,checkedAt:result.retrievedAt||now(),failure:result.failure||{code:'listing-not-verified',message:'No permitted current source reasonably matched this address.'}};
  const candidate=clone(record);if(price)candidate.price=Number(price.replace(/,/g,''));if(acres)candidate.acres=Number(acres);if(status)candidate.listingStatus=status.replace(/\b\w/g,char=>char.toUpperCase());
  return {success:Boolean(price||acres||status),snapshot:snapshotFromRecord(candidate,{source:result.provider||'Public research result',sourceUrl:matching[0]?.url||'',checkedAt:result.retrievedAt||now(),verified:{price:Boolean(price),status:Boolean(status),acreage:Boolean(acres),importantFacts:false,descriptionClaims:false}}),failure:price||acres||status?null:{code:'listing-not-verified',message:'The address matched, but current price, status, and acreage were not confirmed by the permitted source.'}};
}
function delta(type,label,before,after,checkedAt){return {id:`${type}-${checkedAt}-${clean(after)}`,type,label,before,after,checkedAt,acknowledged:false}}
function compare(previous={},current={}){
  const checkedAt=current.checkedAt||now(),changes=[];
  if(current.verification?.price&&finite(previous.price)&&finite(current.price)&&Number(previous.price)!==Number(current.price)){const amount=Number(current.price)-Number(previous.price),pct=previous.price?amount/Number(previous.price)*100:0;changes.push({...delta('price',amount<0?'Price reduced':'Price increased',Number(previous.price),Number(current.price),checkedAt),amount,percent:Number(pct.toFixed(1))})}
  if(current.verification?.status&&clean(previous.status)&&clean(current.status)&&clean(previous.status).toLowerCase()!==clean(current.status).toLowerCase())changes.push(delta('status','Listing status changed',previous.status,current.status,checkedAt));
  if(current.verification?.acreage&&finite(previous.acreage)&&finite(current.acreage)&&Math.abs(Number(previous.acreage)-Number(current.acreage))>=Math.max(.25,Number(previous.acreage)*.01))changes.push(delta('acreage','Listing acreage changed',Number(previous.acreage),Number(current.acreage),checkedAt));
  if(current.verification?.importantFacts&&JSON.stringify(previous.importantFacts||[])!==JSON.stringify(current.importantFacts||[]))changes.push(delta('facts','Important listing facts changed',previous.importantFacts||[],current.importantFacts||[],checkedAt));
  if(current.verification?.descriptionClaims&&JSON.stringify(previous.descriptionClaims||[])!==JSON.stringify(current.descriptionClaims||[]))changes.push(delta('description','Meaningful description claims changed',previous.descriptionClaims||[],current.descriptionClaims||[],checkedAt));
  return changes;
}
function applyObservation(record={},observation={},options={}){
  const next=clone(record),monitor={cadenceHours:DEFAULT_CADENCE_HOURS,history:[],unacknowledgedCount:0,...(next.listingMonitoring||{})},checkedAt=observation.snapshot?.checkedAt||observation.checkedAt||now();
  monitor.lastAttemptAt=checkedAt;
  if(!observation.success||!observation.snapshot){monitor.lastCheckStatus='incomplete';monitor.lastFailure=observation.failure||{code:'listing-not-verified',message:'Listing status not verified this check.'};next.listingMonitoring=monitor;return {property:next,changes:[],status:'incomplete'}}
  const previous=monitor.current||snapshotFromRecord(next,{checkedAt:monitor.baselineAt||checkedAt}),changes=monitor.current?compare(previous,observation.snapshot):[];
  monitor.baseline=monitor.baseline||previous;monitor.baselineAt=monitor.baselineAt||previous.checkedAt;monitor.current=observation.snapshot;monitor.lastSuccessfulAt=checkedAt;monitor.lastCheckStatus='complete';monitor.lastFailure=null;
  const existingIds=new Set((monitor.history||[]).map(item=>item.id));monitor.history=[...(monitor.history||[]),...changes.filter(item=>!existingIds.has(item.id))].slice(-40);monitor.unacknowledgedCount=monitor.history.filter(item=>!item.acknowledged).length;next.listingMonitoring=monitor;
  return {property:next,changes,status:changes.length?'changed':'verified-no-change'};
}
function establishBaseline(record={}){return applyObservation(record,{success:true,snapshot:snapshotFromRecord(record,{checkedAt:record.importedAt||now()})}).property}
function acknowledge(record={}){const next=clone(record),monitor={...(next.listingMonitoring||{})};monitor.history=(monitor.history||[]).map(item=>({...item,acknowledged:true}));monitor.unacknowledgedCount=0;monitor.acknowledgedAt=now();next.listingMonitoring=monitor;return next}
function isStale(record={},at=Date.now()){const checked=Date.parse(record.listingMonitoring?.lastAttemptAt||record.listingMonitoring?.lastSuccessfulAt||0),hours=Number(record.listingMonitoring?.cadenceHours)||DEFAULT_CADENCE_HOURS;return !checked||at-checked>=hours*3600000}
function formatChange(change={}){if(change.type==='price'){const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);return `${change.label}: ${money(change.before)} → ${money(change.after)} (${change.amount<0?'−':'+'}${money(Math.abs(change.amount))} / ${change.percent>0?'+':''}${change.percent}%)`}if(change.type==='status')return `Listing status: ${change.before} → ${change.after}`;if(change.type==='acreage')return `Acreage: ${change.before} → ${change.after}`;return change.label||'Listing facts changed'}
function runRegressionChecks(){
  const base={id:'happy',price:895000,acres:45.76,listingStatus:'Active',source:'Listing text',importedAt:'2026-08-01T00:00:00.000Z'};
  const established=establishBaseline(base),changed=applyObservation(established,{success:true,snapshot:snapshotFromRecord({...base,price:799000,listingStatus:'Pending'},{checkedAt:'2026-08-14T00:00:00.000Z',source:'Fixture current listing',verified:{price:true,status:true,acreage:true}})}),factSnapshot={...changed.property.listingMonitoring.current,checkedAt:'2026-08-15T00:00:00.000Z',importantFacts:[...changed.property.listingMonitoring.current.importantFacts,'Seller financing'],descriptionClaims:['Seller financing'],verification:{price:false,status:false,acreage:false,importantFacts:true,descriptionClaims:true}},factChanged=applyObservation(changed.property,{success:true,snapshot:factSnapshot}),unverified=applyObservation(changed.property,{success:false,checkedAt:'2026-08-15T00:00:00.000Z',failure:{code:'blocked',message:'Listing status not verified this check.'}}),acked=acknowledge(changed.property),repeat=applyObservation(changed.property,{success:true,snapshot:changed.property.listingMonitoring.current}),checks={baselineHasNoFalseChange:established.listingMonitoring.history.length===0,priceAndStatusDetected:changed.changes.some(item=>item.type==='price'&&item.amount===-96000)&&changed.changes.some(item=>item.type==='status'),factsAndDescriptionDetected:factChanged.changes.some(item=>item.type==='facts')&&factChanged.changes.some(item=>item.type==='description'),meaningfulDeltaStored:changed.property.listingMonitoring.unacknowledgedCount===2,unverifiedIsNotNoChange:unverified.status==='incomplete'&&unverified.property.listingMonitoring.lastFailure.message.includes('not verified'),acknowledgementPersists:acked.listingMonitoring.unacknowledgedCount===0&&acked.listingMonitoring.history.every(item=>item.acknowledged),repeatIsIdempotent:repeat.changes.length===0,cadenceIsBounded:!isStale(changed.property,Date.parse('2026-08-14T23:00:00.000Z'))&&isStale(changed.property,Date.parse('2026-08-15T01:00:00.000Z'))};
  return {passed:Object.values(checks).every(Boolean),checks};
}
window.OTListingMonitor={VERSION,DEFAULT_CADENCE_HOURS,snapshotFromRecord,observationFromResearch,compare,applyObservation,establishBaseline,acknowledge,isStale,formatChange,runRegressionChecks};
})();
