(()=>{
'use strict';
const $=id=>document.getElementById(id);
const MAP=()=>window.OT_MAP;
const FEATURE_NAMES={'driveway-entrance':'Driveway entrance','driveway-route':'Driveway route','build-site':'Build-site area','existing-home':'Existing home','barn-shop':'Barn / shop','well':'Well','septic':'Septic area','utility-connection':'Utility connection','utility-route':'Utility route','electric-route':'Electric route','water-route':'Water route','propane-route':'Propane route','internet-route':'Internet / fiber route','gate':'Gate','creek':'Creek / crossing','problem-area':'Problem area','clearing-area':'Clearing area','viewpoint':'Viewpoint'};
const LINE_TYPES=new Set(['driveway-route','utility-route','electric-route','water-route','propane-route','internet-route','creek']);
const POLYGON_TYPES=new Set(['build-site','septic','problem-area','clearing-area']);
const DRIVEWAY_COST_CONFIG=Object.freeze({
  clearingPerFoot:[3,6,10],gradingPerFoot:{flat:[12,19,30],rolling:[18,29,46],steep:[32,52,82],hillside:[55,88,140]},baseStonePerFoot:[13,20,31],finishPerFoot:{gravel:[4,7,11],'road-base':[0,2,4],paved:[18,28,42]},rockPerFoot:[18,42,85],drainagePerFoot:[4,8,14],culvertEach:[900,1800,3600],retainingPerFoot:[75,165,340],switchbackEach:[3500,8500,21000],creekCrossing:[14000,42000,125000],mobilization:[2500,5000,9000],contingency:{flat:.12,rolling:.16,steep:.22,hillside:.28}
});
const BUILD_SITE_COST_CONFIG=Object.freeze({clearingPerSqFt:[.35,.7,1.2],padPerSqFt:{light:[3,6,10],moderate:[7,13,22],heavy:[14,27,48]},drainage:{simple:[1200,3000,6000],moderate:[3500,8000,16000],complex:[9000,22000,50000]},rock:[8000,24000,70000],retaining:[12000,35000,95000],access:[5000,15000,40000],mobilization:[3500,6500,11000],contingency:.18});
const UTILITY_COST_CONFIG=Object.freeze({'underground-electric':[18,34,65],'overhead-electric':[10,18,34],'public-water':[22,42,85],'well-supply':[8,16,32],propane:[7,14,26],internet:[6,13,28],'septic-connection':[12,24,50],terrain:{flat:1,rolling:1.3,steep:1.85},rock:[7,20,52],crossing:[2500,8500,30000],mobilization:[1200,3000,7000]});
 let activePropertyId='',planning=null,selectedFeatureId='',drawing=null,workingLayer=null,planningGroup=null,vertexGroup=null,pendingPlanSaveTimer=null,pendingPlanSaveLabel='',drawingMapDoubleClickWasEnabled=false,vertexDragMapWasEnabled=false,lastDrawingClick=null;
 const PLANNING_HISTORY_LIMIT=40,planningHistories=new Map();
const clone=value=>value==null?value:structuredClone(value);
const now=()=>new Date().toISOString();
const round=value=>Math.round(Number(value)||0);
const num=value=>Number(value)||0;
const safe=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function point(lat,lng){return {lat:Number(lat),lng:Number(lng)}}
function validPoint(value){return value&&Number.isFinite(Number(value.lat))&&Number.isFinite(Number(value.lng))}
function geometryFor(type){return POLYGON_TYPES.has(type)?'Polygon':LINE_TYPES.has(type)?'LineString':'Point'}
function defaultPlan(){return {schemaVersion:3,features:[],drivewayAnalyses:{},buildSiteAnalyses:{},elevationProfiles:{},manualElevationOverrides:{},preferredDrivewayRouteId:'',concepts:[],activeConceptId:'',checklist:[],createdAt:now(),updatedAt:now()}}
function normalizeFeature(feature,index=0){const type=FEATURE_NAMES[feature?.type]?feature.type:'problem-area',geometry=geometryFor(type),coords=Array.isArray(feature?.geometry?.coordinates)?feature.geometry.coordinates.filter(validPoint).map(item=>point(item.lat,item.lng)):[];return {...feature,id:String(feature?.id||`spf-${Date.now()}-${index}`),type,geometry:{...feature?.geometry,type:feature?.geometry?.type||geometry,coordinates:coords},label:String(feature?.label||FEATURE_NAMES[type]),notes:String(feature?.notes||''),relationships:Array.isArray(feature?.relationships)?feature.relationships.map(String):[],inputSource:String(feature?.inputSource||'user-entered'),confidence:String(feature?.confidence||'user-estimated'),createdAt:String(feature?.createdAt||now()),updatedAt:String(feature?.updatedAt||now())}}
function normalizePlan(value){const source=value&&typeof value==='object'?value:{};return {...source,schemaVersion:Number(source.schemaVersion)||1,features:Array.isArray(source.features)?source.features.map(normalizeFeature):[],drivewayAnalyses:source.drivewayAnalyses&&typeof source.drivewayAnalyses==='object'?clone(source.drivewayAnalyses):{},buildSiteAnalyses:source.buildSiteAnalyses&&typeof source.buildSiteAnalyses==='object'?clone(source.buildSiteAnalyses):{},elevationProfiles:source.elevationProfiles&&typeof source.elevationProfiles==='object'?clone(source.elevationProfiles):{},manualElevationOverrides:source.manualElevationOverrides&&typeof source.manualElevationOverrides==='object'?clone(source.manualElevationOverrides):{},preferredDrivewayRouteId:String(source.preferredDrivewayRouteId||''),concepts:Array.isArray(source.concepts)?clone(source.concepts):[],activeConceptId:String(source.activeConceptId||''),checklist:Array.isArray(source.checklist)?clone(source.checklist):[],createdAt:String(source.createdAt||now()),updatedAt:String(source.updatedAt||now())}}
function candidateSquare(sample,radiusFeet=55){const latDelta=radiusFeet/364000,lngDelta=radiusFeet/(364000*Math.cos(Number(sample.lat)*Math.PI/180)||1);return [{lat:sample.lat-latDelta,lng:sample.lng-lngDelta},{lat:sample.lat-latDelta,lng:sample.lng+lngDelta},{lat:sample.lat+latDelta,lng:sample.lng+lngDelta},{lat:sample.lat+latDelta,lng:sample.lng-lngDelta}]}
function parcelBoundaryPoints(record={}){const geometry=record.parcelGeometry,polygons=geometry?.type==='Polygon'?[geometry.coordinates]:geometry?.type==='MultiPolygon'?geometry.coordinates:[];return polygons.flatMap(polygon=>(polygon?.[0]||[]).map(pair=>({lat:Number(pair?.[1]),lng:Number(pair?.[0])})).filter(validPoint))}
function nearestBoundaryPoint(record={},origin={}){return parcelBoundaryPoints(record).sort((a,b)=>Math.hypot(a.lat-origin.lat,a.lng-origin.lng)-Math.hypot(b.lat-origin.lat,b.lng-origin.lng))[0]||null}
function generateParcelCandidates(record={},screen={}){
 const next=clone(record),plan=normalizePlan(next.sitePlanning),fingerprint=String(screen.geometryFingerprint||'');
 if(!screen.success||!fingerprint||!['verified-parcel-polygon','user-adjusted-parcel'].includes(screen.parcelCertainty))return {property:next,created:[],reason:'verified-parcel-terrain-required'};
 if(plan.terrainScreening?.geometryFingerprint===fingerprint&&plan.terrainScreening?.retrievedAt===screen.retrievedAt)return {property:next,created:[],reused:true};
 const prior=plan.features.filter(feature=>feature.inputSource!=='automated-terrain-screen'),created=[],make=(kind,type,label,coordinates,notes)=>normalizeFeature({id:`auto-${kind}-${fingerprint.replace(/[^a-z0-9-]/gi,'').slice(-18)}`,type,label,geometry:{type:geometryFor(type),coordinates},notes,inputSource:'automated-terrain-screen',confidence:'preliminary-provider-derived',candidateStatus:'suggested',automationFingerprint:fingerprint,createdAt:screen.retrievedAt,updatedAt:screen.retrievedAt});
 const home={lat:Number(next.lat),lng:Number(next.lng)},homeInside=validPoint(home)&&window.OTParcelIntelligence?.pointInGeometry?.(home,next.parcelGeometry);
 if(homeInside){const feature=make('existing-home','existing-home','Existing Home Zone',[home],'Address/home point falls inside the verified parcel. Confirm the exact structure footprint before relying on this zone.');prior.push(feature);created.push(feature)}
 const zones=(screen.candidateZones||[]).slice(0,2);(zones.length?zones:(screen.candidateSamples||[]).slice(0,2).map((sample,index)=>({label:`Candidate Build Zone ${String.fromCharCode(65+index)}`,center:sample,averageSlopePct:sample.slopePct,approximateScreenedAcres:null}))).forEach((zone,index)=>{const radius=zone.approximateScreenedAcres?Math.max(55,Math.min(145,Math.sqrt(zone.approximateScreenedAcres*43560/Math.PI))):65,feature=make(`build-${index+1}`,'build-site',`Candidate Build Zone ${String.fromCharCode(65+index)}`,candidateSquare(zone.center,radius),`Parcel-wide terrain samples average ${zone.averageSlopePct}% slope in this contiguous candidate area. Verify soils, septic, drainage, setbacks, access, and actual usable footprint.`);prior.push(feature);created.push(feature)});
 (screen.steepSamples||[]).slice(0,1).forEach(sample=>{const feature=make('steep','problem-area','Steep/Challenging Area',candidateSquare(sample,70),`Sampled local slope ${sample.slopePct}%. Preliminary terrain caution only.`);prior.push(feature);created.push(feature)});
 (screen.drainageCandidates||[]).slice(0,1).forEach(sample=>{const feature=make('drainage','problem-area','Creek/Drainage Area',candidateSquare(sample,65),'Low relative elevation sample. Verify creek, drainage, flood, and wet-soil conditions before planning.');prior.push(feature);created.push(feature)});
 const layout=next.parcelIntelligence?.subdivisionLayout,boundary=homeInside&&['Promising','Possible'].includes(layout?.classification)?nearestBoundaryPoint(next,home):null;if(boundary){const feature=make('independent-access','driveway-route','Possible Independent Access',[home,boundary],'Physical layout suggestion only. Confirm road frontage, legal access, grade, stream crossings, and driveway approval.');prior.push(feature);created.push(feature)}
 plan.features=prior;plan.terrainScreening=clone(screen);plan.developmentFeasibility={physicalCandidate:zones.length?'candidate-zones-detected':'no-zone-detected',legalFeasibility:'unknown',septicFeasibility:'unknown',utilityFeasibility:'unknown',note:'A terrain candidate is not confirmation of a legal, septic-feasible, or utility-feasible second-home site.'};plan.automatedCandidateFingerprint=fingerprint;plan.automatedCandidateStatus='suggested';plan.updatedAt=now();next.sitePlanning=plan;next.updatedAt=now();return {property:next,created,reused:false};
}
function activeConcept(){return planning?.concepts?.find(item=>item.id===planning.activeConceptId)||planning?.concepts?.[0]||null}
function syncConcept(){const concept=activeConcept();if(!concept)return;planning.activeConceptId=concept.id;concept.features=Array.isArray(concept.features)?concept.features.map(normalizeFeature):[];concept.drivewayAnalyses=concept.drivewayAnalyses||{};concept.buildSiteAnalyses=concept.buildSiteAnalyses||{};concept.utilityAnalyses=concept.utilityAnalyses||{};concept.elevationProfiles=concept.elevationProfiles||{};concept.manualElevationOverrides=concept.manualElevationOverrides||{};concept.preferredDrivewayRouteId=String(concept.preferredDrivewayRouteId||'');concept.relationships=concept.relationships||{};planning.features=concept.features;planning.drivewayAnalyses=concept.drivewayAnalyses;planning.buildSiteAnalyses=concept.buildSiteAnalyses;planning.utilityAnalyses=concept.utilityAnalyses;planning.elevationProfiles=concept.elevationProfiles;planning.manualElevationOverrides=concept.manualElevationOverrides;planning.preferredDrivewayRouteId=concept.preferredDrivewayRouteId}
function ensureConcepts(){if(!planning)return false;if(!planning.concepts.length){const concept={id:'concept-a',name:'Concept A',archived:false,preferred:true,notes:'Migrated from the original site plan.',features:planning.features||[],drivewayAnalyses:planning.drivewayAnalyses||{},buildSiteAnalyses:planning.buildSiteAnalyses||{},utilityAnalyses:planning.utilityAnalyses||{},elevationProfiles:planning.elevationProfiles||{},manualElevationOverrides:planning.manualElevationOverrides||{},preferredDrivewayRouteId:planning.preferredDrivewayRouteId||'',relationships:{},createdAt:now(),updatedAt:now()};planning.concepts=[concept];planning.activeConceptId=concept.id;planning.schemaVersion=Math.max(3,Number(planning.schemaVersion)||1);syncConcept();return true}syncConcept();return false}
function renderConcepts(){const select=$('planningConceptSelect');if(!select||!planning)return;select.innerHTML=planning.concepts.map(concept=>`<option value="${concept.id}">${safe(concept.name)}${concept.preferred?' ★':''}${concept.archived?' (archived)':''}</option>`).join('');select.value=planning.activeConceptId;const comparison=$('planningConceptComparison');if(comparison)comparison.textContent=planning.concepts.map(concept=>`${concept.name}: ${concept.features?.length||0} features`).join(' · ')}
 function switchConcept(id){if(!planning.concepts.some(concept=>concept.id===id))return;flushPlanSave();planning.activeConceptId=id;selectedFeatureId='';syncConcept();window.OTDiagnostics?.setContext?.({concept:activeConcept()?.name||id});renderFeatures();renderConcepts();savePlan('Changed active site-plan concept')}
function conceptAction(kind){const current=activeConcept();if(!current)return;if(kind==='create'){const name=prompt('Name this site-plan concept:','New Concept');if(!name)return;planning.concepts.push({id:`concept-${Date.now()}`,name:name.trim(),archived:false,preferred:false,notes:'',features:[],drivewayAnalyses:{},buildSiteAnalyses:{},utilityAnalyses:{},elevationProfiles:{},manualElevationOverrides:{},preferredDrivewayRouteId:'',relationships:{},createdAt:now(),updatedAt:now()});planning.activeConceptId=planning.concepts.at(-1).id}else if(kind==='duplicate'){const name=prompt('Name the duplicate concept:',`${current.name} copy`);if(!name)return;const duplicate=clone(current);duplicate.id=`concept-${Date.now()}`;duplicate.name=name.trim();duplicate.preferred=false;duplicate.createdAt=now();planning.concepts.push(duplicate);planning.activeConceptId=duplicate.id}else if(kind==='rename'){const name=prompt('Rename concept:',current.name);if(!name)return;current.name=name.trim()}else if(kind==='archive'){if(!confirm(`Archive ${current.name}? Its drawings and estimates remain recoverable.`))return;current.archived=true;current.preferred=false;const next=planning.concepts.find(concept=>!concept.archived&&concept.id!==current.id)||current;planning.activeConceptId=next.id}syncConcept();savePlan(`${kind} site-plan concept`);renderFeatures();renderConcepts()}
function activeProperty(){return window.OTPropertyStore?.getProperty?.(activePropertyId)||null}
function selectedFeature(){return planning?.features.find(feature=>feature.id===selectedFeatureId)||null}
function haversineFeet(a,b){const radius=3958.8,toRad=value=>value*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),h=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return 2*radius*Math.asin(Math.sqrt(h))*5280}
function lineFeet(coords=[]){return coords.slice(1).reduce((total,item,index)=>total+haversineFeet(coords[index],item),0)}
function polygonAcres(coords=[]){if(coords.length<3)return 0;const lat0=coords.reduce((total,item)=>total+item.lat,0)/coords.length*Math.PI/180,xy=coords.map(item=>({x:item.lng*111320*Math.cos(lat0),y:item.lat*110540}));let area=0;for(let i=0,j=xy.length-1;i<xy.length;j=i++)area+=xy[j].x*xy[i].y-xy[i].x*xy[j].y;return Math.abs(area/2)/4046.8564224}
function triplet(...items){return [items.reduce((total,item)=>total+item[0],0),items.reduce((total,item)=>total+item[1],0),items.reduce((total,item)=>total+item[2],0)]}
function money(value){return Math.round(value).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}
function estimateDriveway(input={}){const length=Math.max(0,num(input.lengthFeet)),terrain=['flat','rolling','steep','hillside'].includes(input.terrainClass)?input.terrainClass:'rolling',width=Math.max(8,num(input.clearingWidth)||16),finish=['gravel','road-base','paved'].includes(input.surface)?input.surface:'gravel',scale=width/16,components=[];const add=(name,range,enabled=true)=>{if(enabled)components.push({name,range})};
 add('Clearing',DRIVEWAY_COST_CONFIG.clearingPerFoot.map(value=>value*length*scale));
 add('Grading / cut and fill',DRIVEWAY_COST_CONFIG.gradingPerFoot[terrain].map(value=>value*length));
 add('Geotextile and base stone',DRIVEWAY_COST_CONFIG.baseStonePerFoot.map(value=>value*length));
 add('Finish surface',DRIVEWAY_COST_CONFIG.finishPerFoot[finish].map(value=>value*length));
 add('Rock excavation allowance',DRIVEWAY_COST_CONFIG.rockPerFoot.map(value=>value*length),!!input.rockRisk);
 add('Drainage ditches',DRIVEWAY_COST_CONFIG.drainagePerFoot.map(value=>value*length),!!input.drainage);
 add('Culverts',DRIVEWAY_COST_CONFIG.culvertEach.map(value=>value*Math.max(0,num(input.culverts))),num(input.culverts)>0);
 add('Retaining walls',DRIVEWAY_COST_CONFIG.retainingPerFoot.map(value=>value*Math.max(0,num(input.retainingFeet))),num(input.retainingFeet)>0);
 add('Switchbacks',DRIVEWAY_COST_CONFIG.switchbackEach.map(value=>value*Math.max(0,num(input.switchbacks))),num(input.switchbacks)>0);
 add('Creek crossing',DRIVEWAY_COST_CONFIG.creekCrossing,!!input.creekCrossing);
 add('Mobilization',DRIVEWAY_COST_CONFIG.mobilization,length>0);
 const measured=input.elevationProfile?.success&&!input.elevationProfile?.stale?input.elevationProfile:null,adjustments=measured&&window.OTElevation?.costAdjustments?window.OTElevation.costAdjustments(measured):{basis:'Manual terrain',components:[]};adjustments.components.forEach(component=>add(component.name,component.range));
 const subtotal=triplet(...components.map(component=>component.range)),contingency=DRIVEWAY_COST_CONFIG.contingency[terrain],total=subtotal.map(value=>round(value*(1+contingency))),drivers=components.slice().sort((a,b)=>b.range[1]-a.range[1]).slice(0,4).map(component=>component.name),estimateBasis=measured?(input.manualElevationOverride?.enabled?'Mixed inputs':'Measured elevation'):'Manual terrain';
 const classification=terrain==='flat'?'Simple':terrain==='rolling'?'Moderate':terrain==='steep'?'Difficult':'Major hillside construction';
 return {lengthFeet:round(length),terrainClass:terrain,classification,low:total[0],expected:total[1],high:total[2],subtotal,contingencyPct:round(contingency*100),drivers,costAdjustments:adjustments.components,estimateBasis,elevationProfileStatus:measured?'measured':input.elevationProfile?.failure?'unavailable':'not-requested',calculatedAt:now(),assumptions:measured?'Preliminary provider-derived elevations refine grade, drainage, cut-and-fill, and switchback allowances. This is not an engineering design or construction quote.':'User-entered route geometry and manual terrain inputs; no automated elevation profile, parcel, utility, or contractor quote is connected.'}
}
function estimateBuildSite(input={}){const footprint=Math.max(0,num(input.padFootprint)||1800),clearing=Math.max(0,Math.min(100,num(input.clearingPct)||35))/100,cut=['light','moderate','heavy'].includes(input.cutFill)?input.cutFill:'moderate',drain=['simple','moderate','complex'].includes(input.drainage)?input.drainage:'moderate',area=footprint*Math.max(1.5,clearing*4),components=[{name:'Clearing',range:BUILD_SITE_COST_CONFIG.clearingPerSqFt.map(value=>value*area)},{name:'Pad and cut/fill',range:BUILD_SITE_COST_CONFIG.padPerSqFt[cut].map(value=>value*footprint)},{name:'Drainage',range:BUILD_SITE_COST_CONFIG.drainage[drain]},{name:'Mobilization',range:BUILD_SITE_COST_CONFIG.mobilization}];if(input.rock)components.push({name:'Rock excavation',range:BUILD_SITE_COST_CONFIG.rock});if(input.retaining)components.push({name:'Retaining',range:BUILD_SITE_COST_CONFIG.retaining});if(input.accessHard)components.push({name:'Construction access',range:BUILD_SITE_COST_CONFIG.access});const subtotal=triplet(...components.map(item=>item.range)),total=subtotal.map(value=>round(value*(1+BUILD_SITE_COST_CONFIG.contingency)));return {low:total[0],expected:total[1],high:total[2],drivers:components.sort((a,b)=>b.range[1]-a.range[1]).slice(0,3).map(item=>item.name),calculatedAt:now(),missing:['Surveyed buildable area','Foundation/geotechnical review','Contractor grading quote']}}
function estimateUtility(input={}){const length=Math.max(0,num(input.lengthFeet)),type=UTILITY_COST_CONFIG[input.type]?input.type:'underground-electric',factor=UTILITY_COST_CONFIG.terrain[input.terrain]||1,components=[{name:'On-property route',range:UTILITY_COST_CONFIG[type].map(value=>value*length*factor)},{name:'Mobilization',range:UTILITY_COST_CONFIG.mobilization}];if(input.rock)components.push({name:'Rock / difficult trenching',range:UTILITY_COST_CONFIG.rock.map(value=>value*length)});if(input.crossing)components.push({name:'Road or creek crossing',range:UTILITY_COST_CONFIG.crossing});const subtotal=triplet(...components.map(item=>item.range));return {low:round(subtotal[0]),expected:round(subtotal[1]),high:round(subtotal[2]),drivers:components.sort((a,b)=>b.range[1]-a.range[1]).slice(0,3).map(item=>item.name),providerCharges:'Unknown provider charges are excluded—not treated as $0.',calculatedAt:now()}}
 function status(text){const target=$('sitePlanningStatus');if(target)target.textContent=text}
 function historyScope(){return activePropertyId&&planning?.activeConceptId?`${activePropertyId}::${planning.activeConceptId}`:''}
 function conceptSnapshot(){const concept=activeConcept();if(!concept)return null;return clone({features:concept.features||[],drivewayAnalyses:concept.drivewayAnalyses||{},buildSiteAnalyses:concept.buildSiteAnalyses||{},utilityAnalyses:concept.utilityAnalyses||{},elevationProfiles:concept.elevationProfiles||{},manualElevationOverrides:concept.manualElevationOverrides||{},preferredDrivewayRouteId:concept.preferredDrivewayRouteId||'',relationships:concept.relationships||{}})}
 function historyForScope(){const key=historyScope();if(!key)return null;if(!planningHistories.has(key))planningHistories.set(key,{undo:[],redo:[]});return planningHistories.get(key)}
 function updateHistoryControls(){const history=historyForScope(),undoButton=$('planningUndoEditBtn'),redoButton=$('planningRedoEditBtn');if(undoButton)undoButton.disabled=!(history?.undo?.length);if(redoButton)redoButton.disabled=!(history?.redo?.length)}
 function recordPlanningHistory(label){const history=historyForScope(),state=conceptSnapshot();if(!history||!state)return;history.undo.push({label,state});if(history.undo.length>PLANNING_HISTORY_LIMIT)history.undo.shift();history.redo=[];updateHistoryControls()}
 function restoreConceptSnapshot(snapshot){const concept=activeConcept();if(!concept||!snapshot)return false;Object.assign(concept,clone(snapshot));syncConcept();selectedFeatureId='';clearVertices();renderFeatures();return true}
 function undoPlanningEdit(){const history=historyForScope();if(!history?.undo?.length){status('No earlier edit is available for this concept.');return false}flushPlanSave();const prior=history.undo.pop(),current=conceptSnapshot();if(current)history.redo.push({label:prior.label,state:current});if(!restoreConceptSnapshot(prior.state))return false;savePlan(`Undid ${prior.label}`,{immediate:true});status(`Undid ${prior.label}.`);updateHistoryControls();return true}
 function redoPlanningEdit(){const history=historyForScope();if(!history?.redo?.length){status('No later edit is available for this concept.');return false}flushPlanSave();const next=history.redo.pop(),current=conceptSnapshot();if(current)history.undo.push({label:next.label,state:current});if(!restoreConceptSnapshot(next.state))return false;savePlan(`Redid ${next.label}`,{immediate:true});status(`Redid ${next.label}.`);updateHistoryControls();return true}
 function setSaveStatus(label,state='saved'){const target=$('sitePlanningSaveState');if(target){target.textContent=label;target.dataset.state=state}}
 function flushPlanSave(){if(pendingPlanSaveTimer){clearTimeout(pendingPlanSaveTimer);pendingPlanSaveTimer=null}if(!pendingPlanSaveLabel||!planning||!activePropertyId)return false;const label=pendingPlanSaveLabel;pendingPlanSaveLabel='';const saved=window.OTPropertyStore?.writeSitePlanning?.(activePropertyId,planning,label)||false;setSaveStatus(saved?'Saved.':'Save failed — planning changes were not committed.',saved?'saved':'failed');return saved}
 function savePlan(label,options={}){if(!planning||!activePropertyId)return false;planning.updatedAt=now();pendingPlanSaveLabel=label;setSaveStatus('Saving…','saving');if(options.immediate)return flushPlanSave();if(pendingPlanSaveTimer)clearTimeout(pendingPlanSaveTimer);pendingPlanSaveTimer=setTimeout(flushPlanSave,450);return true}
function typeColor(type){return type==='driveway-route'?'#b6672c':type==='build-site'?'#24725d':type==='utility-route'?'#426d9a':type==='problem-area'?'#b44747':'#6c4b8b'}
function clearWorking(){if(workingLayer){MAP()?.removeLayer(workingLayer);workingLayer=null}}
 function clearVertices(){if(vertexDragMapWasEnabled){MAP()?.dragging?.enable();vertexDragMapWasEnabled=false}if(vertexGroup){vertexGroup.clearLayers();MAP()?.removeLayer(vertexGroup);vertexGroup=null}}
function createLayer(feature){const map=MAP(),coords=feature.geometry.coordinates;if(!map||!coords.length)return null;let layer;if(feature.geometry.type==='Point')layer=L.marker([coords[0].lat,coords[0].lng],{title:feature.label});else if(feature.geometry.type==='LineString')layer=L.polyline(coords.map(item=>[item.lat,item.lng]),{color:typeColor(feature.type),weight:5,opacity:.9});else layer=L.polygon(coords.map(item=>[item.lat,item.lng]),{color:typeColor(feature.type),weight:3,fillOpacity:.18});layer.bindTooltip(`${FEATURE_NAMES[feature.type]} · ${feature.label}`,{sticky:true});layer.on('click',()=>selectFeature(feature.id));return layer}
function renderFeatures(){if(!planningGroup){planningGroup=L.featureGroup().addTo(MAP())}planningGroup.clearLayers();if(!planning)return;planning.features.forEach(feature=>{const layer=createLayer(feature);if(layer)layer.addTo(planningGroup)});renderTerrainControls();renderTerrainPreferredRoutes();renderUtilityControls();renderTerrainReadouts();renderTerrainCostAdjustments();renderCombined();updateToolbar()}
function setField(id,value){const input=$(id);if(input)input.value=value??''}
function featureMeasure(feature){if(!feature)return '';if(feature.geometry.type==='LineString')return `${round(lineFeet(feature.geometry.coordinates)).toLocaleString()} ft`;if(feature.geometry.type==='Polygon')return `${polygonAcres(feature.geometry.coordinates).toFixed(2)} ac`;return `${feature.geometry.coordinates[0]?.lat.toFixed(6)||'—'}, ${feature.geometry.coordinates[0]?.lng.toFixed(6)||'—'}`}
function renderFeatureControls(){const list=$('planningFeatureList'),routes=$('planningDrivewayFeature'),sites=$('planningBuildSiteFeature');if(!planning||!list||!routes||!sites)return;const previousRoute=routes.value,previousSite=sites.value;list.innerHTML=planning.features.length?planning.features.map(feature=>`<button type="button" class="planning-feature ${feature.id===selectedFeatureId?'selected':''}" data-site-feature="${safe(feature.id)}"><b>${safe(FEATURE_NAMES[feature.type])}</b><span>${safe(feature.label)} · ${featureMeasure(feature)}</span></button>`).join(''):'<div class="small">No planning features saved for this property.</div>';list.querySelectorAll('[data-site-feature]').forEach(button=>button.addEventListener('click',()=>selectFeature(button.dataset.siteFeature)));const optionHTML=(filter,empty)=>`<option value="">${empty}</option>${planning.features.filter(filter).map(feature=>`<option value="${safe(feature.id)}">${safe(feature.label)} · ${featureMeasure(feature)}</option>`).join('')}`;routes.innerHTML=optionHTML(feature=>feature.type==='driveway-route','Select a driveway route');sites.innerHTML=optionHTML(feature=>feature.type==='build-site','Select a build-site area');routes.value=planning.drivewayAnalyses[previousRoute]?previousRoute:planning.features.find(feature=>feature.type==='driveway-route')?.id||'';sites.value=planning.buildSiteAnalyses[previousSite]?previousSite:planning.features.find(feature=>feature.type==='build-site')?.id||'';if(selectedFeature()){setField('planningFeatureLabel',selectedFeature().label);setField('planningFeatureNotes',selectedFeature().notes)}}
function renderReadouts(){const routeId=$('planningDrivewayFeature')?.value,siteId=$('planningBuildSiteFeature')?.value,drive=planning?.drivewayAnalyses?.[routeId],site=planning?.buildSiteAnalyses?.[siteId],driveout=$('drivewayEstimateReadout'),siteout=$('buildSiteReadout');if(driveout)driveout.innerHTML=drive?`<b>${safe(drive.classification)}</b> · ${drive.lengthFeet.toLocaleString()} ft · <b>${money(drive.low)}–${money(drive.high)}</b><br>Expected: ${money(drive.expected)} · Inputs: user-entered (${safe(drive.terrainClass)}, ${safe(drive.surface)}, ${drive.averageSlope||'slope unknown'}% average).<br><span class="small">Drivers: ${safe((drive.drivers||[]).join(', ')||'route length and terrain')}. Calculated ${new Date(drive.calculatedAt).toLocaleString()}.</span>`:'Draw and select a driveway route to calculate a property-specific range.';if(siteout)siteout.innerHTML=site?`<b>${safe(site.classification)}</b> · ${site.areaAcres?.toFixed(2)||'0.00'} ac outlined<br>${safe(site.terrainNote||'Terrain not entered.')} ${safe(site.utilityNote||'')}<br><span class="small">Septic: ${safe(site.septicStatus||'unknown')} · user-entered assessment, updated ${new Date(site.updatedAt).toLocaleString()}.</span>`:'Draw and select one or more build-site areas to compare them.'}
 function selectFeature(id){selectedFeatureId=id;const feature=selectedFeature();if(!feature)return;setField('planningFeatureLabel',feature.label);setField('planningFeatureNotes',feature.notes);if($('planningFeatureType'))$('planningFeatureType').value=feature.type;status(`${FEATURE_NAMES[feature.type]} selected. Edit its label, notes, or geometry.`);renderFeatures()}
function drawPreview(){clearWorking();if(!drawing?.coordinates.length)return;const map=MAP(),points=drawing.coordinates.map(item=>[item.lat,item.lng]);if(drawing.geometry==='LineString')workingLayer=L.polyline(points,{color:'#b6672c',dashArray:'6 6',weight:4}).addTo(map);else if(drawing.geometry==='Polygon')workingLayer=L.polygon(points,{color:'#24725d',dashArray:'6 6',fillOpacity:.10}).addTo(map)}
 function createFeature(type,coordinates){recordPlanningHistory(`adding ${FEATURE_NAMES[type].toLowerCase()}`);const feature=normalizeFeature({id:`spf-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,type,geometry:{type:geometryFor(type),coordinates},label:FEATURE_NAMES[type],notes:'',inputSource:'user-entered',confidence:'user-estimated',createdAt:now(),updatedAt:now()});planning.features.push(feature);selectedFeatureId=feature.id;savePlan(`Added ${FEATURE_NAMES[type].toLowerCase()}`);renderFeatures();return feature}
 function setDrawingMapInteraction(active){const zoom=MAP()?.doubleClickZoom;if(active){drawingMapDoubleClickWasEnabled=!!zoom?.enabled?.();if(drawingMapDoubleClickWasEnabled)zoom.disable()}else if(drawingMapDoubleClickWasEnabled){zoom?.enable?.();drawingMapDoubleClickWasEnabled=false}}
 function startDrawing(){if(!planning)return;clearVertices();lastDrawingClick=null;const type=$('planningFeatureType').value;drawing={type,geometry:geometryFor(type),coordinates:[]};setDrawingMapInteraction(true);status(`${FEATURE_NAMES[type]}: click the satellite map ${drawing.geometry==='Point'?'once':'for each vertex, then choose Finish drawing'}.`);document.querySelector('[data-view="mapView"]')?.click();document.querySelector('input[name="baseLayer"][value="satellite"]')?.click()}
 function finishDrawing(){if(!drawing)return;const required=drawing.geometry==='Point'?1:drawing.geometry==='LineString'?2:3;if(drawing.coordinates.length<required){status(`Add at least ${required} map point${required===1?'':'s'} before finishing.`);return}const type=drawing.type,coords=clone(drawing.coordinates);drawing=null;lastDrawingClick=null;setDrawingMapInteraction(false);clearWorking();if(type==='measure'){status(`Measurement: ${round(lineFeet(coords)).toLocaleString()} ft. It was not saved as a planning feature.`);updateToolbar();return}createFeature(type,coords);status(`${FEATURE_NAMES[type]} saved for this property. Select it to add notes or edit geometry.`);updateToolbar()}
 function onMapClick(event){if(!drawing){if(selectedFeatureId){selectedFeatureId='';clearVertices();renderFeatures();status('Planning feature deselected.')}return}const next=point(event.latlng.lat,event.latlng.lng),stamp=Date.now(),duplicate=lastDrawingClick&&stamp-lastDrawingClick.at<350&&Math.abs(next.lat-lastDrawingClick.lat)<1e-8&&Math.abs(next.lng-lastDrawingClick.lng)<1e-8;if(duplicate)return;lastDrawingClick={lat:next.lat,lng:next.lng,at:stamp};drawing.coordinates.push(next);if(drawing.geometry==='Point')finishDrawing();else{drawPreview();status(`${drawing.coordinates.length} point${drawing.coordinates.length===1?'':'s'} recorded. Finish drawing when complete.`)}}
function editGeometry(){const feature=selectedFeature();if(!feature){status('Select a saved planning feature first.');return}clearVertices();vertexGroup=L.featureGroup().addTo(MAP());feature.geometry.coordinates.forEach((coord,index)=>{const marker=L.marker([coord.lat,coord.lng],{draggable:true,title:`Vertex ${index+1}`}).addTo(vertexGroup);marker.on('dragend',event=>{const next=event.target.getLatLng();feature.geometry.coordinates[index]=point(next.lat,next.lng);feature.updatedAt=now();savePlan(`Adjusted ${FEATURE_NAMES[feature.type].toLowerCase()} geometry`);renderFeatures();status('Geometry saved. Drag another vertex or choose Edit geometry again when finished.')})});status('Drag the visible vertex handles to edit. Each drag saves only this property’s planning feature.')}
 function saveFeatureDetails(){const feature=selectedFeature();if(!feature){status('Select a planning feature first.');return}recordPlanningHistory(`updating ${FEATURE_NAMES[feature.type].toLowerCase()} details`);feature.label=$('planningFeatureLabel').value.trim()||FEATURE_NAMES[feature.type];feature.notes=$('planningFeatureNotes').value.trim();feature.relationships=[...($('planningRelationships')?.selectedOptions||[])].map(option=>option.value);feature.updatedAt=now();savePlan(`Updated ${FEATURE_NAMES[feature.type].toLowerCase()} details`);renderFeatures();status('Feature details and relationships saved.')}
function deleteFeature(){const feature=selectedFeature();if(!feature)return;if(!confirm(`Delete ${feature.label}? This removes only this planning feature from ${activeProperty()?.name||'this property'}.`))return;planning.features=planning.features.filter(item=>item.id!==feature.id);delete planning.drivewayAnalyses[feature.id];delete planning.buildSiteAnalyses[feature.id];selectedFeatureId='';clearVertices();savePlan(`Deleted ${FEATURE_NAMES[feature.type].toLowerCase()}`);renderFeatures();status('Planning feature deleted.')}
function fillDrivewayInputs(){const id=$('planningDrivewayFeature').value,analysis=planning?.drivewayAnalyses?.[id];if(!analysis)return;setField('planningTerrainClass',analysis.terrainClass);setField('planningSurface',analysis.surface);setField('planningAverageSlope',analysis.averageSlope);setField('planningMaximumSlope',analysis.maximumSlope);setField('planningClearingWidth',analysis.clearingWidth);setField('planningSwitchbacks',analysis.switchbacks);setField('planningCulverts',analysis.culverts);setField('planningRetainingFeet',analysis.retainingFeet);$('planningRockRisk').checked=!!analysis.rockRisk;$('planningDrainage').checked=!!analysis.drainage;$('planningCreekCrossing').checked=!!analysis.creekCrossing}
function saveDriveway(){const id=$('planningDrivewayFeature').value,feature=planning?.features.find(item=>item.id===id);if(!feature){status('Draw and select a driveway route first.');return}const input={lengthFeet:lineFeet(feature.geometry.coordinates),terrainClass:$('planningTerrainClass').value,surface:$('planningSurface').value,averageSlope:num($('planningAverageSlope').value),maximumSlope:num($('planningMaximumSlope').value),clearingWidth:num($('planningClearingWidth').value)||16,switchbacks:num($('planningSwitchbacks').value),culverts:num($('planningCulverts').value),retainingFeet:num($('planningRetainingFeet').value),rockRisk:$('planningRockRisk').checked,drainage:$('planningDrainage').checked,creekCrossing:$('planningCreekCrossing').checked,inputSource:'user-entered',confidence:'user-estimated'};const estimate=estimateDriveway(input);planning.drivewayAnalyses[id]={...input,...estimate};savePlan(`Updated driveway feasibility for ${feature.label}`);renderFeatures();status('Driveway feasibility and range estimate saved for this property.')}
function fillBuildSiteInputs(){const id=$('planningBuildSiteFeature').value,analysis=planning?.buildSiteAnalyses?.[id];if(!analysis)return;setField('planningBuildSiteClass',analysis.classification);setField('planningBuildTerrain',analysis.terrainNote);setField('planningSepticStatus',analysis.septicStatus);setField('planningUtilityNote',analysis.utilityNote);setField('planningBuildNotes',analysis.notes)}
function saveBuildSite(){const id=$('planningBuildSiteFeature').value,feature=planning?.features.find(item=>item.id===id);if(!feature){status('Draw and select a build-site area first.');return}recordPlanningHistory(`updating build-site feasibility for ${feature.label}`);const input={padFootprint:num($('planningPadFootprint').value),clearingPct:num($('planningBuildClearingPct').value),cutFill:$('planningCutFill').value,drainage:$('planningBuildDrainage').value,rock:$('planningBuildRock').checked,retaining:$('planningBuildRetaining').checked,accessHard:$('planningBuildAccessHard').checked},estimate=estimateBuildSite(input);planning.buildSiteAnalyses[id]={featureId:id,areaAcres:polygonAcres(feature.geometry.coordinates),classification:$('planningBuildSiteClass').value,terrainNote:$('planningBuildTerrain').value.trim(),septicStatus:$('planningSepticStatus').value,utilityNote:$('planningUtilityNote').value.trim(),notes:$('planningBuildNotes').value.trim(),...input,...estimate,inputSource:'user-entered',confidence:'user-estimated',updatedAt:now()};savePlan(`Updated build-site feasibility for ${feature.label}`);renderFeatures();status('Build-site assessment saved for this property.')}
function utilityFeatures(){return planning?.features.filter(feature=>LINE_TYPES.has(feature.type)&&feature.type!=='driveway-route')||[]}
function renderUtilityControls(){const select=$('planningUtilityFeature');if(!select||!planning)return;const prior=select.value;select.innerHTML=`<option value="">Select a utility route</option>${utilityFeatures().map(feature=>`<option value="${feature.id}">${safe(feature.label)} · ${featureMeasure(feature)}</option>`).join('')}`;select.value=prior||utilityFeatures()[0]?.id||''}
function saveUtility(){const id=$('planningUtilityFeature').value,feature=planning?.features.find(item=>item.id===id);if(!feature){status('Draw and select a utility route first.');return}recordPlanningHistory(`updating utility estimate for ${feature.label}`);const input={lengthFeet:lineFeet(feature.geometry.coordinates),type:$('planningUtilityType').value,terrain:$('planningUtilityTerrain').value,rock:$('planningUtilityRock').checked,crossing:$('planningUtilityCrossing').checked};planning.utilityAnalyses=planning.utilityAnalyses||{};planning.utilityAnalyses[id]={...input,...estimateUtility(input),inputSource:'user-entered',confidence:'user-estimated'};savePlan(`Updated utility estimate for ${feature.label}`);renderFeatures();status('Utility estimate saved; provider extension charges remain unknown.')}
function renderCombined(){const out=$('combinedEstimateReadout'),check=$('planningChecklist');if(!out||!planning)return;const drives=Object.values(planning.drivewayAnalyses||{}),builds=Object.values(planning.buildSiteAnalyses||{}),utilities=Object.values(planning.utilityAnalyses||{}),all=[...drives,...builds,...utilities],sum=key=>all.reduce((total,item)=>total+(num(item[key])||0),0),unpriced=[];if(!drives.length)unpriced.push('driveway');if(!builds.length)unpriced.push('build-site preparation');if(!utilities.length)unpriced.push('utility provider charges');out.innerHTML=all.length?`<b>Preliminary priced scope: ${money(sum('low'))}–${money(sum('high'))}</b><br>Expected priced subtotal: ${money(sum('expected'))}. ${unpriced.length?`Unpriced / unresolved: ${safe(unpriced.join(', '))}.`:'Provider and permit charges still require confirmation.'}`:'Add a driveway, build site, or utility route to establish a preliminary priced scope.';const items=[!drives.length&&'Confirm legal access and proposed driveway route',!builds.length&&'Outline and evaluate at least one build site',!utilities.length&&'Locate electric, water, and communications service',drives.some(item=>item.creekCrossing)&&'Confirm creek-crossing approval',builds.some(item=>item.septicStatus==='unknown')&&'Order soil/septic evaluation'].filter(Boolean);if(check)check.innerHTML=items.map(item=>`<div class="planning-feature"><b>Open</b><span>${safe(item)}</span></div>`).join('')||'<div class="small">No immediate planning checklist items generated.</div>'}
function planningSummary(property){const plan=normalizePlan(property.sitePlanning),routes=Object.entries(plan.drivewayAnalyses),sites=Object.entries(plan.buildSiteAnalyses),priority={preferred:0,viable:1,conditional:2,poor:3},bestSite=sites.sort((a,b)=>(priority[a[1].classification]??9)-(priority[b[1].classification]??9))[0],drive=routes.sort((a,b)=>a[1].expected-b[1].expected)[0];return {plan,bestSite:bestSite&&plan.features.find(feature=>feature.id===bestSite[0]),bestSiteAssessment:bestSite?.[1],driveFeature:drive&&plan.features.find(feature=>feature.id===drive[0]),driveAnalysis:drive?.[1]}}
function addDossierPlanning(id){const property=window.OTPropertyStore?.getProperty?.(id),panel=document.querySelector('#drawer [data-dossier-tab="Map & Site"]');if(!property||!panel||panel.querySelector('[data-dossier-planning]'))return;const summary=planningSummary(property),siteName=summary.bestSite?summary.bestSite.label:'No build site selected',routeName=summary.driveFeature?summary.driveFeature.label:'No driveway route selected',range=summary.driveAnalysis?`${money(summary.driveAnalysis.low)}–${money(summary.driveAnalysis.high)}`:'No range calculated',section=document.createElement('section');section.className='section planning-overview';section.dataset.dossierPlanning='true';section.innerHTML=`<h3>Site planning</h3><div class="planning-summary"><div><b>Build site</b><span>${safe(siteName)}${summary.bestSiteAssessment?` · ${safe(summary.bestSiteAssessment.classification)}`:''}</span></div><div><b>Preferred driveway</b><span>${safe(routeName)}</span></div><div><b>Development range</b><span>${safe(range)}</span></div></div><button class="secondary outline" type="button" onclick="openSitePlanning('${property.id}')">Open Site Planning</button>`;panel.appendChild(section)}
function openSitePlanning(id){if(activePropertyId)flushPlanSave();const property=window.OTPropertyStore?.getProperty?.(id);if(!property)return;window.OTOverlayManager?.prepare?.('planning');activePropertyId=id;planning=normalizePlan(property.sitePlanning);const migrated=ensureConcepts();window.OTDiagnostics?.setContext?.({propertyId:id,concept:activeConcept()?.name||'',coordinateSource:property.locationVerification?.source||property.pinQuality||''});selectedFeatureId='';drawing=null;lastDrawingClick=null;setDrawingMapInteraction(false);clearWorking();clearVertices();$('sitePlanningPanel').hidden=false;$('planningMapToolbar').hidden=false;$('sitePlanningProperty').textContent=`${property.name||property.address} · ${property.id} · satellite workspace`;document.querySelector('[data-view="mapView"]')?.click();document.querySelector('input[name="baseLayer"][value="satellite"]')?.click();MAP()?.setView([property.lat,property.lng],15,{animate:false});renderConcepts();renderFeatures();updateHistoryControls();setSaveStatus('Saved.','saved');if(migrated)savePlan('Migrated existing site plan into Concept A',{immediate:true});status('Satellite workspace ready. Planning geometry is saved only inside this property record.');window.OTOverlayManager?.opened?.('planning')}
function closeSitePlanning(){flushPlanSave();drawing=null;lastDrawingClick=null;setDrawingMapInteraction(false);clearWorking();clearVertices();if(planningGroup)planningGroup.clearLayers();$('sitePlanningPanel').hidden=true;$('planningMapToolbar').hidden=true;activePropertyId='';planning=null;selectedFeatureId='';window.OTDiagnostics?.setContext?.({concept:''});updateHistoryControls()}
function toolbarKey(){return 'ot-planning-toolbar-collapsed'}
function terrainDrivewayRoutes(){return planning?.features.filter(feature=>feature.type==='driveway-route')||[]}
function terrainRouteFingerprint(feature){return window.OTElevation?.geometryFingerprint?.(feature?.geometry?.coordinates||[])||''}
function terrainProfile(routeId){return planning?.elevationProfiles?.[routeId]||null}
function terrainProfileCurrent(feature,profile){return !!(feature&&profile?.success&&!profile.stale&&profile.geometryFingerprint===terrainRouteFingerprint(feature))}
function markTerrainProfileStale(feature,reason='The driveway geometry changed.'){if(feature?.type!=='driveway-route')return;const profile=terrainProfile(feature.id);if(profile){profile.stale=true;profile.staleAt=now();profile.staleReason=reason}if(planning?.drivewayAnalyses?.[feature.id])planning.drivewayAnalyses[feature.id].elevationProfileStale=true}
function terrainRouteOptions(empty){return `<option value="">${empty}</option>${terrainDrivewayRoutes().map(feature=>`<option value="${safe(feature.id)}">${safe(feature.label)} - ${featureMeasure(feature)}</option>`).join('')}`}
function renderTerrainPreferredRoutes(){const select=$('planningPreferredRoute');if(!select)return;const current=planning?.preferredDrivewayRouteId||'';select.innerHTML=terrainRouteOptions('Select a preferred route');select.value=terrainDrivewayRoutes().some(feature=>feature.id===current)?current:''}
function renderTerrainControls(){const list=$('planningFeatureList'),routes=$('planningDrivewayFeature'),sites=$('planningBuildSiteFeature');if(!planning||!list||!routes||!sites)return;const priorRoute=routes.value,priorSite=sites.value,priorA=$('planningCompareRouteA')?.value,priorB=$('planningCompareRouteB')?.value,allRoutes=terrainDrivewayRoutes();list.innerHTML=planning.features.length?planning.features.map(feature=>`<button type="button" class="planning-feature ${feature.id===selectedFeatureId?'selected':''}" data-site-feature="${safe(feature.id)}"><b>${safe(FEATURE_NAMES[feature.type])}</b><span>${safe(feature.label)} - ${featureMeasure(feature)}</span></button>`).join(''):'<div class="small">No planning features saved for this property.</div>';list.querySelectorAll('[data-site-feature]').forEach(button=>button.addEventListener('click',()=>selectFeature(button.dataset.siteFeature)));const options=(filter,empty)=>`<option value="">${empty}</option>${planning.features.filter(filter).map(feature=>`<option value="${safe(feature.id)}">${safe(feature.label)} - ${featureMeasure(feature)}</option>`).join('')}`;routes.innerHTML=terrainRouteOptions('Select a driveway route');sites.innerHTML=options(feature=>feature.type==='build-site','Select a build-site area');routes.value=planning.drivewayAnalyses[priorRoute]?priorRoute:allRoutes[0]?.id||'';sites.value=planning.buildSiteAnalyses[priorSite]?priorSite:planning.features.find(feature=>feature.type==='build-site')?.id||'';[['planningCompareRouteA',priorA,allRoutes[0]?.id||''],['planningCompareRouteB',priorB,allRoutes[1]?.id||allRoutes[0]?.id||'']].forEach(([id,prior,fallback])=>{const select=$(id);if(select){select.innerHTML=terrainRouteOptions('Select a route');select.value=allRoutes.some(feature=>feature.id===prior)?prior:fallback}});const feature=selectedFeature(),related=$('planningRelationships');if(related)related.innerHTML=feature?planning.features.filter(item=>item.id!==feature.id).map(item=>`<option value="${safe(item.id)}" ${(feature.relationships||[]).includes(item.id)?'selected':''}>${safe(FEATURE_NAMES[item.type])} - ${safe(item.label)}</option>`).join(''):'<option disabled>Select a feature first</option>';if(feature){setField('planningFeatureLabel',feature.label);setField('planningFeatureNotes',feature.notes)}}
function terrainProfileMetrics(profile){const bands=profile.gradeBands||{};return `<div class="elevation-metrics"><span>Gain <b>${profile.elevationGainFeet} ft</b></span><span>Loss <b>${profile.elevationLossFeet} ft</b></span><span>Average <b>${profile.averageGradePct}%</b></span><span>Maximum <b>${profile.maximumSegmentGradePct}%</b></span><span>Sustained <b>${profile.steepestSustainedGradePct}%</b></span><span>&gt;10% <b>${profile.longestContinuousAbove10Feet} ft</b></span><span>&gt;15% <b>${profile.longestContinuousAbove15Feet} ft</b></span></div><div class="small">Grade bands: 0-5% ${bands.gentle?.percent??0}% | over 5-10% ${bands.moderate?.percent??0}% | over 10-15% ${bands.steep?.percent??0}% | over 15-20% ${bands['very-steep']?.percent??0}% | over 20% ${bands.severe?.percent??0}%.</div>`}
function terrainProfileChart(profile){if(!profile?.success||!Array.isArray(profile.samples)||profile.samples.length<2)return '';const width=460,height=150,pad=28,min=profile.minimumElevationFeet,max=profile.maximumElevationFeet,range=Math.max(1,max-min),length=Math.max(1,profile.totalLengthFeet),x=sample=>pad+(sample.cumulativeFeet/length)*(width-pad*2),y=sample=>height-pad-((sample.elevationFeet-min)/range)*(height-pad*2),path=profile.samples.map((sample,index)=>`${index?'L':'M'}${x(sample).toFixed(1)},${y(sample).toFixed(1)}`).join(' '),markers=profile.samples.filter(sample=>sample.segmentGradePct>10).map(sample=>`<circle cx="${x(sample).toFixed(1)}" cy="${y(sample).toFixed(1)}" r="${sample.segmentGradePct>20?4:sample.segmentGradePct>15?3:2}" class="grade-marker grade-${sample.segmentGradePct>20?'severe':sample.segmentGradePct>15?'very-steep':'steep'}"><title>${sample.segmentGradePct.toFixed(1)}% segment grade</title></circle>`).join('');return `<svg class="elevation-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Preliminary driveway elevation profile"><line x1="${pad}" y1="${height-pad}" x2="${width-pad}" y2="${height-pad}" class="elevation-axis"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${height-pad}" class="elevation-axis"/><path d="${path}" class="elevation-path"/>${markers}<text x="${pad}" y="16">${Math.round(max)} ft high</text><text x="${pad}" y="${height-6}">${Math.round(min)} ft low</text><text x="${width-pad}" y="${height-6}" text-anchor="end">${Math.round(length).toLocaleString()} ft</text></svg>`}
function renderTerrainElevation(routeId){const target=$('drivewayElevationReadout'),feature=planning?.features.find(item=>item.id===routeId),profile=terrainProfile(routeId),manual=planning?.manualElevationOverrides?.[routeId];if(!target)return;if(terrainProfileCurrent(feature,profile))target.innerHTML=`<b>Measured elevation - preliminary planning only</b><br>${terrainProfileMetrics(profile)}${terrainProfileChart(profile)}<span class="small">${safe(profile.provider)} | retrieved ${new Date(profile.retrievedAt).toLocaleString()} | ${profile.sampleSpacingFeet}-ft sampling. Markers: amber over 10%, orange over 15%, red over 20%.</span>`;else if(profile?.success)target.innerHTML=`<b>Elevation profile is stale.</b><br><span class="small">${safe(profile.staleReason||'The driveway geometry no longer matches the measured profile.')} Request a new profile before relying on its cost adjustments.</span>`;else if(profile?.failure)target.innerHTML=`<b>Measured elevation unavailable.</b><br><span class="small">${safe(profile.failure.message)} Manual elevation values remain separate and are not replaced.</span>`;else if(manual?.enabled)target.innerHTML=`<b>User-estimated elevation</b><br><span class="small">Start ${manual.startElevationFeet||'unknown'} ft | End ${manual.endElevationFeet||'unknown'} ft | Average ${manual.estimatedAverageGradePct||'unknown'}% | Maximum ${manual.estimatedMaximumGradePct||'unknown'}%. This is not provider-derived data.</span>`;else target.innerHTML='<span class="small">Request a preliminary profile, or keep using clearly labelled manual terrain estimates. Elevation data is not engineering approval.</span>'}
function compareTerrainRoute(routeId){const feature=planning?.features.find(item=>item.id===routeId),analysis=planning?.drivewayAnalyses?.[routeId],profile=terrainProfile(routeId);return {feature,analysis,profile:terrainProfileCurrent(feature,profile)?profile:null}}
function renderTerrainCostAdjustments(){const routeId=$('planningDrivewayFeature')?.value,target=$('drivewayElevationReadout'),analysis=planning?.drivewayAnalyses?.[routeId];if(!target||!analysis?.costAdjustments?.length)return;target.insertAdjacentHTML('beforeend',`<div class="small elevation-cost-adjustments"><b>Measured-cost adjustments included:</b> ${safe(analysis.costAdjustments.map(item=>item.name).join(', '))}. Preliminary ranges remain subject to drainage, rock, cut-and-fill, and contractor verification.</div>`)}
function renderTerrainComparison(){const target=$('drivewayComparisonReadout'),a=compareTerrainRoute($('planningCompareRouteA')?.value),b=compareTerrainRoute($('planningCompareRouteB')?.value);if(!target)return;if(!a.feature||!b.feature){target.innerHTML='<span class="small">Select two driveway routes in this concept to compare their route length, grade, and preliminary range.</span>';return}const range=route=>route.analysis?`${money(route.analysis.low)} - ${money(route.analysis.expected)} - ${money(route.analysis.high)}`:'-';const metrics=route=>route.profile?`${route.profile.averageGradePct}% / ${route.profile.maximumSegmentGradePct}%`:'manual / unknown';target.innerHTML=`<div class="driveway-compare"><div></div><div><b>${safe(a.feature.label)}</b>${planning.preferredDrivewayRouteId===a.feature.id?' - Preferred':''}</div><div><b>${safe(b.feature.label)}</b>${planning.preferredDrivewayRouteId===b.feature.id?' - Preferred':''}</div><div>Length</div><div>${Math.round(lineFeet(a.feature.geometry.coordinates)).toLocaleString()} ft</div><div>${Math.round(lineFeet(b.feature.geometry.coordinates)).toLocaleString()} ft</div><div>Elevation gain</div><div>${a.profile?`${a.profile.elevationGainFeet} ft`:'-'}</div><div>${b.profile?`${b.profile.elevationGainFeet} ft`:'-'}</div><div>Average / maximum grade</div><div>${metrics(a)}</div><div>${metrics(b)}</div><div>Continuous above 10% / 15%</div><div>${a.profile?`${a.profile.longestContinuousAbove10Feet} / ${a.profile.longestContinuousAbove15Feet} ft`:'-'}</div><div>${b.profile?`${b.profile.longestContinuousAbove10Feet} / ${b.profile.longestContinuousAbove15Feet} ft`:'-'}</div><div>Switchback pressure</div><div>${a.profile?.switchbackPressure||'manual / unknown'}</div><div>${b.profile?.switchbackPressure||'manual / unknown'}</div><div>Low / expected / high</div><div>${range(a)}</div><div>${range(b)}</div><div>Primary cost drivers</div><div>${safe(a.analysis?.drivers?.join(', ')||'-')}</div><div>${safe(b.analysis?.drivers?.join(', ')||'-')}</div></div>`}
function renderTerrainReadouts(){const routeId=$('planningDrivewayFeature')?.value,siteId=$('planningBuildSiteFeature')?.value,drive=planning?.drivewayAnalyses?.[routeId],site=planning?.buildSiteAnalyses?.[siteId],driveout=$('drivewayEstimateReadout'),siteout=$('buildSiteReadout');if(driveout)driveout.innerHTML=drive?`<b>${safe(drive.classification)}</b> - ${drive.lengthFeet.toLocaleString()} ft - <b>${money(drive.low)}-${money(drive.high)}</b><br>Expected: ${money(drive.expected)} | Basis: <b>${safe(drive.estimateBasis||'Manual terrain')}</b> | Inputs: ${safe(drive.terrainClass)}, ${safe(drive.surface)}, ${drive.averageSlope||'slope unknown'}% manual average.<br><span class="small">Drivers: ${safe((drive.drivers||[]).join(', ')||'route length and terrain')}. Calculated ${new Date(drive.calculatedAt).toLocaleString()}.</span>`:'Draw and select a driveway route to calculate a property-specific range.';renderTerrainElevation(routeId);renderTerrainComparison();if(siteout)siteout.innerHTML=site?`<b>${safe(site.classification)}</b> - ${site.areaAcres?.toFixed(2)||'0.00'} ac outlined<br>${safe(site.terrainNote||'Terrain not entered.')} ${safe(site.utilityNote||'')}<br><span class="small">Septic: ${safe(site.septicStatus||'unknown')} - user-entered assessment, updated ${new Date(site.updatedAt).toLocaleString()}.</span>`:'Draw and select one or more build-site areas to compare them.'}
function readTerrainManualElevation(routeId,feature){const enabled=!!$('planningManualElevationEnabled')?.checked,values={enabled,startElevationFeet:num($('planningStartElevation')?.value),endElevationFeet:num($('planningEndElevation')?.value),estimatedAverageGradePct:num($('planningAverageSlope')?.value),estimatedMaximumGradePct:num($('planningMaximumSlope')?.value),terrainClass:$('planningTerrainClass')?.value||'rolling',note:$('planningManualElevationNote')?.value.trim()||''};planning.manualElevationOverrides=planning.manualElevationOverrides||{};if(enabled)planning.manualElevationOverrides[routeId]={...window.OTElevation?.manualElevationFallback?.(feature.geometry.coordinates,values),...values,updatedAt:now()};else delete planning.manualElevationOverrides[routeId];return planning.manualElevationOverrides[routeId]||null}
function terrainDrivewayInput(feature){const routeId=feature.id,profile=terrainProfile(routeId),manual=readTerrainManualElevation(routeId,feature),validProfile=terrainProfileCurrent(feature,profile)?profile:null;return {lengthFeet:lineFeet(feature.geometry.coordinates),terrainClass:$('planningTerrainClass').value,surface:$('planningSurface').value,averageSlope:num($('planningAverageSlope').value),maximumSlope:num($('planningMaximumSlope').value),clearingWidth:num($('planningClearingWidth').value)||16,switchbacks:num($('planningSwitchbacks').value),culverts:num($('planningCulverts').value),retainingFeet:num($('planningRetainingFeet').value),rockRisk:$('planningRockRisk').checked,drainage:$('planningDrainage').checked,creekCrossing:$('planningCreekCrossing').checked,inputSource:'user-entered',confidence:'user-estimated',elevationProfile:validProfile,manualElevationOverride:manual}}
 function saveTerrainDriveway(message='Driveway feasibility and range estimate saved for this property.',options={}){const id=$('planningDrivewayFeature').value,feature=planning?.features.find(item=>item.id===id);if(!feature){status('Draw and select a driveway route first.');return false}if(options.recordHistory!==false)recordPlanningHistory(`updating driveway feasibility for ${feature.label}`);const input=terrainDrivewayInput(feature),estimate=estimateDriveway(input),profile=terrainProfile(id);planning.drivewayAnalyses[id]={...input,...estimate,elevationProfileFingerprint:profile?.geometryFingerprint||'',elevationProfileStale:!!(profile&&!terrainProfileCurrent(feature,profile))};savePlan(`Updated driveway feasibility for ${feature.label}`);renderFeatures();status(message);return true}
 async function requestTerrainElevation(){const id=$('planningDrivewayFeature')?.value,feature=planning?.features.find(item=>item.id===id),button=$('requestElevationProfileBtn'),scope=historyScope();if(!feature){status('Draw and select a driveway route first.');return}if(!window.OTElevation?.getElevationProfile){status('The elevation adapter did not load. Manual terrain estimates remain available.');return}if(button)button.disabled=true;status('Locating preliminary elevations along the full driveway route...');const profile=await window.OTElevation.getElevationProfile(feature.geometry.coordinates);if(scope!==historyScope()||!planning?.features.some(item=>item.id===id)){if(button)button.disabled=false;status('The active property or concept changed, so the returned profile was not applied.');return}recordPlanningHistory(`updating elevation profile for ${feature.label}`);planning.elevationProfiles=planning.elevationProfiles||{};planning.elevationProfiles[id]={...profile,stale:false,lastRequestedAt:now()};if(profile.success){saveTerrainDriveway(profile.cached?'Reused the unchanged cached elevation profile and refreshed the driveway estimate.':'Measured elevation profile saved and applied to the driveway estimate.',{recordHistory:false})}else{saveTerrainDriveway('Elevation retrieval did not complete. Manual terrain planning was preserved; see the profile message for details.',{recordHistory:false})}if(button)button.disabled=false}
function fillTerrainDrivewayInputs(){fillDrivewayInputs();const id=$('planningDrivewayFeature')?.value,manual=planning?.manualElevationOverrides?.[id];if(!id)return;$('planningManualElevationEnabled').checked=!!manual?.enabled;setField('planningStartElevation',manual?.startElevationFeet);setField('planningEndElevation',manual?.endElevationFeet);setField('planningManualElevationNote',manual?.note)}
 function choosePreferredDriveway(){const id=$('planningPreferredRoute')?.value;if(!planning?.features.some(feature=>feature.id===id&&feature.type==='driveway-route')){status('Select a driveway route in this concept first.');return}recordPlanningHistory('choosing preferred driveway route');planning.preferredDrivewayRouteId=id;const concept=activeConcept();if(concept)concept.preferredDrivewayRouteId=id;savePlan('Marked preferred driveway route');renderFeatures();status('Preferred driveway route saved for this concept.')}
 function editTerrainGeometry(){const feature=selectedFeature();if(!feature){status('Select a saved planning feature first.');return}clearVertices();vertexGroup=L.featureGroup().addTo(MAP());feature.geometry.coordinates.forEach((coord,index)=>{const marker=L.marker([coord.lat,coord.lng],{draggable:true,title:`Vertex ${index+1}`}).addTo(vertexGroup);marker.on('dragstart',()=>{recordPlanningHistory(`adjusting ${FEATURE_NAMES[feature.type].toLowerCase()} geometry`);vertexDragMapWasEnabled=!!MAP()?.dragging?.enabled?.();if(vertexDragMapWasEnabled)MAP()?.dragging?.disable()});marker.on('dragend',event=>{if(vertexDragMapWasEnabled){MAP()?.dragging?.enable();vertexDragMapWasEnabled=false}const next=event.target.getLatLng();feature.geometry.coordinates[index]=point(next.lat,next.lng);feature.updatedAt=now();markTerrainProfileStale(feature);savePlan(`Adjusted ${FEATURE_NAMES[feature.type].toLowerCase()} geometry`);renderFeatures();status(feature.type==='driveway-route'?'Geometry saved. Its elevation profile is now stale and will not affect the estimate until refreshed.':'Geometry saved. Drag another vertex or choose Edit geometry again when finished.')})});status('Drag the visible vertex handles to edit. Map panning pauses while a vertex is being moved.')}
 function deleteTerrainFeature(){const feature=selectedFeature();if(!feature)return;const dependent=planning.features.filter(item=>(item.relationships||[]).includes(feature.id));if(!confirm(`Delete ${feature.label}? This removes only this planning feature from ${activeProperty()?.name||'this property'}${dependent.length?` and clears ${dependent.length} related feature link${dependent.length===1?'':'s'}`:''}.`))return;recordPlanningHistory(`deleting ${FEATURE_NAMES[feature.type].toLowerCase()}`);planning.features=planning.features.filter(item=>item.id!==feature.id);planning.features.forEach(item=>{item.relationships=(item.relationships||[]).filter(id=>id!==feature.id)});delete planning.drivewayAnalyses[feature.id];delete planning.buildSiteAnalyses[feature.id];delete planning.utilityAnalyses?.[feature.id];delete planning.elevationProfiles?.[feature.id];delete planning.manualElevationOverrides?.[feature.id];if(planning.preferredDrivewayRouteId===feature.id)planning.preferredDrivewayRouteId='';const concept=activeConcept();if(concept?.preferredDrivewayRouteId===feature.id)concept.preferredDrivewayRouteId='';selectedFeatureId='';clearVertices();savePlan(`Deleted ${FEATURE_NAMES[feature.type].toLowerCase()}`);renderFeatures();status('Planning feature deleted. Associated driveway profile and route preference were reconciled.')}
function setToolbarCollapsed(collapsed){const bar=$('planningMapToolbar');if(!bar)return;bar.classList.toggle('collapsed',!!collapsed);try{const value=collapsed?'1':'0';window.OTSaveReliability?.preflightStorageWrite?.(localStorage,{[toolbarKey()]:value});localStorage.setItem(toolbarKey(),value)}catch{}}
 function clearTerrainFeatures(){if(!planning?.features?.length){status('There are no planning features to clear in this concept.');return}if(!confirm(`Clear every planning feature and estimate in ${activeConcept()?.name||'this concept'}? Other property concepts are not affected.`))return;recordPlanningHistory('clearing this concept');const concept=activeConcept();Object.assign(concept,{features:[],drivewayAnalyses:{},buildSiteAnalyses:{},utilityAnalyses:{},elevationProfiles:{},manualElevationOverrides:{},preferredDrivewayRouteId:'',relationships:{},updatedAt:now()});syncConcept();selectedFeatureId='';clearVertices();savePlan('Cleared active site-plan concept');renderFeatures();status('This concept was cleared. Use Undo edit to restore it.')}
 function cancelDrawing(){if(!drawing)return;drawing=null;lastDrawingClick=null;setDrawingMapInteraction(false);clearWorking();status('Drawing cancelled. Existing planning features were not changed.');updateToolbar()}
function undoPoint(){if(!drawing?.coordinates?.length)return;drawing.coordinates.pop();drawPreview();status('Last drawing point removed.');updateToolbar()}
function updateToolbar(){const active=$('planningActiveTool'),cancel=$('planningCancelDrawBtn');if(active)active.textContent=drawing?FEATURE_NAMES[drawing.type]||drawing.type:'Navigate';if(cancel)cancel.hidden=!drawing}
 function selectToolbarTool(type){if(type==='select'){cancelDrawing();status('Select a feature on the map to edit it, or click open map space to deselect it.');return}if(type==='measure'){clearVertices();lastDrawingClick=null;drawing={type:'measure',geometry:'LineString',coordinates:[]};setDrawingMapInteraction(true);status('Measure: click map points, then Finish. This measurement is not saved.');updateToolbar();return}const select=$('planningFeatureType');if(select&&[...select.options].some(option=>option.value===type))select.value=type;else if(select){const option=document.createElement('option');option.value=type;option.textContent=FEATURE_NAMES[type]||type;select.appendChild(option);select.value=type}startDrawing();if(matchMedia('(max-width: 760px)').matches)setToolbarCollapsed(true);updateToolbar()}
function init(){planningGroup=L.featureGroup().addTo(MAP());MAP().on('click',onMapClick);$('startPlanningDrawBtn').addEventListener('click',startDrawing);$('finishPlanningDrawBtn').addEventListener('click',finishDrawing);$('editPlanningGeometryBtn').addEventListener('click',editTerrainGeometry);$('deletePlanningFeatureBtn').addEventListener('click',deleteTerrainFeature);$('clearPlanningFeaturesBtn').addEventListener('click',clearTerrainFeatures);$('savePlanningFeatureBtn').addEventListener('click',saveFeatureDetails);$('planningDrivewayFeature').addEventListener('change',()=>{fillTerrainDrivewayInputs();renderTerrainReadouts()});$('planningBuildSiteFeature').addEventListener('change',()=>{fillBuildSiteInputs();renderTerrainReadouts()});$('saveDrivewayAnalysisBtn').addEventListener('click',saveTerrainDriveway);$('saveBuildSiteAnalysisBtn').addEventListener('click',saveBuildSite);$('closeSitePlanningBtn').addEventListener('click',closeSitePlanning);const priorOpen=window.openProperty;window.openProperty=function(id){priorOpen(id);addDossierPlanning(id)};window.openSitePlanning=openSitePlanning}
document.addEventListener('DOMContentLoaded',init);
document.addEventListener('DOMContentLoaded',()=>{setToolbarCollapsed(localStorage.getItem(toolbarKey())==='1');$('togglePlanningToolbarBtn')?.addEventListener('click',()=>setToolbarCollapsed(!$('planningMapToolbar').classList.contains('collapsed')));$('planningMapToolbar')?.querySelectorAll('[data-planning-tool]').forEach(button=>button.addEventListener('click',()=>selectToolbarTool(button.dataset.planningTool)));$('planningCancelDrawBtn')?.addEventListener('click',cancelDrawing);$('planningUndoPointBtn')?.addEventListener('click',undoPoint);$('planningUndoEditBtn')?.addEventListener('click',undoPlanningEdit);$('planningRedoEditBtn')?.addEventListener('click',redoPlanningEdit);$('planningToolbarFinishDrawBtn')?.addEventListener('click',finishDrawing);$('planningDeleteSelectedBtn')?.addEventListener('click',deleteTerrainFeature);$('planningConceptSelect')?.addEventListener('change',event=>switchConcept(event.target.value));$('createPlanningConceptBtn')?.addEventListener('click',()=>conceptAction('create'));$('duplicatePlanningConceptBtn')?.addEventListener('click',()=>conceptAction('duplicate'));$('renamePlanningConceptBtn')?.addEventListener('click',()=>conceptAction('rename'));$('archivePlanningConceptBtn')?.addEventListener('click',()=>conceptAction('archive'));$('saveUtilityAnalysisBtn')?.addEventListener('click',saveUtility);$('requestElevationProfileBtn')?.addEventListener('click',requestTerrainElevation);$('planningCompareRouteA')?.addEventListener('change',renderTerrainComparison);$('planningCompareRouteB')?.addEventListener('change',renderTerrainComparison);$('planningPreferredRoute')?.addEventListener('change',renderTerrainComparison);$('savePreferredDrivewayBtn')?.addEventListener('click',choosePreferredDriveway);window.addEventListener('pagehide',flushPlanSave);document.addEventListener('keydown',event=>{if(!activePropertyId)return;const key=event.key.toLowerCase(),shortcut=event.ctrlKey||event.metaKey;if(shortcut&&(key==='z'||key==='y')){event.preventDefault();if(key==='y'||event.shiftKey)redoPlanningEdit();else if(drawing)undoPoint();else undoPlanningEdit();return}if(event.key==='Escape'){event.preventDefault();if(drawing)cancelDrawing();else if(selectedFeatureId){selectedFeatureId='';clearVertices();renderFeatures();status('Planning feature deselected.')}}else if(event.key==='Enter'&&drawing){event.preventDefault();finishDrawing()}else if(key==='t'&&!event.ctrlKey&&!event.metaKey&&!event.altKey){event.preventDefault();setToolbarCollapsed(!$('planningMapToolbar').classList.contains('collapsed'))}})});
window.OTPlanning={DRIVEWAY_COST_CONFIG,BUILD_SITE_COST_CONFIG,UTILITY_COST_CONFIG,estimateDriveway,estimateBuildSite,estimateUtility,normalizePlan,generateParcelCandidates,measureLineFeet:lineFeet,measurePolygonAcres:polygonAcres,elevationProfileNeedsRefresh:(routeCoordinates,profile)=>!profile?.success||profile?.stale||profile.geometryFingerprint!==(window.OTElevation?.geometryFingerprint?.(routeCoordinates||[])||''),open:openSitePlanning,close:closeSitePlanning,flush:flushPlanSave,isActiveForProperty:id=>String(activePropertyId)===String(id),closeForProperty:id=>{if(String(activePropertyId)===String(id))closeSitePlanning()}};
})();
