(function(){
'use strict';
let points={};
const $=id=>document.getElementById(id);
const fmt=(pt)=>pt&&Number.isFinite(pt.lat)&&Number.isFinite(pt.lng)?`${pt.lat.toFixed(6)}, ${pt.lng.toFixed(6)}`:'';
function parseCoordinates(text){
 text=String(text||'').trim();
 const patterns=[/@(-?\d{1,2}\.\d+),(-?\d{1,3}\.\d+)/,/!3d(-?\d{1,2}\.\d+)!4d(-?\d{1,3}\.\d+)/,/q=(-?\d{1,2}\.\d+),(-?\d{1,3}\.\d+)/,/^\s*(-?\d{1,2}\.\d+)\s*,\s*(-?\d{1,3}\.\d+)\s*$/];
 for(const re of patterns){const m=text.match(re);if(m){const lat=Number(m[1]),lng=Number(m[2]);if(lat>=-90&&lat<=90&&lng>=-180&&lng<=180)return {lat,lng}}}
 return null;
}
function validUsPoint(lat,lng){return Number.isFinite(lat)&&Number.isFinite(lng)&&!(Math.abs(lat)<0.0001&&Math.abs(lng)<0.0001)&&lat>=18&&lat<=72&&lng>=-180&&lng<=-66}
function currentPin(){const el=$('pinReadout'),lat=Number(el?.dataset.lat),lng=Number(el?.dataset.lng);return validUsPoint(lat,lng)?{lat,lng}:null}
function sync(){if($('referenceCoords'))$('referenceCoords').value=fmt(points.reference);if($('homesiteCoords'))$('homesiteCoords').value=fmt(points.homesite);if($('entranceCoords'))$('entranceCoords').value=fmt(points.entrance)}
function resetForm(){points={};sync();if($('locationConfidence'))$('locationConfidence').value='review';['costDrivewayFeet','costClearingAcres','costElectricFeet'].forEach(id=>{if($(id))$(id).value=0});if($('costExcavation'))$('costExcavation').value='unknown';if($('costWell')){$('costWell').checked=false;$('costWell').dataset.importedState='unknown'}if($('costSeptic')){$('costSeptic').checked=false;$('costSeptic').dataset.importedState='unknown'}updateCost()}
function loadProperty(p){points={...(p.points||{}),reference:(p.points?.reference||{lat:Number(p.lat),lng:Number(p.lng)})};sync();if($('locationConfidence'))$('locationConfidence').value=p.locationConfidence||'review';const c=p.developmentCost||{};if($('costDrivewayFeet'))$('costDrivewayFeet').value=c.drivewayFeet||0;if($('costClearingAcres'))$('costClearingAcres').value=c.clearingAcres||0;if($('costElectricFeet'))$('costElectricFeet').value=c.electricFeet||0;if($('costExcavation'))$('costExcavation').value=c.excavation||'unknown';if($('costWell')){$('costWell').checked=c.well===true||c.well==='allowance';$('costWell').dataset.importedState=String(c.well||'unknown')}if($('costSeptic')){$('costSeptic').checked=c.septic===true||c.septic==='allowance';$('costSeptic').dataset.importedState=String(c.septic||'unknown')}updateCost()}
function setReferencePoint(lat,lng){lat=Number(lat);lng=Number(lng);if(Number.isFinite(lat)&&Number.isFinite(lng)){points.reference={lat,lng};sync()}}
function readPoints(){const cp=currentPin();return {...points,reference:points.reference||cp}}
function readCostInputs(){const state=id=>{const input=$(id);if(input?.checked)return 'allowance';const retained=input?.dataset.importedState;return ['existing-unverified','not-needed-existing-service'].includes(retained)?retained:'unknown'};return {drivewayFeet:Number($('costDrivewayFeet')?.value)||0,clearingAcres:Number($('costClearingAcres')?.value)||0,electricFeet:Number($('costElectricFeet')?.value)||0,excavation:$('costExcavation')?.value||'unknown',well:state('costWell'),septic:state('costSeptic')}}
function estimateCost(c){c=c||{};const inputs={drivewayFeet:Number(c.drivewayFeet)||0,clearingAcres:Number(c.clearingAcres)||0,electricFeet:Number(c.electricFeet)||0},unknown=[],items=[];const add=(key,label,value,known)=>{if(known){items.push({key,label,value});return value}unknown.push(label);return 0};const driveway=add('driveway','driveway length',inputs.drivewayFeet*32,inputs.drivewayFeet>0),clearing=add('clearing','clearing scope',inputs.clearingAcres*6500,inputs.clearingAcres>0),electric=add('electric','electric extension',inputs.electricFeet*18,inputs.electricFeet>0),excavation=add('excavation','excavation / rock',({light:12000,moderate:30000,heavy:65000}[c.excavation]||0),['light','moderate','heavy'].includes(c.excavation)),well=c.well==='not-needed-existing-service'?0:add('well',c.well==='existing-unverified'?'water connection / well verification':'well',c.well===true||c.well==='allowance'?16000:0,c.well===true||c.well==='allowance'),septic=c.septic==='not-needed-existing-service'?0:add('septic',c.septic==='existing-unverified'?'septic / sewer inspection contingency':'septic',c.septic===true||c.septic==='allowance'?18000:0,c.septic===true||c.septic==='allowance'),subtotal=items.reduce((total,item)=>total+item.value,0),contingency=Math.round(subtotal*.15);return {driveway,clearing,electric,excavation,well,septic,items,unknown,subtotal,contingency,total:subtotal+contingency} }
function money(value){return Number(value).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}
function updateCost(){const est=estimateCost(readCostInputs()),out=$('costEstimateReadout');if(out)out.innerHTML=`<b>Priced subtotal:</b> ${money(est.subtotal)}${est.items.length?` (${est.items.map(item=>item.label).join(', ')})`:''}<br><b>15% contingency:</b> ${money(est.contingency)}<br><b>Preliminary priced scope:</b> <span class="cost-total">${money(est.total)}</span>${est.unknown.length?`<br><span class="small">Unpriced / unknown: ${est.unknown.join(', ')}. These items are not assumed to cost $0.</span>`:''}`}
function confidenceLabel(v){return v==='verified'?'User confirmed':v==='high'?'High confidence':v==='needs-pin'?'Needs verification':v==='review'?'Approximate / review':'Review'}
function prepareCostForm(){const excavation=$('costExcavation');if(excavation&&!Array.from(excavation.options).some(option=>option.value==='unknown')){const option=document.createElement('option');option.value='unknown';option.textContent='Unknown / not priced';excavation.insertBefore(option,excavation.firstChild)};[['costWell',' Include well allowance'],['costSeptic',' Include septic allowance']].forEach(([id,label])=>{const input=$(id);if(input?.nextSibling?.nodeType===3)input.nextSibling.nodeValue=label})}
function scoreReasons(p){const r=[];const d=p.development||{};if(d.driveway==='none')r.push('− No driveway cut materially increases access cost.');else if(d.driveway==='existing')r.push('+ Existing usable driveway improves readiness.');if((p.scores?.Infrastructure||0)>=75)r.push('+ Confirmed infrastructure materially lowers site-development risk.');else if((p.scores?.Infrastructure||50)<45)r.push('− Limited confirmed infrastructure increases cost and uncertainty.');if(d.homesite==='pad')r.push('+ Prepared pad reduces excavation uncertainty.');else if(d.homesite==='steep')r.push('− No clear homesite or steep terrain reduces buildability.');if(d.utilities==='extension'||d.utilities==='offgrid')r.push('− Utility extension risk reduces value.');if(p.terrain){if(p.terrain.maxSlopePct>25)r.push('− Steep sampled slopes suggest substantial grading or retaining work.');else if(p.terrain.maxSlopePct<12)r.push('+ Terrain sample is comparatively favorable near the analysis point.')}if((p.acres||0)>=25)r.push('+ Acreage supports privacy and recreation goals.');return r.slice(0,6)}
function recommendation(p,cost){let s=p.score||50;if(cost.items?.length&&cost.total>150000)s-=8;else if(cost.items?.length&&cost.total<75000)s+=3;if(p.locationConfidence==='needs-pin')s-=10;return s>=82?'Strong candidate':s>=70?'Worth serious review':s>=58?'Conditional candidate':'Low priority'}
function buildIntelligence(p){const c=estimateCost(p.developmentCost||{}),rec=recommendation(p,c),conf=p.locationConfidence||'review',pts=p.points||{},reasons=scoreReasons(p);const decisionHtml=`<div class="section decision-card"><span class="decision-badge">${rec}</span><h3>Land-intelligence decision card</h3><p>${reasons[0]||'Add development and terrain facts to strengthen the recommendation.'}</p><span class="confidence-pill ${conf}">Location: ${confidenceLabel(conf)}</span></div>`;const cards=[['Parcel reference',pts.reference||{lat:p.lat,lng:p.lng}],['Primary homesite',pts.homesite],['Driveway entrance',pts.entrance]].map(([n,v])=>`<div class="point-card"><b>${n}</b><span>${v?fmt(v):'Not set'}</span></div>`).join('');const pointsHtml=`<div class="section"><h3>Precision locations</h3><div class="point-grid">${cards}</div><div class="small">Terrain analysis uses the primary homesite when one is saved; otherwise it uses the parcel reference.</div></div>`;const costHtml=`<div class="section"><h3>Development-cost screen</h3><div class="kpis"><div class="kpi"><b>${c.total.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}</b><span>Working total</span></div><div class="kpi"><b>${c.excavation.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}</b><span>Excavation allowance</span></div><div class="kpi"><b>15%</b><span>Contingency included</span></div></div></div>`;const explanationsHtml=`<div class="section"><h3>Why it scores this way</h3><div class="explain-list">${(reasons.length?reasons:['Complete development inputs and terrain analysis for explainable scoring.']).map(x=>`<div class="explain-item">${x}</div>`).join('')}</div></div>`;return {decisionHtml,pointsHtml,costHtml,explanationsHtml}}
function importGooglePin(){const text=$('googleMapPinInput')?.value||'',pt=parseCoordinates(text),msg=$('locationMessage');if(!pt){msg.textContent='No usable coordinates were found. In Google Maps, right-click the exact spot and click the coordinate pair to copy it, then paste it here.';return}if(!validUsPoint(pt.lat,pt.lng)){msg.textContent='Those coordinates are invalid or outside the supported U.S. area. No pin was changed.';return}if(typeof setAddPin==='function'&&setAddPin(pt.lat,pt.lng,'Google Maps coordinates — verified by user')===false){msg.textContent='The coordinates failed the location safety check. No pin was changed.';return}points.reference={...pt};if($('locationConfidence'))$('locationConfidence').value='verified';sync();msg.textContent=`Imported ${fmt(pt)} as a user-verified reference point. Save the property when the satellite placement is correct.`}
document.addEventListener('DOMContentLoaded',()=>{
 prepareCostForm();
 $('importGooglePinBtn')?.addEventListener('click',importGooglePin);
 $('useCurrentAsHomesiteBtn')?.addEventListener('click',()=>{const p=currentPin();if(!p)return $('locationMessage').textContent='Place the current property pin first.';points.homesite={...p};sync();$('locationMessage').textContent='Primary homesite saved from the current pin.'});
 $('useCurrentAsEntranceBtn')?.addEventListener('click',()=>{const p=currentPin();if(!p)return $('locationMessage').textContent='Place the current property pin first.';points.entrance={...p};sync();$('locationMessage').textContent='Driveway entrance saved from the current pin.'});
 ['costDrivewayFeet','costClearingAcres','costElectricFeet','costExcavation','costWell','costSeptic'].forEach(id=>$(id)?.addEventListener('input',updateCost));
 resetForm();
});
window.OTPrecision={resetForm,loadProperty,setReferencePoint,readPoints,readCostInputs,estimateCost,getTerrainPoint:()=>points.homesite||points.reference||currentPin(),buildIntelligence,parseCoordinates};
})();
(()=>{const priorBuild=window.OTPrecision?.buildIntelligence;if(!priorBuild)return;window.OTPrecision.buildIntelligence=p=>{const result=priorBuild(p),cost=window.OTPrecision.estimateCost(p.developmentCost||{}),items=cost.items.map(item=>`<div class="estimate"><b>${item.label}</b><span>${money(item.value)}</span></div>`).join('')||'<div class="small">No site-development work has been priced yet.</div>',costHtml=`<div class="section"><h3>Development-cost screen</h3><div class="estimate-grid">${items}</div><div class="terrain-dossier"><b>Priced subtotal:</b> ${money(cost.subtotal)}<br><b>15% contingency:</b> ${money(cost.contingency)}<br><b>Preliminary priced scope:</b> ${money(cost.total)}${cost.unknown.length?`<br><span class="small">Unpriced / unknown: ${cost.unknown.join(', ')}. These items are not assumed to cost $0.</span>`:''}<br><span class="small">Preliminary planning figures only; confirm contractor pricing, utility availability, soils, permits, drainage, and site conditions.</span></div></div>`;return {...result,costHtml}}})();
(()=>{const originalBuild=window.OTPrecision?.buildIntelligence;if(!originalBuild)return;window.OTPrecision.buildIntelligence=p=>{const result=originalBuild(p),investment=p.investment||{},score=Number(p.scores?.InvestmentFlexibility??50);const reasons=[];if(investment.dwellingCondition==='livable-ready')reasons.push('+ Existing dwelling is marked livable now, supporting immediate occupancy and reuse.');else if(investment.dwellingCondition==='needs-renovation')reasons.push('− Existing dwelling needs renovation before full use.');if(investment.utilities==='fully-onsite')reasons.push('+ Existing utilities improve immediate-use flexibility.');if(investment.rentalPotential==='likely'||investment.rentalPotential==='established')reasons.push('+ Rental or guest-use potential improves income and resale flexibility.');if(investment.subdivisionPotential==='strong'||investment.subdivisionPotential==='possible')reasons.push('+ Lot-split potential improves future exit flexibility.');if(investment.occupyDuringBuild==='yes')reasons.push('+ Onsite occupancy while building reduces transition risk.');if(!reasons.length)reasons.push(score>=70?'+ Investment flexibility is supported by the recorded property type and facts.':'Add dwelling, utility, rental, or subdivision facts to refine flexibility.');const investmentHtml=`<div class="section"><h3>Investment &amp; flexibility</h3><div class="kpis"><div class="kpi"><b>${score}/100</b><span>15% of overall score</span></div><div class="kpi"><b>${p.propertyType||'Raw land'}</b><span>Property type</span></div></div><div class="explain-list">${reasons.map(reason=>`<div class="explain-item">${reason}</div>`).join('')}</div></div>`;return {...result,explanationsHtml:`${investmentHtml}${result.explanationsHtml}`}}})();
