(()=>{
'use strict';
const $=id=>document.getElementById(id),KEY='ot-properties',SNAP='ot-recovery-snapshots-v1',DELETED='ot-deleted-property-ids',COUNT='ot-properties-last-known-count';let found=[];
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const propertyLike=value=>value&&typeof value==='object'&&!Array.isArray(value)&&((value.id&&('lat'in value||'address'in value))||(value.address&&('price'in value||'acres'in value||'lat'in value)));
const exactKey=value=>`${String(value.id||'').trim().toLowerCase()}|${String(value.address||'').replace(/\s+/g,' ').trim().toLowerCase()}`;
function parse(value){try{return JSON.parse(value)}catch{return null}}
function collect(value,source,out,depth=0){if(depth>4||value==null)return;if(Array.isArray(value)){value.forEach(item=>{if(propertyLike(item))out.push({record:item,source});else collect(item,source,out,depth+1)});return}if(typeof value==='object'){if(propertyLike(value)){out.push({record:value,source});return}Object.entries(value).forEach(([key,item])=>{if(key==='state'&&item&&typeof item==='object'){const raw=item[KEY];if(raw){const records=parse(raw);collect(records,`${source} snapshot`,out,depth+1)}}else collect(item,source,out,depth+1)})}}
function tombstones(){const ids=parse(localStorage.getItem(DELETED)||'[]');return new Set(Array.isArray(ids)?ids.map(String):[])}
function scan(){const results=[];[...Object.keys(localStorage)].filter(key=>key.startsWith('ot-')||/turtle|propert/i.test(key)).forEach(key=>collect(parse(localStorage.getItem(key)),key,results));const groups=new Map(),current=window.OTPropertyStore?.getProperty?[]:[];results.forEach(item=>{const key=exactKey(item.record);if(!key||key==='|')return;const old=groups.get(key);if(!old||JSON.stringify(item.record).length>JSON.stringify(old.record).length)groups.set(key,item)});const deleted=tombstones();found=[...groups.values()].map((item,index)=>({...item,id:`recovery-${index}`,deleted:deleted.has(String(item.record.id||'')),confidence:item.source===KEY?'current':'recoverable',alreadyCurrent:false}));const currentRaw=parse(localStorage.getItem(KEY)||'[]');const currentKeys=new Set((Array.isArray(currentRaw)?currentRaw:[]).map(exactKey));found.forEach(item=>item.alreadyCurrent=currentKeys.has(exactKey(item.record)));return found}
function render(){const panel=$('lostRecoveryPanel');if(!panel)return;const rows=scan();panel.hidden=false;panel.innerHTML=rows.length?`<div class="small">Found ${rows.length} property-like record${rows.length===1?'':'s'} in this origin. Duplicates already in the canonical store are not selected.</div>${rows.map(item=>`<label class="recovery-snapshot"><input type="checkbox" data-recovery-id="${item.id}" ${item.alreadyCurrent?'disabled':''}><div><b>${esc(item.record.address||item.record.name||item.record.id||'Unnamed property')}</b><span>${item.record.acres||'—'} ac · ${item.record.price?Number(item.record.price).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}):'price unknown'} · ${esc(item.source)} · ${item.deleted?'Previously deleted':'Recoverable'}</span></div></label>`).join('')}<div class="settings-actions"><button id="restoreSelectedRecoveryBtn" class="secondary" type="button">Restore selected</button><button id="restoreNonDuplicateRecoveryBtn" class="secondary outline" type="button">Restore all non-duplicates</button></div>`:'<div class="recovery-empty">No property-like records were found in this browser origin. Import a full backup exported from the prior origin if the properties were saved under file://, another localhost port, 127.0.0.1, or a hosted URL.</div>';$('restoreSelectedRecoveryBtn')?.addEventListener('click',()=>restore(false));$('restoreNonDuplicateRecoveryBtn')?.addEventListener('click',()=>restore(true))}
function merge(current,candidate){const merged={...candidate,...current};for(const key of ['notes','listing','source','zillowId','mls'])if(!merged[key])merged[key]=candidate[key]||current[key]||'';merged.pros=[...new Set([...(candidate.pros||[]),...(current.pros||[])])];merged.cons=[...new Set([...(candidate.cons||[]),...(current.cons||[])])];merged.activityHistory=[...(candidate.activityHistory||[]),...(current.activityHistory||[])];merged.locationAudit=[...(candidate.locationAudit||[]),...(current.locationAudit||[])];merged.sitePlanning=current.sitePlanning||candidate.sitePlanning;if(current.locationVerification?.status==='verified'){merged.lat=current.lat;merged.lng=current.lng;merged.locationVerification=current.locationVerification}else if(candidate.locationVerification?.status==='verified'){merged.lat=candidate.lat;merged.lng=candidate.lng;merged.locationVerification=candidate.locationVerification}return merged}
function restore(all){const selected=all?found.filter(item=>!item.alreadyCurrent&&!item.deleted):found.filter(item=>$(`input[data-recovery-id="${item.id}"]`)?.checked);if(!selected.length){alert('Select one or more non-duplicate records first. Previously deleted records require explicit selection.');return}if(!confirm(`Restore ${selected.length} selected record${selected.length===1?'':'s'}? Current data will be protected in a recovery snapshot first.`))return;const current=parse(localStorage.getItem(KEY)||'[]');const list=Array.isArray(current)?current:[];selected.forEach(item=>{const index=list.findIndex(record=>exactKey(record)===exactKey(item.record));if(index>=0)list[index]=merge(list[index],item.record);else list.push(item.record)});if(window.OTPropertyStore?.replaceAll(list,'Lost-property recovery')){alert('Recovery saved. Review restored records before making further edits.');render()}}
function latestSafe(){const entries=parse(localStorage.getItem(SNAP)||'[]');return Array.isArray(entries)?entries.find(entry=>Array.isArray(parse(entry?.state?.[KEY]||''))&&parse(entry.state[KEY]).length):null}
function detect(){const current=parse(localStorage.getItem(KEY)||'[]'),count=Array.isArray(current)?current.length:0,previous=Number(localStorage.getItem(COUNT)||0),safe=latestSafe(),safeCount=Number(safe?.propertyCount||parse(safe?.state?.[KEY]||'[]')?.length||0),priorCount=Math.max(previous,safeCount);if(priorCount>count){const alertBox=$('propertyLossAlert');if(!alertBox)return;$('propertyLossText').textContent=`Current store has ${count} properties; a prior safe record indicates ${priorCount}.`;alertBox.hidden=false}}
function validate(){const current=parse(localStorage.getItem(KEY)||'[]'),entries=parse(localStorage.getItem(SNAP)||'[]'),ids=new Set(),issues=[];(Array.isArray(current)?current:[]).forEach(record=>{if(!record?.id)issues.push('record missing ID');else if(ids.has(String(record.id)))issues.push(`duplicate ID ${record.id}`);else ids.add(String(record.id));if(!Number.isFinite(Number(record?.lat))||!Number.isFinite(Number(record?.lng)))issues.push(`invalid coordinates for ${record?.id||'record'}`)});const usage=Object.keys(localStorage).filter(key=>key.startsWith('ot-')).reduce((sum,key)=>sum+(localStorage.getItem(key)||'').length,0);$('storageValidationPanel').textContent=`Canonical properties: ${Array.isArray(current)?current.length:0} · Snapshots: ${Array.isArray(entries)?entries.length:0} · Storage: ${(usage/1024).toFixed(1)} KB · Last verified save: ${localStorage.getItem('ot-properties-last-verified-save')||'none'}${issues.length?` · Issues: ${issues.join('; ')}`:' · Stored data is structurally valid.'}`}
function restoreLatest(){const entry=latestSafe();if(!entry)return alert('No valid recovery snapshot is available.');const records=parse(entry.state[KEY]);if(!confirm(`Restore the latest safe snapshot with ${records.length} properties? Current data will first be protected.`))return;window.OTPropertyStore?.replaceAll(records,'Restore latest safe snapshot');$('propertyLossAlert').hidden=true}
function init(){ $('recoverLostBtn')?.addEventListener('click',render);$('validateStoredBtn')?.addEventListener('click',validate);$('createSnapshotBtn')?.addEventListener('click',()=>{window.OTCreateRecoverySnapshot?.('Manual snapshot');$('dataMessage').textContent='Recovery snapshot created.'});$('reviewLossRecoveryBtn')?.addEventListener('click',()=>{document.getElementById('settingsBtn')?.click();render()});$('restoreLatestSafeBtn')?.addEventListener('click',restoreLatest);$('continueWithoutRestoreBtn')?.addEventListener('click',()=>$('propertyLossAlert').hidden=true);detect()}
document.addEventListener('DOMContentLoaded',init);window.OTRecovery={scan,validate,detect};
})();
