/* Optional East Tennessee recreation and public-land overlays. No property writes. */
(()=>{
'use strict';
const STATE_KEY='ot-recreation-layer-state-v1';
const PAD_US='https://services.arcgis.com/v01gqwM5QqNysAAi/arcgis/rest/services/Fee_Managers_PADUS/FeatureServer/0/query';
const NHD_WMS='https://hydro.nationalmap.gov/arcgis/services/NHDPlus_HR/MapServer/WMSServer';
const DEFAULT_STATE={federal:false,state:false,atv:false,lakes:false,outdoor:false};
const DESTINATIONS=[
 {id:'windrock',group:'atv',name:'Windrock Park',kind:'SxS / ATV recreation',lat:36.0811,lng:-84.3330},
 {id:'royal-blue',group:'atv',name:'Ride Royal Blue',kind:'SxS / ATV recreation',lat:36.4789,lng:-84.2397},
 {id:'brimstone',group:'atv',name:'Brimstone Recreation',kind:'SxS / ATV recreation',lat:36.4093,lng:-84.5481},
 {id:'tackett-creek',group:'atv',name:'Tackett Creek trail area',kind:'SxS / ATV destination point',lat:36.5327,lng:-84.1708},
 {id:'norris',group:'lakes',name:'Norris Lake',kind:'Lake / water recreation',lat:36.2920,lng:-84.0910},
 {id:'douglas',group:'lakes',name:'Douglas Lake',kind:'Lake / water recreation',lat:35.9750,lng:-83.5150},
 {id:'tellico',group:'lakes',name:'Tellico Reservoir',kind:'Lake / water recreation',lat:35.6500,lng:-84.2400},
 {id:'fort-loudoun',group:'lakes',name:'Fort Loudoun Lake',kind:'Lake / water recreation',lat:35.7900,lng:-84.1750},
 {id:'watts-bar',group:'lakes',name:'Watts Bar Lake',kind:'Lake / water recreation',lat:35.7600,lng:-84.6500},
 {id:'clingmans-dome',group:'outdoor',name:'Kuwohi (Clingmans Dome)',kind:'Major hiking destination',lat:35.5629,lng:-83.4985},
 {id:'fall-creek-falls',group:'outdoor',name:'Fall Creek Falls State Park',kind:'State park / waterfall',lat:35.6627,lng:-85.3567},
 {id:'cades-cove',group:'outdoor',name:'Cades Cove',kind:'National Park destination',lat:35.6059,lng:-83.7813}
];
let groups={},markerGroups={},state={...DEFAULT_STATE},federalLoaded='',stateLoaded='',activeId='';
const $=id=>document.getElementById(id);
const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const finite=value=>Number.isFinite(Number(value));
const clone=value=>value==null?value:structuredClone(value);
function readState(){try{return {...DEFAULT_STATE,...JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}}catch{return {...DEFAULT_STATE}}}
function saveState(){try{const payload=JSON.stringify(state);window.OTSaveReliability?.preflightStorageWrite?.(localStorage,{[STATE_KEY]:payload});localStorage.setItem(STATE_KEY,payload)}catch(error){setStatus(`Layer choices could not be saved: ${error.message||'browser storage unavailable'}`)}}
function setStatus(message){const target=$('recreationLayerStatus');if(target)target.textContent=message||'Optional layers load only when selected.'}
function boundsKey(){const bounds=window.OT_MAP?.getBounds?.();if(!bounds)return '';return [bounds.getWest(),bounds.getSouth(),bounds.getEast(),bounds.getNorth()].map(value=>Number(value).toFixed(2)).join(',')}
function queryUrl(managerType){const bounds=window.OT_MAP?.getBounds?.();if(!bounds)return '';const url=new URL(PAD_US);url.searchParams.set('f','geojson');url.searchParams.set('where',`Mang_Type='${managerType}'`);url.searchParams.set('geometry',`${bounds.getWest()},${bounds.getSouth()},${bounds.getEast()},${bounds.getNorth()}`);url.searchParams.set('geometryType','esriGeometryEnvelope');url.searchParams.set('inSR','4326');url.searchParams.set('spatialRel','esriSpatialRelIntersects');url.searchParams.set('outFields','Mang_Name,Unit_Nm,Mang_Type,Pub_Access');url.searchParams.set('returnGeometry','true');url.searchParams.set('outSR','4326');url.searchParams.set('geometryPrecision','5');url.searchParams.set('resultRecordCount','250');return url.toString()}
async function fetchPublic(groupName,managerType){const group=groups[groupName],key=boundsKey();if(!group||!key)return false;if(groupName==='federal'&&federalLoaded===key||groupName==='state'&&stateLoaded===key)return true;setStatus(`Loading ${groupName==='federal'?'national/public lands':'state parks, forests, and wildlife areas'}…`);try{const response=await fetch(queryUrl(managerType),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(data.error)throw new Error(data.error.message||'Provider error');group.clearLayers();L.geoJSON(data,{style:{color:groupName==='federal'?'#466f3b':'#8a6d28',weight:1.5,fillOpacity:.16},onEachFeature:(feature,layer)=>{const properties=feature.properties||{},name=properties.Unit_Nm||properties.Mang_Name||'Public land';layer.bindPopup(`<b>${safe(name)}</b><br>${groupName==='federal'?'National / federal public land':'Tennessee-managed public land'}<br><small>PAD-US mapped management area · access: ${safe(properties.Pub_Access||'verify')}</small>`)}}).eachLayer(layer=>group.addLayer(layer));if(groupName==='federal')federalLoaded=key;else stateLoaded=key;setStatus(`${group.getLayers().length} ${groupName==='federal'?'national/public-land':'state public-land'} area${group.getLayers().length===1?'':'s'} loaded for this map view.`);return true}catch(error){setStatus(`Public-land layer unavailable: ${error.message||'network or CORS failure'}. Existing property overlays were preserved.`);return false}}
function destinationPopup(item){return `<b>${safe(item.name)}</b><br>${safe(item.kind)}<br><button type="button" class="recreation-route-button" data-recreation-route="${safe(item.id)}">Get travel context</button><div class="recreation-route-result" data-recreation-result="${safe(item.id)}" aria-live="polite"></div>`}
function renderDestinations(groupName){const group=markerGroups[groupName]||groups[groupName];if(!group)return;group.clearLayers();if(groupName==='outdoor'&&window.OT_MAP?.getZoom?.()<9)return;DESTINATIONS.filter(item=>item.group===groupName).forEach(item=>{const marker=L.marker([item.lat,item.lng],{icon:L.divIcon({className:`recreation-destination-marker recreation-destination-${groupName}`,html:'',iconSize:[14,14],iconAnchor:[7,7]}),title:item.name,keyboard:true,riseOnHover:true}).bindPopup(destinationPopup(item));marker.on('add',()=>{const element=marker.getElement?.();if(element){element.setAttribute('role','button');element.setAttribute('aria-label',`${item.name} — ${item.kind}`)}});marker.addTo(group)})}
function propertyForRoute(){const id=window.OTMapWorkspace?.activePropertyId?.()||activeId;return window.OTPropertyStore?.getProperty?.(id)||null}
async function routeDestination(item,button){if(button.disabled)return;const property=propertyForRoute(),target=document.querySelector(`[data-recreation-result="${CSS.escape(item.id)}"]`);if(!target)return;if(!property||!finite(property.lat)||!finite(property.lng)){target.textContent='Open a property first to calculate travel context.';return}button.disabled=true;target.textContent='Calculating route…';try{const url=`https://router.project-osrm.org/route/v1/driving/${Number(property.lng)},${Number(property.lat)};${item.lng},${item.lat}?overview=false&steps=false`;const response=await fetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),route=data.routes?.[0];if(!route)throw new Error('No driving route returned');target.textContent=`${Math.round(route.duration/60)} min · ${(route.distance/1609.344).toFixed(1)} mi from ${property.name||property.address}` }catch(error){target.textContent=`Travel route unavailable: ${error.message||'routing service failed'}.` }finally{button.disabled=false}}
function toggle(name,enabled,{persist=true}={}){state[name]=!!enabled;const group=groups[name];if(!group)return;if(enabled){if(!window.OT_MAP.hasLayer(group))group.addTo(window.OT_MAP);if(name==='federal')fetchPublic(name,'FED');else if(name==='state')fetchPublic(name,'STAT');else renderDestinations(name)}else window.OT_MAP.removeLayer(group);if(persist)saveState()}
function parcelEnvelope(geometry){const polygons=geometry?.type==='Polygon'?[geometry.coordinates]:geometry?.type==='MultiPolygon'?geometry.coordinates:[],points=polygons.flat(2);if(!points.length)return null;return {west:Math.min(...points.map(point=>Number(point[0]))),south:Math.min(...points.map(point=>Number(point[1]))),east:Math.max(...points.map(point=>Number(point[0]))),north:Math.max(...points.map(point=>Number(point[1])))} }
async function assessAdjacency(record={},options={}){const bounds=parcelEnvelope(record.parcelGeometry);if(!bounds)return {adjacent:false,status:'unavailable',reason:'verified parcel geometry required'};const url=new URL(PAD_US);url.searchParams.set('f','geojson');url.searchParams.set('where',"Mang_Type IN ('FED','STAT')");url.searchParams.set('geometry',`${bounds.west},${bounds.south},${bounds.east},${bounds.north}`);url.searchParams.set('geometryType','esriGeometryEnvelope');url.searchParams.set('inSR','4326');url.searchParams.set('spatialRel','esriSpatialRelIntersects');url.searchParams.set('outFields','Mang_Name,Unit_Nm,Mang_Type');url.searchParams.set('returnGeometry','true');url.searchParams.set('outSR','4326');url.searchParams.set('geometryPrecision','6');url.searchParams.set('resultRecordCount','100');try{const response=await (options.fetchImpl||fetch)(url.toString(),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),match=(data.features||[]).find(feature=>window.OTLandConstraints?.geometriesIntersect?.(record.parcelGeometry,feature.geometry));if(!match)return {adjacent:false,status:'checked',provider:'USGS PAD-US',checkedAt:new Date().toISOString()};return {adjacent:true,status:'checked',provider:'USGS PAD-US',name:match.properties?.Unit_Nm||match.properties?.Mang_Name||'public land',managementType:match.properties?.Mang_Type||'',checkedAt:new Date().toISOString(),confidence:'mapped-boundary-intersection',note:'Direct geometry intersection in PAD-US; verify title, access, and exact boundary conditions.'}}catch(error){return {adjacent:false,status:'unavailable',provider:'USGS PAD-US',checkedAt:new Date().toISOString(),reason:error.message||'provider unavailable'}}}
function setActiveProperty(id){activeId=String(id||'')}
function bindPopupRoute(event){const button=event.popup?.getElement?.()?.querySelector('[data-recreation-route]');if(!button||button.dataset.routeBound)return;button.dataset.routeBound='true';const activate=()=>{const item=DESTINATIONS.find(value=>value.id===button.dataset.recreationRoute);if(item)routeDestination(item,button)};button.addEventListener('pointerup',activate);button.addEventListener('click',activate)}
function install(){if(!window.OT_MAP||!window.L)return;groups={federal:L.featureGroup(),state:L.featureGroup(),atv:L.featureGroup(),lakes:L.featureGroup(),outdoor:L.featureGroup()};markerGroups={atv:groups.atv,lakes:groups.lakes,outdoor:groups.outdoor};state=readState();const lakeWater=L.tileLayer.wms(NHD_WMS,{layers:'9',format:'image/png',transparent:true,opacity:.42,attribution:'USGS NHDPlus HR'}),lakeMarkers=groups.lakes;groups.lakes=L.layerGroup([lakeWater,lakeMarkers]);for(const [id,name] of [['layerPublicFederal','federal'],['layerPublicState','state'],['layerAtvSxs','atv'],['layerRecreationLakes','lakes'],['layerOutdoorPois','outdoor']]){const input=$(id);if(!input)continue;input.checked=!!state[name];input.addEventListener('change',()=>toggle(name,input.checked));if(input.checked)toggle(name,true,{persist:false})}window.OT_MAP.on('moveend',()=>{if(state.federal)fetchPublic('federal','FED');if(state.state)fetchPublic('state','STAT');if(state.outdoor)renderDestinations('outdoor')});window.OT_MAP.on('popupopen',bindPopupRoute);setStatus('Optional layers load only when selected. Public lands use mapped PAD-US polygons; recreation destinations use points unless a reliable area boundary is available.')}
function runRegressionChecks(){const captured=[],fakeFetch=async()=>({ok:true,json:async()=>({features:[{properties:{Unit_Nm:'Fixture National Forest',Mang_Type:'FED'},geometry:{type:'Polygon',coordinates:[[[-84.1,35.1],[-84.0,35.1],[-84.0,35.2],[-84.1,35.2],[-84.1,35.1]]]}}]})}),record={parcelGeometry:{type:'Polygon',coordinates:[[[-84.08,35.12],[-84.04,35.12],[-84.04,35.16],[-84.08,35.16],[-84.08,35.12]]]}};return assessAdjacency(record,{fetchImpl:async(...args)=>{captured.push(args[0]);return fakeFetch()}}).then(result=>{const checks={allGroupsOptional:Object.values(DEFAULT_STATE).every(value=>value===false),authoritativePolygonProvider:/services\.arcgis\.com/.test(PAD_US),atvDestinationsArePoints:DESTINATIONS.filter(item=>item.group==='atv').every(item=>finite(item.lat)&&finite(item.lng)),majorLakesPresent:['Norris Lake','Douglas Lake','Tellico Reservoir','Fort Loudoun Lake','Watts Bar Lake'].every(name=>DESTINATIONS.some(item=>item.name===name)),adjacencyIsExactGeometryResult:result.adjacent===true&&result.name==='Fixture National Forest',boundedProviderQuery:captured.every(url=>/geometry=/.test(url))};return {passed:Object.values(checks).every(Boolean),checks,result}})}
window.OTRecreationLayers={STATE_KEY,PAD_US,NHD_WMS,DESTINATIONS,assessAdjacency,setActiveProperty,runRegressionChecks};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
