/* Smart Import 3.0 and Property Profile reliability UI. No startup persistence. */
(()=>{'use strict';
const workflow=window.OTPropertyWorkflow;
const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const factInputs={price:'addPrice',acres:'addAcres',beds:'addBeds',baths:'addBaths',sqft:'addSqft',homeType:'addPropertyType'};
let session=createSession(),refreshBusy=false;
function createSession(){return {parsed:null,importedCount:0,userEdited:new Set(),autoPopulated:new Set(),runResearch:true,runRoutes:true,scoreBefore:null,startedAt:new Date().toISOString()}}
function resetSession(){session=createSession();const text=document.getElementById('smartZillowFactsText');if(text)text.value='';updateSteps()}
function setStatus(text,state='working'){const element=document.getElementById('smartImportStatus');if(element){element.textContent=text;element.dataset.state=state}}
function setStep(name,state,label){const element=document.querySelector('[data-smart-step="'+name+'"]');if(!element)return;element.dataset.state=state;element.querySelector('span').textContent=label}
function updateSteps(){
 const address=document.getElementById('addAddress')?.value.trim(),pin=document.getElementById('pinReadout'),located=Number.isFinite(Number(pin?.dataset.lat))&&Number.isFinite(Number(pin?.dataset.lng));
 setStep('basics',address&&located?'complete':address?'partial':'pending',address&&located?'Ready':'Add address and confirm pin');
 setStep('zillow',session.parsed?'complete':'pending',session.parsed?session.importedCount+' facts ready':'Optional');
 setStep('research',session.runResearch?'queued':'skipped',session.runResearch?'Run after save':'Skipped');
 setStep('routes',session.runRoutes?'queued':'skipped',session.runRoutes?'Verify after save':'Skipped');
 setStep('save',address&&located?'ready':'pending',address&&located?'Review and save':'Waiting for basics')
}
function populateParsedFacts(parsed){
 const byField=Object.fromEntries((parsed.facts||[]).map(fact=>[fact.field,fact.value]));
 Object.entries(factInputs).forEach(([field,id])=>{const input=document.getElementById(id),value=byField[field];if(!input||value===undefined)return;const current=String(input.value||'').trim(),neutral=field==='homeType'?input.dataset.userTouched!=='true'&&(!current||/raw.land/i.test(current)):!current||Number(current)===0;if(!neutral)return;if(field==='homeType'){if(/single.family|residence|house|home/i.test(String(value)))input.value='existing-home-renovation';else return}else input.value=value;input.dataset.smartPopulated='true';session.autoPopulated.add(field)});
 const mapped=window.OTZillowFacts.applyToProperty({id:'working',name:'Working property',address:document.getElementById('addAddress')?.value||'Pending address',lat:35,lng:-84,propertyType:document.getElementById('addPropertyType')?.value||'raw-land',acres:Number(document.getElementById('addAcres')?.value)||0,price:Number(document.getElementById('addPrice')?.value)||0,beds:Number(document.getElementById('addBeds')?.value)||0,baths:Number(document.getElementById('addBaths')?.value)||0,sqft:Number(document.getElementById('addSqft')?.value)||0,fieldSources:{},development:{driveway:'unknown',homesite:'unknown',utilities:'unknown'},propertyIntelligence:{propertyProfile:{}}},parsed);
 if(mapped.property.propertyType&&document.getElementById('addPropertyType'))document.getElementById('addPropertyType').value=mapped.property.propertyType;
 const waterInput=document.getElementById('addWaterFeature'),waterValue=mapped.property.waterFeature;if(waterInput&&waterValue&&waterValue!=='Unknown'&&waterInput.value==='Unknown'&&[...waterInput.options].some(option=>option.value===waterValue)){waterInput.value=waterValue;session.autoPopulated.add('waterFeature')}
 const development=mapped.property.development||{};[['driveway','developmentDriveway'],['homesite','developmentHomesite'],['utilities','developmentUtilities']].forEach(([key,id])=>{const input=document.getElementById(id);if(input&&input.value==='unknown'&&development[key]&&development[key]!=='unknown'){input.value=development[key];session.autoPopulated.add('development.'+key)}});
 document.getElementById('recalcScoreBtn')?.click();return mapped
}
function parseZillow(){
 const text=document.getElementById('smartZillowFactsText')?.value.trim();if(!text){setStatus('Paste Zillow Facts & Features text, or skip this step.','partial');return}
 setStatus('Parsing Zillow facts?');try{const parsed=window.OTZillowFacts?.parse?.(text);if(!parsed?.found){setStatus('No supported Zillow Facts fields were recognized. Keep the text and review its format.','failed');return}session.parsed=parsed;session.importedCount=parsed.found;session.autoPopulated.clear();populateParsedFacts(parsed);setStatus(parsed.found+' Zillow facts are ready. They will be written once through the verified property save.','complete');updateSteps()}catch(error){setStatus('Zillow facts could not be parsed: '+(error.message||'check the pasted text')+'.','failed')}
}
function sourcePath(field){const profile=new Set(['residenceStatus','electric','waterSource','publicWater','well','septicOrSewer','septic','sewer','internet','cable','washerDryerHookups','driveway']);const land=new Set(['wooded','private','levelLand','slopedLand','rollingTerrain','clearedLand','pasture','mountainView','otherViews','creek','stream','spring','pond','river','waterfront','barn','stable','workshop','storageBuilding','shed','garage','detachedGarage','carport','deck','porch','coveredPorch','fencing','fireplace']);return profile.has(field)?'propertyIntelligence.propertyProfile.'+field:land.has(field)?'propertyIntelligence.zillowLand.'+field:field}
function mergeZillowFacts(record,text,userEdited=[],autoPopulated=[],{recordConflicts=true}={}){
 const parsed=typeof text==='string'?window.OTZillowFacts.parse(text):text;if(!parsed?.found)return {property:structuredClone(record),updated:[],conflicts:[],parsed:null};
 const base=structuredClone(record),priorCandidates=structuredClone(base.sourceCandidates||{}),protectedFields=new Set(userEdited),automatedFields=new Set(autoPopulated),sources={...(base.fieldSources||{})};
 const numericBlankFields=new Set(['beds','baths','fullBathrooms','sqft','structureArea','yearBuilt','acres','price','parkingSpaces','assessedValue','annualTaxes']);
 parsed.facts.forEach(fact=>{if(protectedFields.has(fact.field))return;const source=sources[sourcePath(fact.field)]||sources[fact.field],automatic=automatedFields.has(fact.field);if(automatic){delete sources[fact.field];delete sources[sourcePath(fact.field)]}if(numericBlankFields.has(fact.field)&&Number(base[fact.field])===0&&(automatic||window.OTSourcePrecedence?.normalizeSource?.(source)!=='user-confirmed'))delete base[fact.field]});for(const path of automatedFields){if(!path.startsWith('development.'))continue;const key=path.split('.')[1];base.development={...(base.development||{}),[key]:'unknown'};delete sources[path]}base.fieldSources=sources;
 const mapped=window.OTZillowFacts.applyToProperty(base,parsed);
 mapped.property.fieldSources={...(mapped.property.fieldSources||{})};parsed.facts.forEach(fact=>{if(automatedFields.has(fact.field)&&!protectedFields.has(fact.field))mapped.property.fieldSources[sourcePath(fact.field)]='zillow'});if(automatedFields.has('waterFeature'))mapped.property.fieldSources.waterFeature='zillow';if(!recordConflicts){if(Object.keys(priorCandidates).length)mapped.property.sourceCandidates=priorCandidates;else delete mapped.property.sourceCandidates;mapped.conflicts=[]}
 return {...mapped,parsed}
}
function preparePropertyForSave(property){
 if(!session.parsed)return property;session.scoreBefore=window.OTIntelligence?.getTurtleScore?.(property)?.total??null;
 const mapped=mergeZillowFacts(property,session.parsed,[...session.userEdited],[...session.autoPopulated]),next=mapped.property,now=new Date().toISOString();
 next.zillowFacts={current:{rawText:session.parsed.rawText,importedAt:now,parserVersion:session.parsed.version,sourceType:'Zillow',extractedFields:session.parsed.facts.map(fact=>fact.field),conflictSummary:mapped.conflicts.map(conflict=>conflict.field),lastSuccessfulAt:now},previous:property.zillowFacts?.current||null};
 next.activityHistory=[...(next.activityHistory||[]),{at:now,type:'smart-import-zillow',label:'Smart Import: '+mapped.updated.length+' Zillow fields updated'}];session.importedCount=session.parsed.found;return next
}
function countVerifiedRoutes(property){return window.OTRoutePolicy?.config?.scoredCategories?.filter(key=>window.OTRoutePolicy.activeRoute(property,key))?.length||0}
function showCompletion(property,summary,details={}){
 window.openProperty?.(property.id);setTimeout(()=>{const body=document.querySelector('#drawer .drawer-body');if(!body)return;body.querySelector('[data-smart-completion]')?.remove();const section=document.createElement('section');section.className='section smart-completion';section.dataset.smartCompletion='true';section.innerHTML='<h3>'+safe(summary.headline)+'</h3><ul>'+summary.items.map(item=>'<li>'+safe(item)+'</li>').join('')+'</ul><details><summary>Details</summary><p class="small">'+safe(details.text||'Technical import and source details remain available in More.')+'</p></details>';body.prepend(section)},80)
}
async function afterPropertySaved(id,wasExisting){
 const before=session.scoreBefore;setStatus('Saving verified property and completing selected steps?');
 try{
  let research={status:'skipped',completed:[],missing:[]};if(session.runResearch)research=await window.runPropertyResearch?.(id,{recalculate:false,reopen:false})||research;
  if(session.runRoutes)await window.refreshRoutes?.(id,{recalculate:false,reopen:false});
  const scoreSaved=window.recalculateSimplifiedScoreForProperty?.(id,{quiet:true})===true;window.OTWorkflowMetrics={...(window.OTWorkflowMetrics||{}),smartImportScoreRecalculations:Number(window.OTWorkflowMetrics?.smartImportScoreRecalculations||0)+1};
  const property=window.OTPropertyStore.getProperty(id);if(!property)throw new Error('The saved property could not be read back.');const record=window.OTIntelligenceRecord?.(property)||property,score=window.OTIntelligence?.getTurtleScore?.(record),review=window.OTIntelligence?.dataReview?.(record),routes=countVerifiedRoutes(property),partial=!scoreSaved||research.status==='partial'||routes<5||(review?.count||0)>0;
  const summary=workflow.completionSummary({zillow:session.importedCount,research:research.status,routes,scoreBefore:before,scoreAfter:score?.total,reviewCount:review?.count||0,partial});showCompletion(property,{...summary,headline:wasExisting?'Property updated':summary.headline},{text:(!scoreSaved?'The property is saved, but the score summary could not be verified. Retry Refresh Property Data. ':'')+(research.missing?.length?'Research still needs: '+research.missing.join(', ')+'. ':'')+(routes<5?'Some routes still need a user-confirmed pin or service response.':'All configured routes are present.')});setStatus(summary.headline,partial?'partial':'complete');return true
 }catch(error){const property=window.OTPropertyStore?.getProperty?.(id);if(property)showCompletion(property,{headline:'Property saved; follow-up incomplete',items:['The canonical property remains saved','Retry Refresh Property Data when ready']},{text:error.message||'A follow-up step could not complete.'});setStatus('Property saved; follow-up incomplete. '+(error.message||'Retry Refresh Property Data.'),'partial');return true
 }finally{session=createSession();updateSteps()}
}
async function refreshPropertyData(id){
 if(refreshBusy)return false;const original=window.OTPropertyStore?.getProperty(id);if(!original)return false;refreshBusy=true;
 const before=window.OTIntelligence?.getTurtleScore?.(window.OTIntelligenceRecord?.(original)||original)?.total??null;showCompletion(original,{headline:'Refreshing Property Data',items:['Reprocessing saved Zillow facts','Reviewing narrowed research scope','Refreshing unlocked routes','Score and Compare will update once']},{text:'User-confirmed values and locked routes remain protected.'});
 try{
  let candidate=structuredClone(original),zillow=0,zillowChanges=0,conflicts=0;const raw=candidate.zillowFacts?.current?.rawText;if(raw){const mapped=mergeZillowFacts(candidate,raw,[],[],{recordConflicts:false});candidate=mapped.property;zillow=mapped.parsed?.found||0;zillowChanges=mapped.updated.length;conflicts=mapped.conflicts.length}
  const assessed=workflow.applyResearchAssessment(candidate);candidate=assessed.property;
  const saved=window.OTPropertyStore.update(id,()=>candidate,'Refresh canonical property data',{recalculate:false});if(!saved){showCompletion(original,{headline:'Refresh failed',items:['The prior saved property was preserved']},{text:'Retry, or use the emergency export if browser storage is under pressure.'});return false}
  await window.refreshRoutes?.(id,{recalculate:false,reopen:false});window.recalculateSimplifiedScoreForProperty?.(id,{quiet:true});window.OTWorkflowMetrics={...(window.OTWorkflowMetrics||{}),refreshScoreRecalculations:Number(window.OTWorkflowMetrics?.refreshScoreRecalculations||0)+1};
  const property=window.OTPropertyStore.getProperty(id),record=window.OTIntelligenceRecord?.(property)||property,after=window.OTIntelligence?.getTurtleScore?.(record)?.total??null,review=window.OTIntelligence?.dataReview?.(record),routes=countVerifiedRoutes(property),partial=assessed.status==='partial'||routes<5||(review?.count||0)>0;
  const summary=workflow.completionSummary({zillow,zillowAction:'reprocessed',research:assessed.status,routes,scoreBefore:before,scoreAfter:after,reviewCount:review?.count||0,partial});summary.headline='Property Data refreshed';showCompletion(property,summary,{text:(zillow?zillow+' stored Zillow facts were reprocessed; '+zillowChanges+' canonical fields changed. ':'No stored Zillow Facts text was available. ')+(conflicts?conflicts+' new imported candidates differed from stronger saved values and were preserved for review. ':'')+(assessed.missing.length?'Research still needs: '+assessed.missing.join(', ')+'.':'No narrowed research gaps remain.')});return true
 }catch(error){const current=window.OTPropertyStore?.getProperty?.(id)||original;showCompletion(current,{headline:'Refresh incomplete',items:['The last verified property state was preserved','Retry when network and browser storage are available']},{text:error.message||'Property refresh could not complete.'});return false
 }finally{refreshBusy=false}
}
function optionHtml(value,label,current){return '<option value="'+safe(value)+'"'+(String(current)===String(value)?' selected':'')+'>'+safe(label)+'</option>'}
function profileEditor(property){
 const profile=workflow.profileForRecord(property),unknown=value=>value===null?'unknown':String(value),yesNo=[['unknown','Unknown'],['true','Yes'],['false','No']],condition=[['unknown','Unknown'],['livable','Livable / ready'],['minor-work','Needs minor work'],['major-rehabilitation','Needs major rehabilitation'],['unknown-condition','Condition unknown']],service=[['unknown','Unknown'],['verified','Verified installed'],['recorded','Recorded; verify'],['available','Available; not installed'],['none','Not present']],water=[['unknown','Unknown'],['verified-well','Verified well'],['public-water','Public water'],['verified-other','Other verified source'],['recorded','Recorded; verify'],['available','Available; not installed'],['none','Not present']],driveway=[['unknown','Unknown'],['year-round','Verified year-round'],['verified','Verified'],['recorded','Recorded; verify'],['limited','Limited / seasonal'],['none','Not present']],outbuildings=[['unknown','Unknown'],['garage','Garage'],['barn','Barn'],['workshop','Workshop'],['multiple','Multiple structures'],['none','None']],buildSite=[['unknown','Unknown'],['identified','Identified'],['likely','Likely'],['none-identified','None identified yet'],['not-viable','Not viable']],confidence=[['unknown','Unknown'],['high','High'],['medium','Medium'],['low','Low'],['not-viable','Not viable']],access=[['unknown','Unknown'],['independent','Independent access'],['shared-practical','Practical shared access'],['difficult','Difficult'],['not-feasible','Not feasible']],extension=[['unknown','Unknown'],['low','Low'],['moderate','Moderate'],['high','High'],['extreme','Extreme']],permission=[['unknown','Unknown'],['permitted','Permitted'],['likely','Likely; verify'],['restricted','Restricted'],['not-permitted','Not permitted']],mix=[['unknown','Unknown'],['mixed','Mixed wooded / open'],['mostly-wooded','Mostly wooded'],['mostly-open','Mostly open'],['featureless','Uniform / featureless']],slope=[['unknown','Unknown'],['mixed-moderate','Mixed / moderate slopes'],['recreational','Recreational slopes'],['steep-limiting','Steep / limiting'],['flat-open','Flat / open']],waterType=[['unknown','Unknown'],['none','None'],['seasonal-drainage','Seasonal drainage'],['creek','Creek'],['spring','Spring'],['pond','Pond'],['river','River frontage'],['multiple','Multiple features']],reliability=[['unknown','Unknown'],['verified-year-round','Verified year-round'],['likely','Likely'],['seasonal','Seasonal'],['unverified','Unverified']],flood=[['unknown','Unknown'],['none-known','None known'],['low','Low'],['moderate','Moderate'],['high','High']],flex=[['unknown','Unknown'],['excellent','Excellent'],['good','Good'],['difficult','Difficult'],['unlikely','Unlikely']],subdivision=[['unknown','Unknown'],['strong','Strong'],['possible','Possible'],['difficult','Difficult'],['unlikely','Unlikely']];
 const specs=[['existingResidencePresent','Existing residence present',yesNo],['existingResidenceLivable','Existing residence livable',yesNo],['residenceCondition','Residence condition',condition],['electric','Existing electric',service],['waterSource','Existing water source',water],['septicOrSewer','Existing septic or sewer',service],['internet','Existing internet',service],['driveway','Existing driveway',driveway],['outbuildings','Garage or outbuildings',outbuildings],['additionalBuildSite','Additional build site',buildSite],['additionalBuildSiteConfidence','Build-site confidence',confidence],['secondHomeBuildability','Physical second-home buildability',flex],['secondHomeAccess','Second-home access',access],['secondHomeSubdivisionPotential','Subdivision / independent future value',subdivision],['secondHomeFlexibility','Second Home Flexibility',flex],['utilityExtensionDifficulty','Second-home utility extension',extension],['multipleResidences','Multiple residences',permission],['woodedOpenMix','Wooded / open-land mix',mix],['slopeCharacter','Slope character',slope],['waterFeatureType','Water-feature type',waterType],['waterFeatureReliability','Water reliability',reliability],['waterFloodRisk','Water-feature flood risk',flood]];
 return '<summary>Property Profile</summary><p class="small">One verified Save writes these facts to the canonical property. User-confirmed values have highest precedence.</p><div class="scorecard-profile-grid">'+specs.map(spec=>'<label>'+safe(spec[1])+'<select data-profile="'+safe(spec[0])+'">'+spec[2].map(option=>optionHtml(option[0],option[1],unknown(profile[spec[0]]))).join('')+'</select></label>').join('')+'<label>Residence square feet<input data-profile="residenceSquareFootage" type="number" min="0" step="1" value="'+safe(profile.residenceSquareFootage??'')+'" placeholder="Optional"></label><label class="profile-note-wide">Second Home Flexibility note<input data-profile="secondHomeFlexibilityNote" maxlength="240" value="'+safe(profile.secondHomeFlexibilityNote)+'" placeholder="Access, terrain, utility, or subdivision context"></label></div>'
}
function decorateProfile(){
 const section=document.querySelector('#scorecardEditor .scorecard-profile');if(!section||section.dataset.profileV3)return;const id=document.querySelector('#drawer .prop-id')?.textContent.trim(),property=id&&window.OTPropertyStore?.getProperty(id);if(!property)return;section.dataset.profileV3='true';section.open=true;section.innerHTML=profileEditor(property)
}
function decorateDossierAndCompare(){
 const id=document.querySelector('#drawer .prop-id')?.textContent.trim(),property=id&&window.OTPropertyStore?.getProperty(id),body=document.querySelector('#drawer .drawer-body');if(property&&body&&!body.querySelector('[data-profile-summary-v3]')){const profile=workflow.profileForRecord(property),section=document.createElement('section');section.className='section profile-summary-v3';section.dataset.profileSummaryV3='true';section.innerHTML='<h3>Existing home & future flexibility</h3><div class="profile-summary-grid"><span><b>Residence:</b> '+safe(profile.residenceStatus.replaceAll('_',' '))+'</span><span><b>Second Home Flexibility:</b> '+safe(profile.secondHomeFlexibility==='unknown'?'Not evaluated':profile.secondHomeFlexibility)+'</span><span><b>Access:</b> '+safe(profile.secondHomeAccess.replaceAll('-',' '))+'</span><span><b>Subdivision / future value:</b> '+safe(profile.secondHomeSubdivisionPotential.replaceAll('-',' '))+'</span></div>'+(profile.secondHomeFlexibilityNote?'<p class="small">'+safe(profile.secondHomeFlexibilityNote)+'</p>':'');body.querySelector('[data-property-intelligence]')?.after(section)}document.querySelectorAll('.intelligence-compare-card').forEach(card=>{const propertyId=card.querySelector('.prop-id')?.textContent.trim(),record=propertyId&&window.OTPropertyStore?.getProperty(propertyId),grid=card.querySelector('.compare-decision-grid');if(!record||!grid||grid.querySelector('[data-compare-flexibility]'))return;const profile=workflow.profileForRecord(record),span=document.createElement('span');span.dataset.compareFlexibility='true';span.innerHTML='<b>Second home:</b> '+safe(profile.secondHomeFlexibility==='unknown'?'Not evaluated':profile.secondHomeFlexibility);grid.append(span)});document.querySelectorAll('[data-property-intelligence] [onclick*="recalculateSimplifiedScoreForProperty"]').forEach(button=>button.remove())
}
function install(){
 const card=document.querySelector('#addView .form-card');if(card&&!document.getElementById('smartImportPanel')){const panel=document.createElement('section');panel.id='smartImportPanel';panel.className='smart-import-panel';panel.innerHTML='<div class="smart-import-head"><div><strong>Smart Import 3.0</strong><p>Complete what is available, skip what is not, then save once.</p></div><span id="smartImportStatus" data-state="ready">Ready</span></div><ol class="smart-steps"><li data-smart-step="basics"><b>Property basics</b><span>Pending</span></li><li data-smart-step="zillow"><b>Zillow facts</b><span>Optional</span></li><li data-smart-step="research"><b>Research</b><span>Queued</span></li><li data-smart-step="routes"><b>Routes</b><span>Queued</span></li><li data-smart-step="save"><b>Review and save</b><span>Pending</span></li></ol><details><summary>Paste Zillow Facts & Features</summary><label>Zillow Facts text<textarea id="smartZillowFactsText" rows="7" placeholder="Paste the Facts & Features text here"></textarea></label><div class="form-actions"><button id="smartParseZillowBtn" class="secondary" type="button">Import Zillow facts</button></div></details><div class="smart-step-options"><label><input id="smartRunResearch" type="checkbox" checked> Run narrowed Property Research after save</label><label><input id="smartRunRoutes" type="checkbox" checked> Calculate unlocked routes after save</label></div><button id="smartReviewSaveBtn" class="secondary outline" type="button">Review and save</button>';card.prepend(panel);document.getElementById('smartParseZillowBtn').addEventListener('click',parseZillow);document.getElementById('smartRunResearch').addEventListener('change',event=>{session.runResearch=event.target.checked;updateSteps()});document.getElementById('smartRunRoutes').addEventListener('change',event=>{session.runRoutes=event.target.checked;updateSteps()});document.getElementById('smartReviewSaveBtn').addEventListener('click',()=>document.getElementById('savePropertyBtn').scrollIntoView({block:'center'}));['addAddress','addListing','pinReadout'].forEach(id=>document.getElementById(id)?.addEventListener('input',updateSteps));Object.entries(factInputs).forEach(([field,id])=>document.getElementById(id)?.addEventListener('input',event=>{if(session.parsed&&event.isTrusted){session.userEdited.add(field);session.autoPopulated.delete(field);delete event.target.dataset.smartPopulated}}));document.getElementById('addTopBtn')?.addEventListener('click',resetSession);updateSteps()}
 new MutationObserver(()=>{decorateProfile();decorateDossierAndCompare()}).observe(document.body,{childList:true,subtree:true});decorateDossierAndCompare()
}
function runRegressionChecks(){
 const text='Lot size: 50.61 acres\nBedrooms: 2\nBathrooms: 2\nLiving area: 1,152 sqft\nHome type: Single Family Residence\nElectric connected\nSeptic Tank\nWater: Public',base={id:'fixture',name:'Fixture',address:'1 Test Rd, TN',lat:35.4,lng:-84.3,acres:40,fieldSources:{acres:'user-confirmed'},propertyType:'raw-land',propertyIntelligence:{propertyProfile:{}},development:{driveway:'unknown',homesite:'unknown',utilities:'unknown'}};
 const manual=mergeZillowFacts(base,text),manualRepeat=mergeZillowFacts(manual.property,text),unprotected=mergeZillowFacts({...base,acres:0,fieldSources:{}},text),repeat=mergeZillowFacts(unprotected.property,text),autoPrepared=mergeZillowFacts({...base,acres:50.61,fieldSources:{acres:'user-confirmed'}},text,[],['acres']),edited=mergeZillowFacts(base,text,['acres'],['acres']),knownRefresh=mergeZillowFacts({...base,sourceCandidates:{}},text,[],[],{recordConflicts:false}),raw={...base,zillowFacts:{current:{rawText:text}}},refreshed=(()=>{const mapped=mergeZillowFacts(raw,text);return workflow.applyResearchAssessment(mapped.property).property})(),skipped=workflow.completionSummary({research:'skipped',routes:0,partial:true});
 const checks={
  addressOnlyCanSkipOptionalSteps:skipped.status==='partial'&&skipped.items[0]==='Zillow facts skipped'&&skipped.items[1]==='Property research skipped',
  zillowPasteParses:manual.parsed.found>=8,
  manualValueSurvives:manual.property.acres===40,
  manualSourceSurvives:manual.property.fieldSources.acres==='user-confirmed',
  conflictCandidatePreserved:manual.property.sourceCandidates.acres.length===1,
  repeatedConflictDoesNotDuplicate:manualRepeat.property.sourceCandidates.acres.length===1,
  zillowFillsBlankCanonical:unprotected.property.acres===50.61&&unprotected.property.propertyIntelligence.propertyProfile.electric==='verified',
  autoPopulatedFieldUsesZillowSource:autoPrepared.property.acres===50.61&&autoPrepared.property.fieldSources.acres==='zillow',
  explicitEditWinsOverAutoPopulation:edited.property.acres===40&&edited.property.fieldSources.acres==='user-confirmed',
  knownStoredEvidenceDoesNotReopenConflict:knownRefresh.property.acres===40&&!knownRefresh.property.sourceCandidates&&knownRefresh.conflicts.length===0,
  repeatedImportDoesNotDuplicate:repeat.updated.length===0&&repeat.property.sourceCandidates?.acres===undefined,
  refreshReprocessesStoredText:refreshed.beds===2&&refreshed.propertyResearch.status==='partial',
  completionSummaryStable:workflow.completionSummary({zillow:8,research:'partial',routes:0,reviewCount:2,partial:true}).items.length===5
 };
 return {passed:Object.values(checks).every(Boolean),checks}
}
window.refreshPropertyData=refreshPropertyData;
window.OTSmartImportCore={mergeZillowFacts,runRegressionChecks};
window.OTSmartImportUI={preparePropertyForSave,afterPropertySaved,refreshPropertyData,resetSession,profileEditor};
window.addEventListener('DOMContentLoaded',install);
})();
