/* V4.2 stabilization UI: compact dossier, TYS route policy, and manual route review. */
(()=>{
  'use strict';
  const policy=window.OTRoutePolicy,precedence=window.OTSourcePrecedence;
  const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const finite=value=>value!==null&&value!==''&&value!==undefined&&Number.isFinite(Number(value));
  const pause=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
  let lastNominatimAt=0,routeRefreshBusy=false;
  function haversineMiles(aLat,aLng,bLat,bLng){const radius=3958.8,toRadians=value=>value*Math.PI/180,dLat=toRadians(bLat-aLat),dLng=toRadians(bLng-aLng),a=Math.sin(dLat/2)**2+Math.cos(toRadians(aLat))*Math.cos(toRadians(bLat))*Math.sin(dLng/2)**2;return 2*radius*Math.asin(Math.sqrt(a))}
  async function fetchWithTimeout(url,options={},timeoutMs=6000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}catch(error){if(error?.name==='AbortError')throw new Error('The route service timed out.');throw error}finally{clearTimeout(timer)}}

  function isVerifiedPin(property){return property?.locationConfidence==='verified'||property?.locationVerification?.userVerified===true||/manual|verified/i.test(String(property?.pinQuality||''))||(property?.fieldSources?.lat==='user-confirmed'&&property?.fieldSources?.lng==='user-confirmed')}
  function routeTarget(destination){if(finite(destination?.lat)&&finite(destination?.lng))return `${destination.lat},${destination.lng}`;return destination?.address||destination?.name||''}
  function routeLink(property,destination){if(!finite(property?.lat)||!finite(property?.lng))return {ok:false,error:'Confirm the property pin before opening directions.'};const target=routeTarget(destination);if(!target)return {ok:false,error:'Select a destination name, address, or verified coordinates first.'};return {ok:true,url:`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(`${property.lat},${property.lng}`)}&destination=${encodeURIComponent(target)}`}}
  function sameRoute(a,b){const left=policy.normalizedDestination(a),right=policy.normalizedDestination(b);return policy.categoryKey(left)===policy.categoryKey(right)&&left.name===right.name&&left.address===right.address&&Math.abs(Number(left.routeMiles)-Number(right.routeMiles))<.11&&Math.abs(Number(left.routeMinutes)-Number(right.routeMinutes))<.51}
  function routeForDisplay(property,key){return policy.activeRoute(property,key)||(key==='airport'?policy.canonicalAirport({source:'route-automation'}):policy.normalizedDestination({},key))}
  function routeRows(property){
    return policy.config.displayCategories.map(({key,label})=>{
      const route=routeForDisplay(property,key),known=route.name||route.address,hasRoute=finite(route.routeMinutes)&&finite(route.routeMiles),details=[route.source&&`Source: ${route.source}`,route.checkedAt&&`Checked: ${route.checkedAt}`,route.evaluatedAlternative?.name&&`Alternative: ${route.evaluatedAlternative.name} · ${policy.formatDuration(route.evaluatedAlternative.routeMinutes)}`].filter(Boolean);
      return `<div class="stable-route-row"><div><b>${safe(label)}</b><span>${known?safe(route.name||route.address):'Needs destination review'}</span><small>${hasRoute?`${policy.formatMiles(route.routeMiles)} · ${policy.formatDuration(route.routeMinutes)}`:'Routed mileage and time unavailable'}</small>${details.length?`<details><summary>Details</summary><small>${details.map(safe).join(' · ')}</small></details>`:''}</div><div><button class="secondary outline" data-stable-route-open="${safe(key)}">Open route</button><button class="secondary outline" data-stable-route-edit="${safe(key)}">Edit route data</button></div></div>`;
    }).join('');
  }
  function importedFacts(property){
    const land=property.propertyIntelligence?.zillowLand||{},profile=property.propertyIntelligence?.propertyProfile||{},structures=['garage','detachedGarage','carport','barn','stable','workshop','storageBuilding','shed'].filter(key=>land[key]==='yes').map(key=>key.replace(/([A-Z])/g,' $1')),character=['wooded','private','levelLand','slopedLand','rollingTerrain','clearedLand','pasture','mountainView'].filter(key=>land[key]==='yes').map(key=>key.replace(/([A-Z])/g,' $1'));
    return [property.yearBuilt&&`Built ${property.yearBuilt}`,property.structureArea&&`${Number(property.structureArea).toLocaleString()} sq ft structure`,property.homeType,property.heating&&`Heat: ${property.heating}`,property.cooling&&`Cooling: ${property.cooling}`,profile.waterSource&&`Water: ${profile.waterSource}`,profile.septicOrSewer&&`Wastewater: ${profile.septicOrSewer}`,profile.electric&&`Electric: ${profile.electric}`,profile.internet&&`Internet: ${profile.internet}`,structures.length&&`Structures: ${structures.join(', ')}`,character.length&&`Land: ${character.join(', ')}`,profile.waterFeatureType&&profile.waterFeatureType!=='unknown'&&`Water feature: ${profile.waterFeatureType}`,property.parcelNumber&&`Parcel: ${property.parcelNumber}`,property.annualTaxes&&`Taxes: $${Number(property.annualTaxes).toLocaleString()}`].filter(Boolean);
  }
  function compactHeader(drawer,property){
    const tools=drawer.querySelector('.dossier-tools');if(!tools||tools.dataset.stabilized)return;tools.dataset.stabilized='true';
    const existing=[...tools.querySelectorAll('button')],edit=existing.find(button=>/Edit/i.test(button.textContent));if(edit){edit.textContent='Edit';edit.className='secondary'}
    let paste=existing.find(button=>/Paste Zillow/i.test(button.textContent));if(!paste){paste=document.createElement('button');paste.className='secondary';paste.dataset.zillow='true';paste.textContent='Paste Zillow Facts';tools.append(paste)}
    const more=document.createElement('details');more.className='dossier-more';more.innerHTML='<summary>More</summary><div class="dossier-more-menu"></div>';const menu=more.querySelector('div');existing.filter(button=>button!==edit&&button!==paste).forEach(button=>menu.append(button));
    const add=(label,handler,danger=false)=>{if([...menu.children].some(button=>button.textContent.trim()===label))return;const button=document.createElement('button');button.type='button';button.textContent=label;button.className=danger?'secondary danger-outline':'secondary outline';button.onclick=handler;menu.append(button)};
    add('Adjust property location',()=>window.startPinEdit?.(property.id));add('Site Planning',()=>window.openSitePlanning?.(property.id));add('Delete property',()=>window.deleteProperty?.(property.id),true);tools.append(more);
  }
  function compactDossier(){
    const drawer=document.querySelector('#drawer'),id=drawer?.querySelector('.prop-id')?.textContent?.trim(),canonical=id&&window.OTPropertyStore?.getProperty(id),property=canonical&&window.OTIntelligenceRecord?window.OTIntelligenceRecord(canonical):canonical;if(!drawer||!property)return;compactHeader(drawer,property);const body=drawer.querySelector('.drawer-body');if(!body)return;
    if(!body.querySelector('[data-imported-facts]')){const facts=importedFacts(property),section=document.createElement('details');section.className='section stable-imported-facts';section.dataset.importedFacts='true';section.innerHTML=`<summary>Property details${facts.length?` · ${facts.length} imported facts`:''}</summary>${facts.length?`<div class="stable-fact-grid">${facts.map(value=>`<span>${safe(value)}</span>`).join('')}</div>`:'<p class="small">Paste Zillow Facts to populate home, land, utility, and structure details.</p>'}`;body.querySelector('.facts-line')?.after(section)}
    const oldRoute=body.querySelector('.route-refresh')?.closest('.section');if(oldRoute)oldRoute.hidden=true;
    if(!body.querySelector('[data-stable-routes]')){const section=document.createElement('section'),summary=property.routeState?.lastResult;section.className='section stable-routes';section.dataset.stableRoutes='true';section.innerHTML=`<h3>Access & destinations</h3><p class="small" data-route-status>${summary?safe(`${summary.updated} updated · ${summary.unchanged} unchanged · ${summary.needsReview} need review${finite(summary.scoreBefore)&&finite(summary.scoreAfter)?` · score ${Number(summary.scoreBefore).toFixed(1)} → ${Number(summary.scoreAfter).toFixed(1)}`:''}`):'TYS and property-specific routed destinations. Straight-line distance is never scored.'}</p>${routeRows(property)}`;body.append(section)}
  }
  function setRouteStatus(message){const status=document.querySelector('[data-route-status]')||document.getElementById('routeStatus');if(status)status.textContent=message}
  async function nominatimCandidates(query,property){
    const elapsed=Date.now()-lastNominatimAt;if(elapsed<1100)await pause(1100-elapsed);lastNominatimAt=Date.now();
    const west=Number(property.lng)-1.2,east=Number(property.lng)+1.2,north=Number(property.lat)+1.2,south=Number(property.lat)-1.2,url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=40&countrycodes=us&bounded=1&viewbox=${west},${north},${east},${south}&q=${encodeURIComponent(query)}`;
    const response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Destination search returned ${response.status}.`);const values=await response.json();return values.map(value=>({name:value.name||String(value.display_name||'').split(',')[0],address:value.display_name||'',lat:Number(value.lat),lng:Number(value.lon),searchType:value.type||'',searchCategory:value.category||value.class||'',source:'route-automation'})).filter(value=>finite(value.lat)&&finite(value.lng));
  }
  async function routedCandidate(property,candidate){
    const url=`https://router.project-osrm.org/route/v1/driving/${property.lng},${property.lat};${candidate.lng},${candidate.lat}?overview=false&steps=false`,response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Routing returned ${response.status}.`);const body=await response.json(),route=body.code==='Ok'&&body.routes?.[0];if(!route||!finite(route.distance)||!finite(route.duration))throw new Error(body.message||body.code||'No routed result was available.');return {...candidate,routeMiles:Number((Number(route.distance)/1609.344).toFixed(2)),routeMinutes:Number((Number(route.duration)/60).toFixed(1)),checkedAt:new Date().toISOString(),source:'route-automation',provider:'Project OSRM public routing service'};
  }
  async function routeCandidates(property,candidates){const selected=candidates.slice(0,6);if(!selected.length)return null;const coordinates=[[property.lng,property.lat],...selected.map(candidate=>[candidate.lng,candidate.lat])].map(pair=>pair.join(',')).join(';'),destinations=selected.map((_,index)=>index+1).join(';'),url=`https://router.project-osrm.org/table/v1/driving/${coordinates}?sources=0&destinations=${destinations}&annotations=duration,distance`,response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Routing returned ${response.status}.`);const body=await response.json();if(body.code!=='Ok')throw new Error(body.message||body.code||'No routed result was available.');const routed=selected.map((candidate,index)=>{const duration=body.durations?.[0]?.[index],distance=body.distances?.[0]?.[index];return finite(duration)&&finite(distance)?{...candidate,routeMiles:Number((Number(distance)/1609.344).toFixed(2)),routeMinutes:Number((Number(duration)/60).toFixed(1)),checkedAt:new Date().toISOString(),source:'route-automation',provider:'Project OSRM public routing service'}:null}).filter(Boolean);return routed.sort((a,b)=>a.routeMinutes-b.routeMinutes)[0]||null}
  async function findPracticalRoute(property,query,{hospital=false}={}){
    let candidates=await nominatimCandidates(query,property);if(hospital){const hospitals=candidates.filter(candidate=>candidate.searchType==='hospital'||/hospital|medical center|emergency/i.test(`${candidate.name} ${candidate.address}`));if(hospitals.length)candidates=hospitals}if(/costco/i.test(query)){const warehouses=candidates.filter(candidate=>!/(?:gasoline|fuel|gas station)/i.test(`${candidate.name} ${candidate.address}`));if(warehouses.length)candidates=warehouses}if(/supermarket/i.test(query)){const fullService=candidates.filter(candidate=>(candidate.searchType==='supermarket'||candidate.searchCategory==='shop'||/(?:supermarket|walmart|food city|ingles|kroger|publix|food lion|iga)/i.test(`${candidate.name} ${candidate.address}`))&&!/(?:dollar|convenience|fuel|gas station)/i.test(`${candidate.name} ${candidate.address}`));if(fullService.length)candidates=fullService}candidates.sort((a,b)=>haversineMiles(property.lat,property.lng,a.lat,a.lng)-haversineMiles(property.lat,property.lng,b.lat,b.lng));
    return routeCandidates(property,candidates);
  }
  function sourceConfirmed(route){return precedence?.normalizeSource(route?.source)==='user-confirmed'}
  function withCategory(route,key,label){return {...route,type:key,category:label}}
  async function automatedRoutes(property){
    const result={},needs=[];
    const airportExisting=policy.activeRoute(property,'airport');
    if(airportExisting&&sourceConfirmed(airportExisting))result.airport=policy.canonicalAirport(airportExisting);else try{result.airport=policy.canonicalAirport(await routedCandidate(property,policy.config.airport))}catch{needs.push('TYS airport')}
    const tasks=[['grocery','Grocery','supermarket',{}],['hospital','Hospital / emergency care','hospital',{hospital:true}],['costco','Costco','Costco',{}]];
    for(const [key,label,query,options] of tasks){const existing=policy.activeRoute(property,key);if(existing&&sourceConfirmed(existing)){result[key]=existing;continue}try{const route=await findPracticalRoute(property,query,options);if(route)result[key]=withCategory(route,key,label);else needs.push(label)}catch{needs.push(label)}}
    const existingHome=policy.activeRoute(property,'home-improvement');
    if(existingHome&&sourceConfirmed(existingHome))result.homeImprovement=existingHome;else try{const lowes=await findPracticalRoute(property,"Lowe's"),homeDepot=await findPracticalRoute(property,'Home Depot'),selected=policy.chooseHomeImprovement(lowes,homeDepot);if(selected)result.homeImprovement=selected;else needs.push('Home improvement')}catch{needs.push('Home improvement')}
    return {result,needs:[...new Set(needs)]};
  }
  function retainedAndHistory(property,nextRoutes){
    const existing=Array.isArray(property.destinations)?property.destinations:[],scored=new Set(policy.config.scoredCategories),retained=[],history=[...(property.routeHistory||[])];
    for(const raw of existing){const key=policy.categoryKey(raw);if(scored.has(key)||key==='other-airport'){const replacement=nextRoutes.find(route=>policy.categoryKey(route)===key);if(!replacement||!sameRoute(raw,replacement))history.push({...policy.normalizedDestination(raw),archivedAt:new Date().toISOString()})}else retained.push(raw)}
    return {destinations:[...retained,...nextRoutes],routeHistory:history.slice(-30)};
  }
  async function refreshRoutes(propertyId){
    if(routeRefreshBusy){setRouteStatus('A route refresh is already running.');return false}const canonical=window.OTPropertyStore?.getProperty(propertyId),property=canonical&&window.OTIntelligenceRecord?window.OTIntelligenceRecord(canonical):canonical;if(!property)return false;
    if(!isVerifiedPin(property)){setRouteStatus('Confirm the property pin before refreshing routes. No route data changed.');return false}
    routeRefreshBusy=true;setRouteStatus('Routing to TYS and property-specific destinations…');
    try{
      const before=window.OTIntelligence?.getTurtleScore(property),{result,needs}=await automatedRoutes(property),keys=['airport','grocery','hospital','homeImprovement','costco'],nextRoutes=[],updated=[],unchanged=[];
      for(const key of keys){const route=result[key],existing=policy.activeRoute(property,key==='homeImprovement'?'home-improvement':key);if(!route)continue;if(existing&&sameRoute(existing,route)){nextRoutes.push(existing);unchanged.push(key)}else{nextRoutes.push(route);updated.push(key)}}
      if(!updated.length){setRouteStatus(`No routes changed · ${unchanged.length} unchanged · ${needs.length} need review.`);return false}
      const reconciled=retainedAndHistory(property,nextRoutes),now=new Date().toISOString(),candidate={...canonical,...reconciled,routeState:{...(canonical.routeState||{}),updatedAt:now,provider:'Project OSRM public routing service',lastResult:{updated:updated.length,unchanged:unchanged.length,needsReview:needs.length,checkedAt:now}},updatedAt:now},after=window.OTIntelligence?.getTurtleScore(window.OTIntelligenceRecord?window.OTIntelligenceRecord(candidate):candidate);candidate.routeState.lastResult.scoreBefore=before?.total??null;candidate.routeState.lastResult.scoreAfter=after?.total??null;
      const saved=window.OTPropertyStore.update(propertyId,()=>candidate,'Refresh property-specific routes');if(!saved){setRouteStatus('Route results were found but could not be saved. Prior route data was preserved.');return false}
      setTimeout(()=>window.openProperty(propertyId),220);return true;
    }catch(error){setRouteStatus(`Routes were not changed: ${error.message||'routing service unavailable'}`);return false}finally{routeRefreshBusy=false}
  }
  function editRoute(propertyId,key){
    const property=window.OTPropertyStore.getProperty(propertyId),label=policy.config.displayCategories.find(item=>item.key===key)?.label||key,current=routeForDisplay(property,key);let panel=document.querySelector('#routeEditPanel');if(!panel){panel=document.createElement('aside');panel.id='routeEditPanel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');document.body.append(panel)}const airport=key==='airport';
    panel.innerHTML=`<div class="panel-head"><div><b>Edit ${safe(label)} route</b><p>Enter routed values from a directions result. Saving confirms these values.</p></div><button class="drawer-close" data-route-close aria-label="Close">×</button></div><label>Destination name<input data-route-name value="${safe(airport?policy.config.airport.name:current.name)}"${airport?' readonly':''}></label><label>Full address<input data-route-address value="${safe(airport?policy.config.airport.address:current.address)}"${airport?' readonly':''}></label><div class="route-edit-grid"><label>Routed miles<input data-route-miles type="number" min="0" step="0.1" value="${current.routeMiles??''}"></label><label>Routed minutes<input data-route-minutes type="number" min="0" step="1" value="${current.routeMinutes??''}"></label></div><label>Date checked<input data-route-date type="date" value="${safe((current.checkedAt||new Date().toISOString()).slice(0,10))}"></label><div class="form-message" data-route-message></div><div class="form-actions"><button class="secondary" data-route-save>Save route data</button><button class="secondary outline" data-route-close>Cancel</button></div>`;panel.hidden=false;
    const close=()=>{panel.hidden=true;document.querySelector(`[data-stable-route-edit="${key}"]`)?.focus()};panel.querySelectorAll('[data-route-close]').forEach(button=>button.onclick=close);panel.querySelector('[data-route-save]').onclick=()=>{const miles=panel.querySelector('[data-route-miles]').value.trim(),minutes=panel.querySelector('[data-route-minutes]').value.trim();if(!finite(miles)||!finite(minutes)||Number(miles)<0||Number(minutes)<0){panel.querySelector('[data-route-message]').textContent='Enter valid routed mileage and minutes.';return}const base=airport?policy.config.airport:current,updated={...base,type:key,category:label,name:panel.querySelector('[data-route-name]').value.trim(),address:panel.querySelector('[data-route-address]').value.trim(),routeMiles:Number(miles),routeMinutes:Number(minutes),checkedAt:panel.querySelector('[data-route-date]').value,source:'user-confirmed'};const saved=window.OTPropertyStore.update(propertyId,currentProperty=>{const previous=Array.isArray(currentProperty.destinations)?currentProperty.destinations:[],removed=previous.filter(item=>policy.categoryKey(item)===(key==='homeImprovement'?'home-improvement':key)||(key==='airport'&&policy.categoryKey(item)==='other-airport')),retained=previous.filter(item=>!removed.includes(item)),now=new Date().toISOString();return {...currentProperty,destinations:[...retained,updated],routeHistory:[...(currentProperty.routeHistory||[]),...removed.map(item=>({...policy.normalizedDestination(item),archivedAt:now}))].slice(-30),routeState:{...(currentProperty.routeState||{}),updatedAt:now},fieldSources:{...(currentProperty.fieldSources||{}),[`routes.${key}`]:'user-confirmed'},updatedAt:now}},`Confirm ${label} route data`);if(!saved){panel.querySelector('[data-route-message]').textContent='Route data could not be saved. Prior data was preserved.';return}close();setTimeout(()=>window.openProperty(propertyId),220)};setTimeout(()=>panel.querySelector('[data-route-miles]')?.focus(),0);
  }
  function install(){
    window.refreshRoutes=refreshRoutes;new MutationObserver(compactDossier).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',event=>{const open=event.target.closest('[data-stable-route-open]'),edit=event.target.closest('[data-stable-route-edit]');if(!open&&!edit)return;const id=document.querySelector('#drawer .prop-id')?.textContent?.trim(),property=id&&window.OTPropertyStore.getProperty(id);if(!property)return;if(edit){editRoute(id,edit.dataset.stableRouteEdit);return}const key=open.dataset.stableRouteOpen,destination=routeForDisplay(property,key),link=routeLink(property,destination);if(!link.ok){alert(link.error);return}window.open(link.url,'_blank','noopener')});document.addEventListener('keydown',event=>{const panel=document.querySelector('#routeEditPanel');if(event.key==='Escape'&&panel&&!panel.hidden){event.preventDefault();panel.querySelector('[data-route-close]')?.click()}});compactDossier();
  }
  window.addEventListener('DOMContentLoaded',install);
  window.OTStabilization={routeLink,isVerifiedPin,routeRows,importedFacts,refreshRoutes,runRegressionChecks(){const a={id:'A',lat:35,lng:-84,locationConfidence:'verified',destinations:[policy.canonicalAirport({routeMiles:45,routeMinutes:65}),{category:'Grocery',name:'A Grocery',routeMiles:10.25,routeMinutes:18,source:'user-confirmed'}]},b={id:'B',lat:36,lng:-83,locationConfidence:'verified',destinations:[policy.canonicalAirport({routeMiles:70,routeMinutes:90}),{category:'Grocery',name:'B Grocery',routeMiles:20,routeMinutes:35}]},link=routeLink(a,policy.activeRoute(a,'airport')),manual=policy.activeRoute(a,'grocery');const checks={propertySpecific:manual.name!==policy.activeRoute(b,'grocery').name,validUrl:link.ok&&link.url.startsWith('https://www.google.com/maps/dir/'),correctOrigin:decodeURIComponent(link.url).includes('origin=35,-84'),missingOrigin:!routeLink({},policy.activeRoute(a,'airport')).ok,missingDestination:!routeLink(a,policy.normalizedDestination({},'costco')).ok,manualRouteProtected:sourceConfirmed(manual),noStraightLineSubstitution:policy.activeRoute(a,'costco')===null,verifiedPinRequired:isVerifiedPin(a)&&!isVerifiedPin({...a,locationConfidence:'review'}),cleanDisplay:policy.formatMiles(8.36)==='8.4 mi'&&policy.formatDuration(72)==='1 hr 12 min',tysOnly:policy.activeRoute(a,'airport').code==='TYS'};return {passed:Object.values(checks).every(Boolean),checks}}};
})();
