/* V4.2 stabilization UI: compact dossier, TYS route policy, and manual route review. */
(()=>{
  'use strict';
  const policy=window.OTRoutePolicy,precedence=window.OTSourcePrecedence;
  const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const finite=value=>value!==null&&value!==''&&value!==undefined&&Number.isFinite(Number(value));
  const pause=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
  let lastNominatimAt=0,routeRefreshBusy=false;
  function haversineMiles(aLat,aLng,bLat,bLng){const radius=3958.8,toRadians=value=>value*Math.PI/180,dLat=toRadians(bLat-aLat),dLng=toRadians(bLng-aLng),a=Math.sin(dLat/2)**2+Math.cos(toRadians(aLat))*Math.cos(toRadians(bLat))*Math.sin(dLng/2)**2;return 2*radius*Math.asin(Math.sqrt(a))}
  async function fetchWithTimeout(url,options={},timeoutMs=6000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}catch(error){if(error?.name==='AbortError')throw new Error('The route service timed out.');throw error}finally{clearTimeout(timer)}}

  function isVerifiedPin(property){return ['verified','high'].includes(property?.locationConfidence)||['verified','high'].includes(property?.locationVerification?.status)||property?.locationVerification?.userVerified===true||/manual|verified|rooftop|address match/i.test(String(property?.pinQuality||''))||(property?.fieldSources?.lat==='user-confirmed'&&property?.fieldSources?.lng==='user-confirmed')}
  function routeTarget(destination){if(finite(destination?.lat)&&finite(destination?.lng))return `${destination.lat},${destination.lng}`;return destination?.address||destination?.name||''}
  function routeLink(property,destination){if(!finite(property?.lat)||!finite(property?.lng))return {ok:false,error:'Confirm the property pin before opening directions.'};const target=routeTarget(destination);if(!target)return {ok:false,error:'Select a destination name, address, or verified coordinates first.'};return {ok:true,url:`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(`${property.lat},${property.lng}`)}&destination=${encodeURIComponent(target)}`}}
  function sameRoute(a,b){const left=policy.normalizedDestination(a),right=policy.normalizedDestination(b);return policy.categoryKey(left)===policy.categoryKey(right)&&left.name===right.name&&left.address===right.address&&Math.abs(Number(left.routeMiles)-Number(right.routeMiles))<.11&&Math.abs(Number(left.routeMinutes)-Number(right.routeMinutes))<.51}
  function routeForDisplay(property,key){return policy.activeRoute(property,key)||(key==='airport'?policy.canonicalAirport({source:'route-automation'}):policy.normalizedDestination({},key))}
  function routeRows(property){
    return policy.config.displayCategories.map(({key,label})=>{const route=routeForDisplay(property,key),known=route.name||route.address,hasRoute=finite(route.routeMinutes)&&finite(route.routeMiles);return `<div class="stable-route-row"><div><b>${safe(label)}</b><span>${known?safe(route.name||route.address):'Needs verification'}</span><small>${hasRoute?`${policy.formatMiles(route.routeMiles)} · ${policy.formatDuration(route.routeMinutes)}`:'Route unavailable'}</small></div>${known?`<button class="secondary outline" data-stable-route-open="${safe(key)}">Directions</button>`:''}</div>`}).join('')
  }  function importedFacts(property){
    const land=property.propertyIntelligence?.zillowLand||{},profile=property.propertyIntelligence?.propertyProfile||{},structures=['garage','detachedGarage','carport','barn','stable','workshop','storageBuilding','shed'].filter(key=>land[key]==='yes').map(key=>key.replace(/([A-Z])/g,' $1')),character=['wooded','private','levelLand','slopedLand','rollingTerrain','clearedLand','pasture','mountainView'].filter(key=>land[key]==='yes').map(key=>key.replace(/([A-Z])/g,' $1'));
    const residence={livable:'Livable home',likely_livable:'Likely-livable home · confirm condition',condition_unknown:'Home present · condition unknown',non_livable:'Non-livable home',raw_land:'No residence',unknown:''}[profile.residenceStatus||'unknown'];
    return [residence,property.acres&&`${Number(property.acres).toLocaleString()} acres`,property.beds&&`${property.beds} bedrooms`,property.baths&&`${property.baths} bathrooms`,property.sqft&&`${Number(property.sqft).toLocaleString()} sq ft living area`,property.structureArea&&`${Number(property.structureArea).toLocaleString()} sq ft structure`,property.yearBuilt&&`Built ${property.yearBuilt}`,property.homeType,property.heating&&`Heat: ${property.heating}`,property.cooling&&`Cooling: ${property.cooling}`,property.parkingSpaces&&`${property.parkingSpaces} parking spaces`,profile.waterSource&&profile.waterSource!=='unknown'&&`Water: ${profile.waterSource}`,profile.septicOrSewer&&profile.septicOrSewer!=='unknown'&&`Wastewater: ${profile.septicOrSewer}`,profile.electric&&profile.electric!=='unknown'&&`Electric: ${profile.electric}`,profile.internet&&profile.internet!=='unknown'&&`Internet: ${profile.internet}`,profile.cable&&profile.cable!=='unknown'&&`Cable: ${profile.cable}`,profile.driveway&&profile.driveway!=='unknown'&&`Driveway: ${profile.driveway}`,structures.length&&`Structures: ${structures.join(', ')}`,character.length&&`Land: ${character.join(', ')}`,profile.waterFeatureType&&profile.waterFeatureType!=='unknown'&&`Water feature: ${profile.waterFeatureType}`,property.parcelNumber&&`Parcel: ${property.parcelNumber}`,property.annualTaxes&&`Taxes: $${Number(property.annualTaxes).toLocaleString()}`].filter(Boolean);
  }
  function compactHeader(drawer,property){
    const tools=drawer.querySelector('.dossier-tools');if(!tools||tools.dataset.stabilized)return;tools.dataset.stabilized='true';
    const existing=[...tools.querySelectorAll('button')],editAll=existing.find(button=>/Edit/i.test(button.textContent));if(editAll)editAll.remove();
    let paste=existing.find(button=>/Paste Zillow|Reprocess Zillow/i.test(button.textContent));if(!paste){paste=document.createElement('button');paste.className='secondary outline';paste.dataset.zillow='true';tools.append(paste)}paste.textContent='Reprocess Zillow Facts';
    existing.filter(button=>button.isConnected).forEach(button=>{if(/Adjust pin|Adjust property location/i.test(button.textContent))button.textContent='Adjust property location';else if(/Research property/i.test(button.textContent))button.textContent='Run Property Research';else if(/Refresh routes/i.test(button.textContent))button.textContent='Refresh routes';else if(/County parcel/i.test(button.textContent))button.textContent='View County Parcel Map';else if(/Listing/i.test(button.textContent))button.textContent='Open listing'});
    const editProfile=document.createElement('button');editProfile.className='secondary';editProfile.type='button';editProfile.textContent='Edit Profile';editProfile.onclick=()=>window.openPropertyScorecard?.(property.id);
    const refresh=document.createElement('button');refresh.className='secondary';refresh.type='button';refresh.textContent='Refresh Property Data';refresh.onclick=()=>window.refreshPropertyData?.(property.id);
    const more=document.createElement('details');more.className='dossier-more';more.innerHTML='<summary>More</summary><div class="dossier-more-menu"></div>';const menu=more.querySelector('div');[...tools.querySelectorAll('button')].forEach(button=>menu.append(button));
    const add=(label,handler,danger=false)=>{if([...menu.children].some(button=>button.textContent.trim()===label))return;const button=document.createElement('button');button.type='button';button.textContent=label;button.className=danger?'secondary danger-outline':'secondary outline';button.onclick=handler;menu.append(button)};
    add('Site Planning',()=>window.openSitePlanning?.(property.id));if(property.parcelGeometry||property.boundary?.length>=3)add('View parcel boundary',()=>window.fitParcelBoundary?.(property.id));add('Advanced diagnostics',()=>{const details=drawer.querySelector('[data-imported-facts]');if(details){details.open=true;details.scrollIntoView({block:'nearest'})}else drawer.querySelector('.explain-list')?.scrollIntoView({block:'nearest'})});add('Delete property',()=>window.deleteProperty?.(property.id),true);tools.append(editProfile,refresh,more)
  }  function compactDossier(){
    const drawer=document.querySelector('#drawer'),id=drawer?.querySelector('.prop-id')?.textContent?.trim(),canonical=id&&window.OTPropertyStore?.getProperty(id),property=canonical&&window.OTIntelligenceRecord?window.OTIntelligenceRecord(canonical):canonical;if(!drawer||!property)return;compactHeader(drawer,property);const body=drawer.querySelector('.drawer-body');if(!body)return;
    const overview=body.querySelector('[data-dossier-tab="Overview"]')||body,profile=window.OTPropertyWorkflow?.profileForRecord?.(property)||{},homeLabel={livable:'Livable home',likely_livable:'Likely-livable home',condition_unknown:'Home condition unknown',non_livable:'Non-livable home',raw_land:'No existing house',unknown:'House status unknown'}[profile.residenceStatus||'unknown'],cost=window.OTPrecision?.estimateCost?.(property.developmentCost||{}),planningAnalyses=Object.values(property.sitePlanning?.drivewayAnalyses||{}),planningEstimate=planningAnalyses.find(value=>finite(value?.low)&&finite(value?.high)),connectedServices=['electric','waterSource','septicOrSewer'].filter(key=>!['unknown','none',''].includes(String(profile[key]||'unknown'))).length,costLabel=cost?.items?.length&&Number(cost.total)>0?`$${Number(cost.total).toLocaleString()}`:planningEstimate?`$${Number(planningEstimate.low).toLocaleString()}–$${Number(planningEstimate.high).toLocaleString()}`:connectedServices>=2?'Existing services noted · site work not scoped':'Needs estimate';
    overview.querySelector('.property-visual-summary .dossier-tools')?.setAttribute('hidden','');overview.querySelectorAll('.kpis,.dossier-summary-strip,.facts-line,.source-line,.decision-card,.planning-overview').forEach(element=>element.classList.add('dossier-legacy-hidden'));[...overview.children].forEach(element=>{if(/Score breakdown|Decision snapshot|Pros\s*Concerns|Research history|Score history/i.test(element.textContent||''))element.hidden=true});const mapPins=[...overview.children].find(element=>/^Map pins/i.test(element.querySelector('h3')?.textContent||'')),landPanel=body.querySelector('[data-dossier-tab="Land & Home"]');if(mapPins&&landPanel)landPanel.append(mapPins);
    if(!overview.querySelector('[data-property-conclusions]')){const conclusions=window.OTPropertyWorkflow?.propertyConclusions?.(property)||[],section=document.createElement('section');section.className='section dossier-conclusions';section.dataset.propertyConclusions='true';section.innerHTML=`<h3>Property conclusions</h3><div class="conclusion-grid">${conclusions.map(item=>`<article><span>${safe(item.label)}</span><b>${safe(item.rating)}</b><p>${safe(item.support)}</p></article>`).join('')}</div>`;const visual=overview.querySelector('[data-property-visual]');visual?visual.after(section):overview.prepend(section)}
    if(!overview.querySelector('[data-evaluation-summary]')){const section=document.createElement('section');section.className='section dossier-evaluation-summary';section.dataset.evaluationSummary='true';section.innerHTML=`<div><b>Existing house</b><span>${safe(homeLabel)}${property.sqft?` · ${Number(property.sqft).toLocaleString()} sq ft`:''}</span></div><div><b>Development estimate</b><span>${safe(costLabel)}</span></div>`;overview.querySelector('[data-property-conclusions]')?.after(section)}
    if(!body.querySelector('[data-imported-facts]')){const facts=importedFacts(property),section=document.createElement('details');section.className='section stable-imported-facts';section.dataset.importedFacts='true';section.innerHTML=`<summary>Property details${facts.length?` · ${facts.length} saved facts`:''}</summary>${facts.length?`<div class="stable-fact-grid">${facts.map(value=>`<span>${safe(value)}</span>`).join('')}</div>`:'<p class="small">No imported listing facts are saved yet.</p>'}`;(body.querySelector('[data-dossier-tab="Land & Home"]')||body).append(section)}
    const oldRoute=body.querySelector('.route-refresh')?.closest('.section');if(oldRoute)oldRoute.hidden=true;
    if(!body.querySelector('[data-stable-routes]')){const section=document.createElement('section');section.className='section stable-routes';section.dataset.stableRoutes='true';section.innerHTML='<h3>Main routes</h3><p class="small" data-route-status>Property-specific practical destinations and TYS drive times.</p>'+routeRows(property);overview.append(section)}
  }  function setRouteStatus(message){const status=document.querySelector('[data-route-status]')||document.getElementById('routeStatus');if(status)status.textContent=message}
  async function nominatimCandidates(query,property,radiusMiles){
    const elapsed=Date.now()-lastNominatimAt;if(elapsed<1100)await pause(1100-elapsed);lastNominatimAt=Date.now();
    const latDelta=Number(radiusMiles)/69,lngDelta=Number(radiusMiles)/(69*Math.max(.25,Math.cos(Number(property.lat)*Math.PI/180))),west=Number(property.lng)-lngDelta,east=Number(property.lng)+lngDelta,north=Number(property.lat)+latDelta,south=Number(property.lat)-latDelta,url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&extratags=1&namedetails=1&limit=40&countrycodes=us&bounded=1&viewbox=${west},${north},${east},${south}&q=${encodeURIComponent(query)}`;
    const response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Destination search returned ${response.status}.`);const values=await response.json();return values.map(value=>({name:value.name||value.namedetails?.name||String(value.display_name||'').split(',')[0],address:value.display_name||'',lat:Number(value.lat),lng:Number(value.lon),searchType:value.type||'',searchCategory:value.category||value.class||'',addressDetails:value.address||{},extratags:value.extratags||{},stateCode:value.address?.['ISO3166-2-lvl4']||'',status:value.extratags?.opening_hours==='closed'?'closed':'',source:'route-automation'})).filter(value=>finite(value.lat)&&finite(value.lng)&&haversineMiles(property.lat,property.lng,value.lat,value.lng)<=Number(radiusMiles)*1.03);
  }
  async function routedCandidate(property,candidate){
    const url=`https://router.project-osrm.org/route/v1/driving/${property.lng},${property.lat};${candidate.lng},${candidate.lat}?overview=false&steps=false`,response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Routing returned ${response.status}.`);const body=await response.json(),route=body.code==='Ok'&&body.routes?.[0];if(!route||!finite(route.distance)||!finite(route.duration))throw new Error(body.message||body.code||'No routed result was available.');return {...candidate,routeMiles:Number((Number(route.distance)/1609.344).toFixed(2)),routeMinutes:Number((Number(route.duration)/60).toFixed(1)),checkedAt:new Date().toISOString(),source:'route-automation',provider:'Project OSRM public routing service'};
  }
  async function routeCandidates(property,candidates){const selected=candidates.slice(0,policy.config.candidateLimit);if(!selected.length)return [];const coordinates=[[property.lng,property.lat],...selected.map(candidate=>[candidate.lng,candidate.lat])].map(pair=>pair.join(',')).join(';'),destinations=selected.map((_,index)=>index+1).join(';'),url=`https://router.project-osrm.org/table/v1/driving/${coordinates}?sources=0&destinations=${destinations}&annotations=duration,distance`,response=await fetchWithTimeout(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Routing returned ${response.status}.`);const body=await response.json();if(body.code!=='Ok')throw new Error(body.message||body.code||'No routed result was available.');return selected.map((candidate,index)=>{const duration=body.durations?.[0]?.[index],distance=body.distances?.[0]?.[index];return finite(duration)&&finite(distance)?{...candidate,routeMiles:Number((Number(distance)/1609.344).toFixed(2)),routeMinutes:Number((Number(duration)/60).toFixed(1)),checkedAt:new Date().toISOString(),source:'route-automation',provider:'Project OSRM public routing service'}:null}).filter(Boolean)}
  function practicalCandidates(candidates,category){return policy.validCandidates(candidates,category).valid}
  async function collectCandidates(property,category,radiusMiles){
    const queries=policy.config.searchQueries[category]||[],collected=[],errors=[];
    for(const query of queries)try{collected.push(...await nominatimCandidates(query,property,radiusMiles))}catch(error){errors.push(error)}
    if(!collected.length&&errors.length)throw errors[0];
    return practicalCandidates(collected,category).sort((a,b)=>haversineMiles(property.lat,property.lng,a.lat,a.lng)-haversineMiles(property.lat,property.lng,b.lat,b.lng));
  }
  async function findPracticalRoute(property,category){
    const radiusKey=['home-depot','lowes'].includes(category)?'home-improvement':category,radii=policy.config.searchRadiiMiles[radiusKey],initial=await collectCandidates(property,category,radii.initial),initialRouted=await routeCandidates(property,initial),initialWinner=policy.chooseRoutedCandidate(radiusKey,initialRouted),needsFallback=!initialWinner||(radiusKey==='grocery'&&policy.groceryRouteIsSuspicious(initialWinner,initialRouted));
    if(!needsFallback)return {route:initialWinner,routed:initialRouted,usedFallback:false,dependable:true};
    const broad=await collectCandidates(property,category,radii.fallback),known=new Set(initialRouted.map(policy.candidateKey)),additional=await routeCandidates(property,broad.filter(candidate=>!known.has(policy.candidateKey(candidate)))),routed=[...initialRouted,...additional],winner=policy.chooseRoutedCandidate(radiusKey,routed),dependable=Boolean(winner)&&(radiusKey!=='grocery'||!policy.groceryRouteIsSuspicious(winner,routed));
    return {route:dependable?winner:null,routed,usedFallback:true,dependable};
  }
  function sourceConfirmed(route){return precedence?.normalizeSource(route?.source)==='user-confirmed'||route?.locked===true}
  function withCategory(route,key,label){return {...route,type:key,category:label,locked:false}}
  function retainOrReplace(existing,candidate,key,label,needs,preserved){
    if(candidate&&key==='grocery'&&policy.groceryRouteIsSuspicious(candidate,[candidate]))candidate=null;
    if(existing&&candidate&&sameRoute(existing,candidate))return existing;
    const choice=policy.automaticReplacement(existing,candidate);
    if(choice.route&&choice.replaced)return withCategory(choice.route,key,label);
    if(choice.route){if(choice.reason!=='manual-lock'){needs.push(label);preserved.push(label)}return choice.route}
    needs.push(label);return null;
  }
  async function automatedRoutes(property){
    const result={},needs=[],preserved=[],search={};
    const airportExisting=policy.activeRoute(property,'airport');
    if(airportExisting&&sourceConfirmed(airportExisting))result.airport=policy.canonicalAirport(airportExisting);else try{result.airport=policy.canonicalAirport(retainOrReplace(airportExisting,await routedCandidate(property,policy.config.airport),'airport','TYS airport',needs,preserved))}catch{const retained=retainOrReplace(airportExisting,null,'airport','TYS airport',needs,preserved);if(retained)result.airport=policy.canonicalAirport(retained)}
    const tasks=[['grocery','Grocery'],['hospital','Hospital / emergency care'],['costco','Costco']];
    for(const [key,label] of tasks){const existing=policy.activeRoute(property,key);if(existing&&sourceConfirmed(existing)){result[key]=existing;continue}try{const found=await findPracticalRoute(property,key);search[key]={evaluated:found.routed.length,usedFallback:found.usedFallback};const selected=retainOrReplace(existing,found.route,key,label,needs,preserved);if(selected)result[key]=selected}catch{const retained=retainOrReplace(existing,null,key,label,needs,preserved);if(retained)result[key]=retained}}
    const existingHome=policy.activeRoute(property,'home-improvement');
    if(existingHome&&sourceConfirmed(existingHome))result.homeImprovement=existingHome;else try{const lowes=await findPracticalRoute(property,'lowes'),homeDepot=await findPracticalRoute(property,'home-depot'),selected=policy.chooseHomeImprovement(lowes.route,homeDepot.route);search.homeImprovement={evaluated:lowes.routed.length+homeDepot.routed.length,usedFallback:lowes.usedFallback||homeDepot.usedFallback};const retained=retainOrReplace(existingHome,selected,'home-improvement','Home improvement',needs,preserved);if(retained)result.homeImprovement=retained}catch{const retained=retainOrReplace(existingHome,null,'home-improvement','Home improvement',needs,preserved);if(retained)result.homeImprovement=retained}
    return {result,needs:[...new Set(needs)],preserved:[...new Set(preserved)],search};
  }
  function retainedAndHistory(property,nextRoutes){
    const existing=Array.isArray(property.destinations)?property.destinations:[],scored=new Set(policy.config.scoredCategories),retained=[],history=[...(property.routeHistory||[])];
    for(const raw of existing){const key=policy.categoryKey(raw);if(scored.has(key)||key==='other-airport'){const replacement=nextRoutes.find(route=>policy.categoryKey(route)===key);if(!replacement||!sameRoute(raw,replacement))history.push({...policy.normalizedDestination(raw),archivedAt:new Date().toISOString()})}else retained.push(raw)}
    return {destinations:[...retained,...nextRoutes],routeHistory:history.slice(-30)};
  }
  async function refreshRoutes(propertyId,options={}){
    if(routeRefreshBusy){setRouteStatus('A route refresh is already running.');return false}const canonical=window.OTPropertyStore?.getProperty(propertyId),property=canonical&&window.OTIntelligenceRecord?window.OTIntelligenceRecord(canonical):canonical;if(!property)return false;
    if(!isVerifiedPin(property)){setRouteStatus('Confirm the property pin before refreshing routes. No route data changed.');return false}
    routeRefreshBusy=true;setRouteStatus('Routing to TYS and property-specific destinations…');
    try{
      const before=window.OTIntelligence?.getTurtleScore(property),{result,needs,preserved,search}=await automatedRoutes(property),unresolvedNeeds=needs.filter(label=>!preserved.includes(label)),keys=['airport','grocery','hospital','homeImprovement','costco'],nextRoutes=[],updated=[],unchanged=[];
      for(const key of keys){const route=result[key],existing=policy.activeRoute(property,key==='homeImprovement'?'home-improvement':key);if(!route)continue;if(existing&&sameRoute(existing,route)){nextRoutes.push(existing);unchanged.push(key)}else{nextRoutes.push(route);updated.push(key)}}
      if(!updated.length&&!needs.length){setRouteStatus(`No routes changed · ${unchanged.length} unchanged.`);return false}
      const reconciled=retainedAndHistory(property,nextRoutes),now=new Date().toISOString(),candidate={...canonical,...reconciled,routeState:{...(canonical.routeState||{}),updatedAt:now,provider:'Nominatim candidate search + Project OSRM routed comparison',lastResult:{updated:updated.length,unchanged:unchanged.length,needsReview:unresolvedNeeds.length,preserved:preserved.length,checkedAt:now,search}},updatedAt:now},after=window.OTIntelligence?.getTurtleScore(window.OTIntelligenceRecord?window.OTIntelligenceRecord(candidate):candidate);candidate.routeState.lastResult.scoreBefore=before?.total??null;candidate.routeState.lastResult.scoreAfter=after?.total??null;
      const saved=window.OTCanonicalPropertyUpdate(propertyId,()=>candidate,'Refresh property-specific routes',{recalculate:options.recalculate!==false});if(!saved){setRouteStatus('Route results were found but could not be saved. Prior route data was preserved.');return false}
      setRouteStatus(`${updated.length} updated · ${unchanged.length} unchanged · ${preserved.length} prior routes preserved · ${unresolvedNeeds.length} need review.`);window.OTLastRouteRefresh={propertyId,updated:updated.length,unchanged:unchanged.length,needsReview:unresolvedNeeds.length,preserved:preserved.length};if(options.reopen!==false)setTimeout(()=>window.openProperty(propertyId),220);return updated.length>0;
    }catch(error){setRouteStatus(`Routes were not changed: ${error.message||'routing service unavailable'}`);return false}finally{routeRefreshBusy=false}
  }
  function editRoute(propertyId,key){
    const property=window.OTPropertyStore.getProperty(propertyId),label=policy.config.displayCategories.find(item=>item.key===key)?.label||key,current=routeForDisplay(property,key);let panel=document.querySelector('#routeEditPanel');if(!panel){panel=document.createElement('aside');panel.id='routeEditPanel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');document.body.append(panel)}const airport=key==='airport';
    panel.innerHTML=`<div class="panel-head"><div><b>Edit ${safe(label)} route</b><p>Enter routed values from a directions result. Saving confirms and locks these values.</p></div><button class="drawer-close" data-route-close aria-label="Close">×</button></div><label>Destination name<input data-route-name value="${safe(airport?policy.config.airport.name:current.name)}"${airport?' readonly':''}></label><label>Full address<input data-route-address value="${safe(airport?policy.config.airport.address:current.address)}"${airport?' readonly':''}></label><div class="route-edit-grid"><label>Routed miles<input data-route-miles type="number" min="0" step="0.1" value="${current.routeMiles??''}"></label><label>Routed minutes<input data-route-minutes type="number" min="0" step="1" value="${current.routeMinutes??''}"></label></div><label>Date checked<input data-route-date type="date" value="${safe((current.checkedAt||new Date().toISOString()).slice(0,10))}"></label><div class="form-message" data-route-message></div><div class="form-actions"><button class="secondary" data-route-save>Save and lock route</button><button class="secondary outline" data-route-close>Cancel</button></div>`;panel.hidden=false;
    const close=()=>{panel.hidden=true;document.querySelector(`[data-stable-route-edit="${key}"]`)?.focus()};panel.querySelectorAll('[data-route-close]').forEach(button=>button.onclick=close);panel.querySelector('[data-route-save]').onclick=()=>{const miles=panel.querySelector('[data-route-miles]').value.trim(),minutes=panel.querySelector('[data-route-minutes]').value.trim();if(!finite(miles)||!finite(minutes)||Number(miles)<0||Number(minutes)<0){panel.querySelector('[data-route-message]').textContent='Enter valid routed mileage and minutes.';return}const base=airport?policy.config.airport:current,updated={...base,type:key,category:label,name:panel.querySelector('[data-route-name]').value.trim(),address:panel.querySelector('[data-route-address]').value.trim(),routeMiles:Number(miles),routeMinutes:Number(minutes),checkedAt:panel.querySelector('[data-route-date]').value,source:'user-confirmed',locked:true};const saved=window.OTCanonicalPropertyUpdate(propertyId,currentProperty=>{const previous=Array.isArray(currentProperty.destinations)?currentProperty.destinations:[],removed=previous.filter(item=>policy.categoryKey(item)===(key==='homeImprovement'?'home-improvement':key)||(key==='airport'&&policy.categoryKey(item)==='other-airport')),retained=previous.filter(item=>!removed.includes(item)),now=new Date().toISOString();return {...currentProperty,destinations:[...retained,updated],routeHistory:[...(currentProperty.routeHistory||[]),...removed.map(item=>({...policy.normalizedDestination(item),archivedAt:now}))].slice(-30),routeState:{...(currentProperty.routeState||{}),updatedAt:now},fieldSources:{...(currentProperty.fieldSources||{}),[`routes.${key}`]:'user-confirmed'},updatedAt:now}},`Confirm ${label} route data`);if(!saved){panel.querySelector('[data-route-message]').textContent='Route data could not be saved. Prior data was preserved.';return}close();setTimeout(()=>window.openProperty(propertyId),220)};setTimeout(()=>panel.querySelector('[data-route-miles]')?.focus(),0);
  }
  function unlockRoute(propertyId,key){
    if(!confirm('Unlock this route for automatic refresh? The saved route remains in place until a better valid routed result is found.'))return false;
    const changed=window.OTCanonicalPropertyUpdate(propertyId,current=>{const category=key==='homeImprovement'?'home-improvement':key,now=new Date().toISOString(),destinations=(current.destinations||[]).map(item=>policy.categoryKey(item)===category?{...item,source:'user-unlocked',locked:false,unlockedAt:now}:item),fieldSources={...(current.fieldSources||{})};delete fieldSources[`routes.${key}`];return {...current,destinations,fieldSources,routeState:{...(current.routeState||{}),updatedAt:now},updatedAt:now}},'Unlock route for automatic refresh');
    if(changed)setTimeout(()=>window.openProperty(propertyId),220);return changed;
  }
  function install(){
    window.refreshRoutes=refreshRoutes;window.OTRouteEditor={open:editRoute,unlock:unlockRoute};new MutationObserver(compactDossier).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',event=>{const open=event.target.closest('[data-stable-route-open]'),edit=event.target.closest('[data-stable-route-edit]'),unlock=event.target.closest('[data-stable-route-unlock]');if(!open&&!edit&&!unlock)return;const id=document.querySelector('#drawer .prop-id')?.textContent?.trim(),property=id&&window.OTPropertyStore.getProperty(id);if(!property)return;if(unlock){unlockRoute(id,unlock.dataset.stableRouteUnlock);return}if(edit){editRoute(id,edit.dataset.stableRouteEdit);return}const key=open.dataset.stableRouteOpen,destination=routeForDisplay(property,key),link=routeLink(property,destination);if(!link.ok){alert(link.error);return}window.open(link.url,'_blank','noopener')});document.addEventListener('keydown',event=>{const panel=document.querySelector('#routeEditPanel');if(event.key==='Escape'&&panel&&!panel.hidden){event.preventDefault();panel.querySelector('[data-route-close]')?.click()}});compactDossier();
  }
  window.addEventListener('DOMContentLoaded',install);
  window.OTStabilization={routeLink,isVerifiedPin,routeRows,importedFacts,refreshRoutes,runRegressionChecks(){const a={id:'A',lat:35,lng:-84,locationConfidence:'verified',destinations:[policy.canonicalAirport({routeMiles:45,routeMinutes:65}),{category:'Grocery',name:'A Grocery',address:'Athens, TN',lat:35.4,lng:-84.5,searchType:'supermarket',searchCategory:'shop',routeMiles:10.25,routeMinutes:18,source:'user-confirmed',locked:true}]},b={id:'B',lat:36,lng:-83,locationConfidence:'verified',destinations:[policy.canonicalAirport({routeMiles:70,routeMinutes:90}),{category:'Grocery',name:'B Grocery',routeMiles:20,routeMinutes:35}]},link=routeLink(a,policy.activeRoute(a,'airport')),manual=policy.activeRoute(a,'grocery'),costcoCandidates=practicalCandidates([{name:'Costco',address:'Knoxville, TN',lat:35.9,lng:-84.1,searchType:'wholesale',searchCategory:'shop'},{name:'Costco Gasoline',address:'Knoxville, TN',lat:35.9,lng:-84.1,searchType:'fuel',searchCategory:'amenity'},{name:'Costco Greenway',address:'Knoxville, TN',lat:35.9,lng:-84.1,searchType:'cycleway',searchCategory:'highway'}],'costco');const checks={propertySpecific:manual.name!==policy.activeRoute(b,'grocery').name,validUrl:link.ok&&link.url.startsWith('https://www.google.com/maps/dir/'),correctOrigin:decodeURIComponent(link.url).includes('origin=35,-84'),missingOrigin:!routeLink({},policy.activeRoute(a,'airport')).ok,missingDestination:!routeLink(a,policy.normalizedDestination({},'costco')).ok,manualRouteProtected:sourceConfirmed(manual),compactRowsHideAdministrativeLocks:!routeRows(a).includes('Unlock for automatic refresh')&&sourceConfirmed(manual),noStraightLineSubstitution:policy.activeRoute(a,'costco')===null,verifiedPinRequired:isVerifiedPin(a)&&!isVerifiedPin({...a,locationConfidence:'review'}),cleanDisplay:policy.formatMiles(8.36)==='8.4 mi'&&policy.formatDuration(72)==='1 hr 12 min',tysOnly:policy.activeRoute(a,'airport').code==='TYS',costcoWarehouseOnly:costcoCandidates.length===1&&costcoCandidates[0].name==='Costco'};return {passed:Object.values(checks).every(Boolean),checks}}};
})();
