/* Zillow Facts & Features parser. Deterministic, source-neutral, and intentionally conservative. */
(()=>{
  const VERSION='1.0.0', PRIORITY=Object.freeze({'user-confirmed':1,county:2,'user-entered':3,zillow:4,listing:5,inferred:6});
  const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
  const number=value=>{const n=Number(String(value).replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:null};
  const match=(text,re)=>{const found=String(text).match(re);return found?clean(found[1]):null};
  const fact=(field,label,value,raw,{score=true,cost=false,confidence='medium'}={})=>value===null||value===''?null:{field,label,value,normalized:value,matchedText:raw||'',sourceSection:'Facts & Features',confidence,scoringRelevance:score,costRelevance:cost};
  function parse(text=''){
    const raw=String(text||''),facts=[],add=(...args)=>{const value=fact(...args);if(value)facts.push(value)};
    const pick=(field,label,re,opts)=>{const value=match(raw,re);add(field,label,value,value,opts)};
    pick('beds','Bedrooms',/(?:Bedrooms?|Beds?)\s*[:\-]?\s*(\d+(?:\.\d+)?)/i); pick('baths','Bathrooms',/(?:Bathrooms?|Baths?)\s*[:\-]?\s*(\d+(?:\.\d+)?)/i);
    pick('sqft','Living area',/(?:Living area|Interior area|Finished area|Living space)\s*[:\-]?\s*([\d,]+)\s*(?:sq\.?\s*ft)?/i);pick('structureArea','Structure area',/(?:Structure area|Building area)\s*[:\-]?\s*([\d,]+)/i,{score:false});pick('yearBuilt','Year built',/(?:Year built)\s*[:\-]?\s*(\d{4})/i);pick('acres','Acreage',/(?:Lot size|Lot area|Acreage)\s*[:\-]?\s*([\d,.]+)\s*(?:acres?|ac)/i);pick('parcelNumber','Parcel number',/(?:Parcel number|APN|Parcel ID)\s*[:#\-]?\s*([\w-]+)/i,{score:false});pick('homeType','Home type',/(?:Home type|Property type)\s*[:\-]?\s*([^\n•]+)/i);pick('stories','Levels or stories',/(?:Levels?|Stories)\s*[:\-]?\s*([^\n•]+)/i,{score:false});pick('dateListed','Date listed',/(?:Date listed)\s*[:\-]?\s*([^\n•]+)/i,{score:false});
    pick('roof','Roof',/(?:Roof)\s*[:\-]?\s*([^\n•]+)/i,{score:false});pick('exterior','Exterior material',/(?:Exterior|Construction materials?)\s*[:\-]?\s*([^\n•]+)/i,{score:false});
    const bool=(field,label,re,opts={})=>{if(re.test(raw))add(field,label,'yes',raw.match(re)[0],opts)}; const lower=raw.toLowerCase();
    bool('deck','Deck',/\bdeck\b/i,{score:false});bool('patio','Patio',/\bpatio\b/i,{score:false});bool('porch','Porch',/\bporch\b/i,{score:false});bool('fencing','Fencing',/\b(fenced|fencing)\b/i,{score:false});bool('garage','Garage',/\bgarage\b/i);bool('carport','Carport',/\bcarport\b/i);bool('barn','Barn',/\bbarns?\b/i);bool('workshop','Workshop',/\b(workshop|shop building)\b/i);bool('storageBuilding','Storage building',/\b(storage (?:building|shed)|shed)\b/i);
    ['wooded','private','levelLand','slopedLand','rollingTerrain','clearedLand','pasture','mountainView'].forEach(([field,label,re])=>{});const land=[['wooded','Wooded',/\bwooded\b/i],['private','Private',/\bprivate\b/i],['levelLand','Level land',/\b(level|flat)\b/i],['slopedLand','Sloped land',/\bsloped?\b/i],['rollingTerrain','Rolling terrain',/\brolling\b/i],['clearedLand','Cleared land',/\bcleared\b/i],['pasture','Pasture',/\bpasture\b/i],['mountainView','Mountain view',/\bmountain views?\b/i],['creek','Creek',/\bcreek\b/i],['stream','Stream',/\bstream\b/i],['spring','Spring',/\bspring\b/i],['pond','Pond',/\bpond\b/i],['waterfront','Waterfront',/\bwaterfront\b/i]];land.forEach(([f,l,re])=>bool(f,l,re));
    if(/\bseptic\b/i.test(raw))add('septicOrSewer','Septic',/connected|installed|existing septic/i.test(raw)?'verified':'recorded',raw.match(/[^.\n]*septic[^.\n]*/i)?.[0],{cost:true});else if(/\bsewer\b/i.test(raw))add('septicOrSewer','Sewer',/connected|installed|public sewer/i.test(raw)?'verified':'available',raw.match(/[^.\n]*sewer[^.\n]*/i)?.[0],{cost:true});
    if(/\bwell\b/i.test(raw))add('waterSource','Well',/existing|private well|connected/i.test(raw)?'verified-well':'recorded',raw.match(/[^.\n]*well[^.\n]*/i)?.[0],{cost:true});else if(/public water|city water/i.test(raw))add('waterSource','Public water',/connected|served by/i.test(raw)?'public-water':'available',raw.match(/[^.\n]*(?:public|city) water[^.\n]*/i)?.[0],{cost:true});
    if(/\b(electric|electricity|power)\b/i.test(raw))add('electric','Electric service',/connected|active|on site/i.test(raw)?'verified':'available',raw.match(/[^.\n]*(?:electric|electricity|power)[^.\n]*/i)?.[0]); if(/\b(internet|cable)\b/i.test(raw))add('internet','Internet / cable',/connected|fiber installed/i.test(raw)?'verified':'available',raw.match(/[^.\n]*(?:internet|cable)[^.\n]*/i)?.[0]);
    pick('hoaAmount','HOA amount',/(?:HOA(?: fee)?|Homeowners association)\s*[:\-]?\s*\$?([\d,]+)/i,{score:true});pick('annualTaxes','Annual property taxes',/(?:Annual taxes|Property tax)\s*[:\-]?\s*\$?([\d,]+)/i,{score:true});pick('assessedValue','Assessed value',/(?:Assessed value)\s*[:\-]?\s*\$?([\d,]+)/i,{score:true});
    return {version:VERSION,rawText:raw,facts,found:facts.length,ignored:raw?Math.max(0,raw.split(/\n|•/).filter(Boolean).length-facts.length):0};
  }
  function sourceFor(record,field){return record?.fieldSources?.[field]||'user-entered'}
  function compare(existing,candidate){return String(existing??'').trim().toLowerCase()===String(candidate??'').trim().toLowerCase()}
  window.OTZillowFacts={VERSION,PRIORITY,parse,sourceFor,compare,runRegressionChecks(){const r=parse('Bedrooms: 3\nBathrooms: 2.5\nLiving area: 1,850 sqft\nLot size: 12.4 acres\nYear built: 1999\nPrivate well, existing septic, electric connected, wooded, sloped, mountain views, creek, barn, HOA: $20');const fields=r.facts.map(x=>x.field);const checks={core:['beds','baths','sqft','acres','yearBuilt'].every(x=>fields.includes(x)),land:['wooded','slopedLand','mountainView','creek'].every(x=>fields.includes(x)),utilities:['waterSource','septicOrSewer','electric'].every(x=>fields.includes(x)),sourcePriority:PRIORITY['user-confirmed']<PRIORITY.zillow,blankSafe:parse('').found===0};return {passed:Object.values(checks).every(Boolean),checks}}};
})();
