#!/usr/bin/env node
'use strict';
/* Fixture-only Version 5.0 verification. It never reads or writes browser storage. */
const fs=require('fs'),path=require('path'),vm=require('vm'),zlib=require('zlib'),root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const listeners={},document={readyState:'loading',getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:(name,handler)=>{listeners[name]=handler},createElement:()=>({}),body:{}},context={window:{addEventListener:()=>{},fetch:async()=>{throw new Error('offline fixture')}},document,MutationObserver:function(){this.observe=()=>{}},structuredClone,Math,Number,Object,Array,JSON,Date,URL,URLSearchParams,TextDecoder,TextEncoder,Blob,Response,DecompressionStream,encodeURIComponent,setTimeout:()=>0,clearTimeout:()=>{},confirm:()=>true};context.window.window=context.window;vm.createContext(context);for(const file of ['parcel-intelligence.js','parcel-workflow.js'])vm.runInContext(read(file),context);
const parcel=context.window.OTParcelIntelligence,workflow=context.window.OTParcelWorkflow,ring=[[-83.684,35.712],[-83.68,35.712],[-83.68,35.716],[-83.684,35.716],[-83.684,35.712]],geo={type:'FeatureCollection',features:[{type:'Feature',properties:{PARCELID:'78-001',ACRES:4.5},geometry:{type:'Polygon',coordinates:[ring]}}]},parsed=parcel.parseBoundaryText('parcel.geojson',JSON.stringify(geo)),kml=parcel.parseBoundaryText('parcel.kml',`<kml><Placemark><Polygon><outerBoundaryIs><LinearRing><coordinates>${ring.map(pair=>pair.join(',')).join(' ')}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></kml>`),gpx=parcel.parseBoundaryText('parcel.gpx',`<gpx><trk><trkseg>${ring.map(pair=>`<trkpt lat="${pair[1]}" lon="${pair[0]}"/>`).join('')}</trkseg></trk></gpx>`),image=parcel.parseBoundaryText('county-map.png','');
let openGpxRejected=false;try{parcel.parseBoundaryText('open.gpx','<gpx><trk><trkseg><trkpt lat="35.71" lon="-83.68"/><trkpt lat="35.72" lon="-83.68"/><trkpt lat="35.73" lon="-83.67"/><trkpt lat="35.74" lon="-83.66"/></trkseg></trk></gpx>')}catch{openGpxRejected=true}
const secondRing=ring.map(pair=>[pair[0]+.006,pair[1]]),multi=parcel.combineFeatures([{type:'Feature',properties:{PARCELID:'78-001'},geometry:{type:'Polygon',coordinates:[ring]}},{type:'Feature',properties:{PARCELID:'78-002'},geometry:{type:'Polygon',coordinates:[secondRing]}}]),base={id:'OT-V5-FIXTURE',name:'V5 Fixture',address:'1 Fixture Rd, Sevierville, TN 37862',lat:35.714,lng:-83.682,acres:9,notes:'preserve me',futureField:{nested:true},parcel:{},parcelIntelligence:{},activityHistory:[]},first=workflow.confirmedRecord(base,{...parsed,source:'Fixture GeoJSON'}),replacement=workflow.confirmedRecord(first,{geometry:multi.geometry,parcels:multi.parcels,source:'Fixture multi-parcel'}),analysis=workflow.analysisFor(replacement,replacement.parcelGeometry,{parcels:replacement.parcelIntelligence.parcels}),revertedGeometry=replacement.parcelBoundaryHistory.at(-1).geometry;
function zipSingle(name,content){const nameBytes=Buffer.from(name),raw=Buffer.from(content),compressed=zlib.deflateRawSync(raw),local=Buffer.alloc(30),central=Buffer.alloc(46),eocd=Buffer.alloc(22);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(8,8);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(nameBytes.length,26);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(8,10);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(raw.length,24);central.writeUInt16LE(nameBytes.length,28);central.writeUInt32LE(0,42);const directoryOffset=local.length+nameBytes.length+compressed.length,directorySize=central.length+nameBytes.length;eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(1,8);eocd.writeUInt16LE(1,10);eocd.writeUInt32LE(directorySize,12);eocd.writeUInt32LE(directoryOffset,16);return Buffer.concat([local,nameBytes,compressed,central,nameBytes,eocd])}
function polygonShapefile(points){const contentBytes=48+points.length*16,total=100+8+contentBytes,buffer=Buffer.alloc(total),view=new DataView(buffer.buffer,buffer.byteOffset,buffer.byteLength);view.setInt32(0,9994,false);view.setInt32(24,total/2,false);view.setInt32(28,1000,true);view.setInt32(32,5,true);const xs=points.map(point=>point[0]),ys=points.map(point=>point[1]),bbox=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];bbox.forEach((value,index)=>view.setFloat64(36+index*8,value,true));view.setInt32(100,1,false);view.setInt32(104,contentBytes/2,false);view.setInt32(108,5,true);bbox.forEach((value,index)=>view.setFloat64(112+index*8,value,true));view.setInt32(144,1,true);view.setInt32(148,points.length,true);view.setInt32(152,0,true);points.forEach((point,index)=>{view.setFloat64(156+index*16,point[0],true);view.setFloat64(164+index*16,point[1],true)});return buffer}
(async()=>{const zip=zipSingle('doc.kml',`<kml><Polygon><outerBoundaryIs><LinearRing><coordinates>${ring.map(pair=>pair.join(',')).join(' ')}</coordinates></LinearRing></outerBoundaryIs></Polygon></kml>`),kmz=await parcel.parseBoundaryFile({name:'parcel.kmz',arrayBuffer:async()=>zip.buffer.slice(zip.byteOffset,zip.byteOffset+zip.byteLength)}),shapeZip=zipSingle('parcel.shp',polygonShapefile(ring)),shape=await parcel.parseBoundaryFile({name:'parcel.zip',arrayBuffer:async()=>shapeZip.buffer.slice(shapeZip.byteOffset,shapeZip.byteOffset+shapeZip.byteLength)}),html=read('index.html'),app=read('app.js'),planning=read('planning.js'),overlays=read('overlay-manager.js'),workflowSource=read('parcel-workflow.js'),styles=read('styles.css'),stabilization=read('stabilization.js'),recovery=read('recovery.js'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]),duplicateIds=ids.filter((id,index)=>ids.indexOf(id)!==index),checks={
  geoJsonImports:parsed.geometry.type==='Polygon'&&parsed.parcelIds[0]==='78-001'&&parsed.gisAcres>0,
  kmlImports:kml.geometry.type==='Polygon'&&kml.gisAcres>0,
  kmzImports:kmz.geometry.type==='Polygon'&&/KMZ/.test(kmz.source),
  zippedShapefileImports:shape.geometry.type==='Polygon'&&/Shapefile/.test(shape.source)&&shape.gisAcres>0,
  closedGpxOnly:gpx.geometry.type==='Polygon'&&openGpxRejected,
  imageIsReferenceOnly:image.geometry===null&&image.failure.code==='image-georeference-required'&&/not converted into fabricated/i.test(image.failure.message),
  multiParcelIdentity:multi.geometry.type==='MultiPolygon'&&multi.parcels.length===2&&multi.parcelIds.join(',')==='78-001,78-002',
  unknownFieldsSurvive:first.futureField.nested&&first.notes==='preserve me',
  confirmationIsExplicitState:first.parcelIntelligence.state.id==='user-corrected'&&first.parcelIntelligence.validation.userConfirmed,
  replacementHistoryIsRecoverable:replacement.parcelBoundaryHistory.length===1&&JSON.stringify(revertedGeometry)===JSON.stringify(first.parcelGeometry),
  analysisIsPropertyScoped:analysis.geometryFingerprint&&analysis.parcelCount===2&&analysis.combinedAcreage>0,
  dossierUsesFourDecisionTabs:/tabs=\['Overview','Property','Map & Site','Research'\]/.test(app)&&!planning.includes("data-dossier-tab=\"Site Planning\""),
  overlayManagerAvailable:overlays.includes("name==='compare'")&&overlays.includes("minimize('dossier')")&&overlays.includes('ot-drag-positioned')&&styles.includes('.panel-dock'),
  fixParcelUiPresent:['parcelFixPanel','parcelRetryBtn','parcelSelectMapBtn','parcelFixFileInput','parcelDrawBtn','parcelConfirmBtn','parcelRevertBtn'].every(id=>ids.includes(id)),
  noDuplicateHtmlIds:duplicateIds.length===0,
  noStartupPropertyWrites:!workflowSource.includes('localStorage.setItem')&&!workflowSource.includes('localStorage.removeItem'),
  viewportGuards:styles.includes('max-height:calc(100dvh - 88px)')&&styles.includes('height:min(86dvh,820px)'),
  hiddenParcelSectionsStayHidden:styles.includes('.parcel-reference-panel[hidden]')&&styles.includes('.parcel-fix-actions[hidden]{display:none!important}'),
  mobileWorkspaceCannotBeStranded:styles.includes('[data-panel-minimize],.panel-close-btn,.panel-dock{display:none!important}'),
  dossierMenuActionsAreUnique:stabilization.includes('seenLabels=new Set')&&stabilization.includes('fixParcel.dataset.fixParcel=property.id'),
  discardReturnsToSavedState:workflowSource.includes("addEventListener('click',discardProposal)")&&workflowSource.includes('The unsaved proposal was discarded.'),
  emptyOriginDoesNotRaiseDataLossAlert:recovery.includes('if(priorCount>count)')&&!recovery.includes('if(!count||'),
  backgroundStages:['location','parcel','terrain'].every(stage=>read('smart-import.js').includes(`data-creation-stage="${stage}"`))
 };for(const [name,passed] of Object.entries(checks))console.log(`${passed?'PASS':'FAIL'} ${name}`);if(!Object.values(checks).every(Boolean)){console.error(`Version 5.0 verification failed at: ${Object.entries(checks).filter(([,passed])=>!passed).map(([name])=>name).join(', ')}`);process.exitCode=1}else console.log(`PASS Version 5.0 parcel recovery and interface foundation (${Object.keys(checks).length} checks).`)})();
